In [1]:
# SQL-PYTHON Connect

In [2]:
#!pip install sqlalchemy
#!pip install pymysql

Library         Type              Speed                Best Use 
CaseMySQL    ConnectorOfficial   Moderate         Official support & latest features
mysqlclient  C-Wrapper          Fastest           High-performance production apps
PyMySQL      Pure Python         Moderate         Lightweight, easy-to-install scripts
SQLAlchemy   ORM/Toolkit          N/A             Large, maintainable web applications

In [3]:
# libraries (install if required)
from sqlalchemy import create_engine, text
import pandas as pd
import os

## Python,SQL

In [5]:
# URL-encode special chars in password if any (e.g., # -> %23, @ -> %40)  #Pass@123 - Pass%40123
engine1 = create_engine("mysql+pymysql://piuser:piit2026@localhost:3306/piit")
print(engine1)
#setting up connection mysql with user name - piuser, pwd - piit2026 and to database piit at port no  3306

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [6]:
# function to run the query with parameters or query
def q(sql, **params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

The code in the upper cell is a "wrapper function." It simplifies the complex steps of opening, using, and closing a database connection into a single line of code.
Here is the breakdown of why each part is important:

1. with engine1.connect() as conn: This is a Context Manager.

The Problem: Normally, when you connect to a database, you must remember to close the connection when you're done. If you forget, the database will eventually run out of available "slots" and crash.

The Solution: The with statement guarantees that the connection is automatically closed the moment the code inside the block finishes, even if your code crashes or encounters an error.

2. Think of text(sql) as a safety filter and a formatter that stands between your Python code and your Database. Normally, a SQL query is just a plain "string of text". To Python, it’s no different than a sentence in a book. But the database needs that "text" to be handled very carefully.

- Here is why text() is essential:
  1. It creates "Blanks" for variables (Placeholders)
  2. Without text(), if you wanted to search for a user, you might be tempted to do this:"SELECT * FROM users WHERE name = " + user_name (This is dangerous!)
  3. With text(), you use a colon to create a named blank:text("SELECT * FROM users WHERE name = :user_name"). SQLAlchemy sees that :user_name and says, "Okay, I'll
  wait to fill that blank with a safe value later."
  4. It prevents "SQL Injection" (The Security Guard): Imagine a bad guy tries to log in. Instead of a name, they type:' OR 1=1; --Without text(): The database might
  run that command, see that 1=1 is always true, and accidentally log the hacker into every account.
  5. With text(): It realizes that the hacker's input is just a piece of data, not a command. It treats the malicious code like a harmless, weirdly named person.
  6. It makes SQL "Portable"Different databases sometimes use different symbols for things. text() acts as a universal translator. It ensures that the way you write    your query in Python will be understood correctly by MySQL, even if you eventually switch to a different database like PostgreSQL.

3. params=params: This is the Parameter Binding step.

The Old Way: "Gluing Strings" (Dangerous): Imagine you want to withdraw money. You write your request on a piece of paper:"Withdraw 100 from account of [NAME]"
The Attack: A hacker writes their name as: John; AND GIVE ME EVERYONE ELSES MONEY TOO.
The Result: The paper now says: "Withdraw $100 from account of John; AND GIVE ME EVERYONE ELSES MONEY TOO".
The Problem: The bank (Database) reads the whole paper as one long instruction and follows it. This is SQL Injection.

The New Way: "Parameter Binding" (Safe)This is what params=params does. It separates the Instruction from the Data.
The Instruction (The Template): You give the teller a pre-printed form:"Withdraw $100 from account of :user_name"
The Data (The Variable): You hand the teller a separate ID card that says:John; AND GIVE ME EVERYONE ELSES MONEY TOO

Why it works:
- The Database is smart: Because you used text() and params, the database compiles the "Instruction" first.
- It locks the plan: It decides, "Okay, I am going to look up one name in the account table.
- "The "Slot" is too small: When you hand over the hacker's text, the database doesn't read it as a new command. It treats that whole long sentence as one single, very weird name.
- Zero Risk: It looks for a person literally named "John; AND GIVE ME EVERYONE".... Since that person doesn't exist, the query just returns "No results" instead of blowing up the bank.

4. **params (The double asterisks): This allows your function to accept Keyword Arguments.It lets you pass variables directly by name when you call the function.
- Behind the scenes: It takes all the named arguments you provide and packs them into a dictionary to be used by the SQL query.
- Putting it all together.
  
If you run this code: pythondf = q("SELECT * FROM products WHERE price > :min_price", min_price=50)

This is what happens internally:
- **params captures {'min_price': 50}.
- engine1.connect() opens a door to your MySQL database.
- text() prepares the SQL statement.
- pd.read_sql sends the command and the 50 to the database.
- MySQL returns the data, and Pandas turns it into a table (DataFrame).The with block finishes and slams the door shut (closes the connection).The function returns your table.

5. return pd.read_sql(text(sql), conn, params=params) means:
- text(sql): This is the instruction of what to grab.
- conn: This is the physical path to the warehouse.
- params: These are the specific filters (like "only show blue items").

In [7]:
q("SELECT * FROM students")

,id,name,branch,score,exam_date,remarks
0,1,Rick Johnson,Mechanical,63.68,2025-03-30,Average
1,2,Shannon Hall,Electrical,74.35,2024-03-28,Outstanding
2,3,Stephanie Flores,Computer Science,88.97,2024-05-17,Average
3,4,Keith Ferrell,Civil,75.00,2025-06-22,Average
4,5,Corey Allen,Computer Science,63.14,2025-05-17,Needs Improvement
5,6,Brittney Galloway,Computer Science,51.85,2025-02-01,Needs Improvement
6,7,Kathryn Gordon,Electrical,70.88,2023-12-10,Outstanding
7,8,Julia Warren,Electrical,63.07,2023-11-21,Needs Improvement
8,9,Carol Cunningham,Computer Science,87.88,2024-07-29,Good
9,10,Cassidy Crawford,Civil,52.46,2025-02-25,Excellent
10,11,William Sanders,Electronics,53.81,2024-01-02,Average
11,12,Amanda Chapman,Mechanical,58.49,2025-03-04,Outstanding
12,13,Amanda Reese,Electronics,54.26,2023-10-15,Average
13,14,Katherine Morrow,Civil,85.95,2023-09-23,Outstanding
14,15,Daniel Graham,Computer Science,65.00,2024-10-27,Needs Improvement
15,16,Alexander Rivers,Electrical,93.69,2024-11-09,Excellent
16,17,Sarah Gordon,Computer Science,86.08,2023-11-24,Excellent
17,18,Lauren Weaver,Electronics,50.65,2025-01-18,Good
18,19,Kim Herrera,Electronics,54.02,2025-01-18,Average
19,20,Rhonda Sullivan,Civil,88.30,2024-02-04,Outstanding
20,21,Sara Gomez,Electronics,64.88,2024-12-01,Needs Improvement
21,22,Emily Moore,Civil,65.21,2024-03-15,Outstanding
22,23,Robert Delacruz,Civil,51.92,2024-02-15,Good
23,24,Shawn Simon,Computer Science,94.68,2023-12-22,Outstanding
24,25,Danielle Le,Mechanical,91.50,2024-02-28,Outstanding
25,26,Alexandra Alexander,Electronics,55.09,2025-04-13,Outstanding
26,27,Anna Zimmerman,Civil,83.72,2024-10-28,Average
27,28,Michael Johnson,Electronics,78.04,2024-07-05,Average
28,29,Michael Higgins DDS,Computer Science,90.45,2025-02-20,Outstanding
29,30,Jodi Chapman,Electronics,54.13,2025-07-04,Needs Improvement
30,9991,Demo One,Electrical,88.25,2025-06-15,Good
31,9992,Demo Two,Civil,72.50,2025-06-20,Average
32,2001,Demo One,Electrical,88.25,2025-06-15,Good
33,2002,Demo Two,Civil,72.50,2025-06-20,Average

select * from students;
select * from students where branch = "Civil";
select * from students where branch in ('Civil','Mechanical');
select * from students where name like 'R%';
select sum(score) from students;
select max(score) from students;
select min(score) from students;
select avg(score) from students;
select branch, avg(score) as avgscore from students group by branch;
select branch, avg(score) as avgscore, count(*) from students group by branch;
select * from students order by score desc;

## Pandas,SQL

In [8]:
df2 = pd.read_sql("SELECT * FROM students", engine1)
df2.shape
df2

,id,name,branch,score,exam_date,remarks
0,1,Rick Johnson,Mechanical,63.68,2025-03-30,Average
1,2,Shannon Hall,Electrical,74.35,2024-03-28,Outstanding
2,3,Stephanie Flores,Computer Science,88.97,2024-05-17,Average
3,4,Keith Ferrell,Civil,75.00,2025-06-22,Average
4,5,Corey Allen,Computer Science,63.14,2025-05-17,Needs Improvement
5,6,Brittney Galloway,Computer Science,51.85,2025-02-01,Needs Improvement
6,7,Kathryn Gordon,Electrical,70.88,2023-12-10,Outstanding
7,8,Julia Warren,Electrical,63.07,2023-11-21,Needs Improvement
8,9,Carol Cunningham,Computer Science,87.88,2024-07-29,Good
9,10,Cassidy Crawford,Civil,52.46,2025-02-25,Excellent
10,11,William Sanders,Electronics,53.81,2024-01-02,Average
11,12,Amanda Chapman,Mechanical,58.49,2025-03-04,Outstanding
12,13,Amanda Reese,Electronics,54.26,2023-10-15,Average
13,14,Katherine Morrow,Civil,85.95,2023-09-23,Outstanding
14,15,Daniel Graham,Computer Science,65.00,2024-10-27,Needs Improvement
15,16,Alexander Rivers,Electrical,93.69,2024-11-09,Excellent
16,17,Sarah Gordon,Computer Science,86.08,2023-11-24,Excellent
17,18,Lauren Weaver,Electronics,50.65,2025-01-18,Good
18,19,Kim Herrera,Electronics,54.02,2025-01-18,Average
19,20,Rhonda Sullivan,Civil,88.30,2024-02-04,Outstanding
20,21,Sara Gomez,Electronics,64.88,2024-12-01,Needs Improvement
21,22,Emily Moore,Civil,65.21,2024-03-15,Outstanding
22,23,Robert Delacruz,Civil,51.92,2024-02-15,Good
23,24,Shawn Simon,Computer Science,94.68,2023-12-22,Outstanding
24,25,Danielle Le,Mechanical,91.50,2024-02-28,Outstanding
25,26,Alexandra Alexander,Electronics,55.09,2025-04-13,Outstanding
26,27,Anna Zimmerman,Civil,83.72,2024-10-28,Average
27,28,Michael Johnson,Electronics,78.04,2024-07-05,Average
28,29,Michael Higgins DDS,Computer Science,90.45,2025-02-20,Outstanding
29,30,Jodi Chapman,Electronics,54.13,2025-07-04,Needs Improvement
30,9991,Demo One,Electrical,88.25,2025-06-15,Good
31,9992,Demo Two,Civil,72.50,2025-06-20,Average
32,2001,Demo One,Electrical,88.25,2025-06-15,Good
33,2002,Demo Two,Civil,72.50,2025-06-20,Average

In [9]:
df2.groupby('branch')['score'].mean()

branch
Civil               71.951111
Computer Science    78.506250
Electrical          79.748333
Electronics         58.110000
Mechanical          71.223333
Name: score, dtype: float64

In [10]:
df2.groupby('remarks')['score'].mean()

remarks
Average              69.650
Excellent            77.410
Good                 73.390
Needs Improvement    60.345
Outstanding          77.490
Name: score, dtype: float64

In [11]:
df2.groupby(['branch','remarks'])['score'].mean()

branch            remarks
Civil             Average              75.930000
                  Excellent            52.460000
                  Good                 51.920000
                  Outstanding          79.820000
Computer Science  Average              88.970000
                  Excellent            86.080000
                  Good                 87.880000
                  Needs Improvement    59.996667
                  Outstanding          92.565000
Electrical        Excellent            93.690000
                  Good                 88.250000
                  Needs Improvement    63.070000
                  Outstanding          72.615000
Electronics       Average              60.032500
                  Good                 50.650000
                  Needs Improvement    59.505000
                  Outstanding          55.090000
Mechanical        Average              63.680000
                  Outstanding          74.995000
Name: score, dtype: float64

In [12]:
df2.groupby(['branch','remarks'])['score'].agg(['mean', 'min', 'max'])

                                         mean    min    max
branch           remarks
Civil            Average            75.930000  72.50  83.72
                 Excellent          52.460000  52.46  52.46
                 Good               51.920000  51.92  51.92
                 Outstanding        79.820000  65.21  88.30
Computer Science Average            88.970000  88.97  88.97
                 Excellent          86.080000  86.08  86.08
                 Good               87.880000  87.88  87.88
                 Needs Improvement  59.996667  51.85  65.00
                 Outstanding        92.565000  90.45  94.68
Electrical       Excellent          93.690000  93.69  93.69
                 Good               88.250000  88.25  88.25
                 Needs Improvement  63.070000  63.07  63.07
                 Outstanding        72.615000  70.88  74.35
Electronics      Average            60.032500  53.81  78.04
                 Good               50.650000  50.65  50.65
                 Needs Improvement  59.505000  54.13  64.88
                 Outstanding        55.090000  55.09  55.09
Mechanical       Average            63.680000  63.68  63.68
                 Outstanding        74.995000  58.49  91.50