# SQL commands from Python
- this will provide feel of sql commands from python env

In [1]:
# Testing

In [2]:
# libraries
from sqlalchemy import create_engine, text
import pandas as pd
import os

In [3]:
# URL-encode special chars in password if any (e.g., # -> %23, @ -> %40)
engine1 = create_engine("mysql+pymysql://piuser:piit2026@localhost:3306/piit")
engine1

Engine(mysql+pymysql://piuser:***@localhost:3306/piit)

In [4]:
# function
def q(sql, **params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

In [5]:
q

In [6]:
q('show tables;')

               Tables_in_piit
0                      aelita
1                     authors
2                       books
3        customer_public_view
4      customer_sales_summary
5               customer_view
6              customerorders
7                   customers
8   east_region_sales_summary
9                  east_sales
10                  employees
11                math_scores
12                     mtcars
13         order_details_view
14                order_items
15                     orders
16         product_sales_view
17                   products
18       region_sales_summary
19                      sales
20                     sales1
21                     sales2
22         salesperson_totals
23             student_scores
24             student_totals
25                   students
26         subject_avg_scores
27                top_sellers

In [7]:
q("SELECT * FROM students LIMIT 5")

   id              name            branch  score  exam_date            remarks
0   1      Rick Johnson        Mechanical  63.68 2025-03-30            Average
1   2      Shannon Hall        Electrical  74.35 2024-03-28        Outstanding
2   3  Stephanie Flores  Computer Science  88.97 2024-05-17            Average
3   4     Keith Ferrell             Civil  75.00 2025-06-22            Average
4   5       Corey Allen  Computer Science  63.14 2025-05-17  Needs Improvement

### Queries

In [8]:
# filter rows (where)
q("""  SELECT id, name, branch, score  FROM students WHERE branch = :branch AND score >= :min_score
    ORDER BY score DESC   LIMIT 10 """, branch="Computer Science", min_score=80)

   id                 name            branch  score
0  24          Shawn Simon  Computer Science  94.68
1  29  Michael Higgins DDS  Computer Science  90.45
2   3     Stephanie Flores  Computer Science  88.97
3   9     Carol Cunningham  Computer Science  87.88
4  17         Sarah Gordon  Computer Science  86.08

In [9]:
#Aggregation (AVG, MIN, MAX)
q("""  SELECT COUNT(*) AS n_students, AVG(score) AS avg_score, MIN(score) AS min_score,
        MAX(score) AS max_score  FROM students """)

   n_students  avg_score  min_score  max_score
0          30  70.371667      50.65      94.68

In [10]:
# Group by branch
q("""     SELECT branch, COUNT(*) AS n, AVG(score) AS avg_score
    FROM students     GROUP BY branch     ORDER BY avg_score DESC""")

             branch  n  avg_score
0  Computer Science  8  78.506250
1        Electrical  4  75.497500
2             Civil  7  71.794286
3        Mechanical  3  71.223333
4       Electronics  8  58.110000

In [11]:
# Date filters (BETWEEN)
q("""  SELECT id, name, score, exam_date FROM students  WHERE exam_date BETWEEN :d1 AND :d2 
ORDER BY exam_date """, d1="2024-01-01", d2="2025-12-31")

    id                 name  score  exam_date
0   11      William Sanders  53.81 2024-01-02
1   20      Rhonda Sullivan  88.30 2024-02-04
2   23      Robert Delacruz  51.92 2024-02-15
3   25          Danielle Le  91.50 2024-02-28
4   22          Emily Moore  65.21 2024-03-15
5    2         Shannon Hall  74.35 2024-03-28
6    3     Stephanie Flores  88.97 2024-05-17
7   28      Michael Johnson  78.04 2024-07-05
8    9     Carol Cunningham  87.88 2024-07-29
9   15        Daniel Graham  65.00 2024-10-27
10  27       Anna Zimmerman  83.72 2024-10-28
11  16     Alexander Rivers  93.69 2024-11-09
12  21           Sara Gomez  64.88 2024-12-01
13  18        Lauren Weaver  50.65 2025-01-18
14  19          Kim Herrera  54.02 2025-01-18
15   6    Brittney Galloway  51.85 2025-02-01
16  29  Michael Higgins DDS  90.45 2025-02-20
17  10     Cassidy Crawford  52.46 2025-02-25
18  12       Amanda Chapman  58.49 2025-03-04
19   1         Rick Johnson  63.68 2025-03-30
20  26  Alexandra Alexander  55.09 2025-04-13
21   5          Corey Allen  63.14 2025-05-17
22   4        Keith Ferrell  75.00 2025-06-22
23  30         Jodi Chapman  54.13 2025-07-04

In [12]:
# Pattern matching (LIKE / case-insensitive)
q("""   SELECT id, name, remarks FROM students WHERE name LIKE :pat """, pat="A%")  # names starting with A, % matches zero or more of any characters.

   id                 name      remarks
0  12       Amanda Chapman  Outstanding
1  13         Amanda Reese      Average
2  16     Alexander Rivers    Excellent
3  26  Alexandra Alexander  Outstanding
4  27       Anna Zimmerman      Average

In [13]:
# Top N per branch (window function, MySQL 8+)
q("""   SELECT id, name, branch, score, rn FROM (   SELECT s.*, ROW_NUMBER() OVER (PARTITION BY branch ORDER BY score DESC) AS rn
        FROM students s ) t  WHERE rn <= 3  ORDER BY branch, rn """)

    id                 name            branch  score  rn
0   20      Rhonda Sullivan             Civil  88.30   1
1   14     Katherine Morrow             Civil  85.95   2
2   27       Anna Zimmerman             Civil  83.72   3
3   24          Shawn Simon  Computer Science  94.68   1
4   29  Michael Higgins DDS  Computer Science  90.45   2
5    3     Stephanie Flores  Computer Science  88.97   3
6   16     Alexander Rivers        Electrical  93.69   1
7    2         Shannon Hall        Electrical  74.35   2
8    7       Kathryn Gordon        Electrical  70.88   3
9   28      Michael Johnson       Electronics  78.04   1
10  21           Sara Gomez       Electronics  64.88   2
11  26  Alexandra Alexander       Electronics  55.09   3
12  25          Danielle Le        Mechanical  91.50   1
13   1         Rick Johnson        Mechanical  63.68   2
14  12       Amanda Chapman        Mechanical  58.49   3

`SELECT s.*, ROW_NUMBER() OVER (PARTITION BY branch ORDER BY score DESC) AS rn 
FROM students s` This creates a temporary list where students are grouped by their branch and ranked by score.
- PARTITION BY branch: Tells the database to slice the students into separate groups based on their branch. It treats "CS" and "ECE" as completely separate lists.
- ORDER BY score DESC: Inside each group, it sorts the students from the highest score to the lowest score.
- ROW_NUMBER() OVER (...) AS rn: This sequentially numbers the rows starting from 1 for each group. When the branch changes, the counter resets back to 1.

`SELECT * FROM (...) t WHERE rn <= 3`
- WHERE rn <= 3: It looks at the row numbers (rn) we just generated and throws away any student ranked 4th, 5th, or lower. Only ranks 1, 2, and 3 survive.

`ORDER BY branch, rn;`
- It groups all the 1st branch winners(Civil) together ranked 1 to 3.
- Then it shows all the 2nd branch(computer) together ranked 1 to 3.

In [14]:
# Bucketing scores (CASE)
q("""  SELECT  CASE  WHEN score >= 90 THEN 'A'  WHEN score >= 80 THEN 'B' WHEN score >= 70 THEN 'C'        WHEN score >= 60 THEN 'D'        ELSE 'F'      END AS grade,
      COUNT(*) AS n    FROM students    GROUP BY grade    ORDER BY grade""")

  grade   n
0     A   4
1     B   6
2     C   4
3     D   6
4     F  10

In [15]:
# Null handling (COALESCE) and derived columns
q("""   SELECT id, name, COALESCE(remarks, 'No remark') AS remarks_clean,   ROUND(score, 0) AS score_rounded
    FROM students    ORDER BY score_rounded DESC   LIMIT 10""")

   id                 name remarks_clean  score_rounded
0  24          Shawn Simon       Average           95.0
1  16     Alexander Rivers     Excellent           94.0
2  25          Danielle Le   Outstanding           92.0
3  29  Michael Higgins DDS   Outstanding           90.0
4   3     Stephanie Flores       Average           89.0
5   9     Carol Cunningham          Good           88.0
6  20      Rhonda Sullivan   Outstanding           88.0
7  14     Katherine Morrow   Outstanding           86.0
8  17         Sarah Gordon     Excellent           86.0
9  27       Anna Zimmerman       Average           84.0

## Advanced
-  Insert / Update (write ops)

In [17]:
from sqlalchemy import text

In [18]:
new_rows = [
    {"id": 9991, "name": "Demo One", "branch": "Electrical", "score": 88.25, "exam_date": "2025-06-15", "remarks": "Good"},
    {"id": 9992, "name": "Demo Two", "branch": "Civil",      "score": 72.5,  "exam_date": "2025-06-20", "remarks": "Average"},
]

In [19]:
with engine1.begin() as conn:  # transaction
    conn.execute(text("""
        INSERT INTO students (id, name, branch, score, exam_date, remarks)
        VALUES (:id, :name, :branch, :score, :exam_date, :remarks)
    """), new_rows)

In [22]:
# Update example
with engine1.begin() as conn:
    conn.execute(text("""  UPDATE students   SET remarks = :r WHERE score >= :min_score AND branch = :b  """), {"r": "Outstanding", "min_score": 90, "b": "Computer Science"})

In [23]:
q (""" Select * from students """)

,id,name,branch,score,exam_date,remarks
0,1,Rick Johnson,Mechanical,63.68,2025-03-30,Average
1,2,Shannon Hall,Electrical,74.35,2024-03-28,Outstanding
2,3,Stephanie Flores,Computer Science,88.97,2024-05-17,Average
3,4,Keith Ferrell,Civil,75.00,2025-06-22,Average
4,5,Corey Allen,Computer Science,63.14,2025-05-17,Needs Improvement
5,6,Brittney Galloway,Computer Science,51.85,2025-02-01,Needs Improvement
6,7,Kathryn Gordon,Electrical,70.88,2023-12-10,Outstanding
7,8,Julia Warren,Electrical,63.07,2023-11-21,Needs Improvement
8,9,Carol Cunningham,Computer Science,87.88,2024-07-29,Good
9,10,Cassidy Crawford,Civil,52.46,2025-02-25,Excellent
10,11,William Sanders,Electronics,53.81,2024-01-02,Average
11,12,Amanda Chapman,Mechanical,58.49,2025-03-04,Outstanding
12,13,Amanda Reese,Electronics,54.26,2023-10-15,Average
13,14,Katherine Morrow,Civil,85.95,2023-09-23,Outstanding
14,15,Daniel Graham,Computer Science,65.00,2024-10-27,Needs Improvement
15,16,Alexander Rivers,Electrical,93.69,2024-11-09,Excellent
16,17,Sarah Gordon,Computer Science,86.08,2023-11-24,Excellent
17,18,Lauren Weaver,Electronics,50.65,2025-01-18,Good
18,19,Kim Herrera,Electronics,54.02,2025-01-18,Average
19,20,Rhonda Sullivan,Civil,88.30,2024-02-04,Outstanding
20,21,Sara Gomez,Electronics,64.88,2024-12-01,Needs Improvement
21,22,Emily Moore,Civil,65.21,2024-03-15,Outstanding
22,23,Robert Delacruz,Civil,51.92,2024-02-15,Good
23,24,Shawn Simon,Computer Science,94.68,2023-12-22,Outstanding
24,25,Danielle Le,Mechanical,91.50,2024-02-28,Outstanding
25,26,Alexandra Alexander,Electronics,55.09,2025-04-13,Outstanding
26,27,Anna Zimmerman,Civil,83.72,2024-10-28,Average
27,28,Michael Johnson,Electronics,78.04,2024-07-05,Average
28,29,Michael Higgins DDS,Computer Science,90.45,2025-02-20,Outstanding
29,30,Jodi Chapman,Electronics,54.13,2025-07-04,Needs Improvement
30,9991,Demo One,Electrical,88.25,2025-06-15,Good
31,9992,Demo Two,Civil,72.50,2025-06-20,Average

In [24]:
#  Safe parameterized IN filter
branches = ["Mechanical", "Civil"]
placeholders = ", ".join([f":b{i}" for i in range(len(branches))])
params = {f"b{i}": v for i, v in enumerate(branches)}

q(f"""    SELECT id, name, branch, score   FROM students   WHERE branch IN ({placeholders})  ORDER BY score DESC """, **params)

      id              name      branch  score
0     25       Danielle Le  Mechanical  91.50
1     20   Rhonda Sullivan       Civil  88.30
2     14  Katherine Morrow       Civil  85.95
3     27    Anna Zimmerman       Civil  83.72
4      4     Keith Ferrell       Civil  75.00
5   9992          Demo Two       Civil  72.50
6     22       Emily Moore       Civil  65.21
7      1      Rick Johnson  Mechanical  63.68
8     12    Amanda Chapman  Mechanical  58.49
9     10  Cassidy Crawford       Civil  52.46
10    23   Robert Delacruz       Civil  51.92

#### Input Definition branches = ['Mechanical', 'Civil']

`branches = ['Mechanical', 'Civil']`

- Creates a Python list named branches.
- Contains the filtering values for the database query.

#### Placeholder Generation 

`placeholders = ','.join([f':b{i}' for i in range(len(branches))])`

- range(len(branches)) loops through the list indexes (0 and 1).
- The list comprehension creates a placeholder string for each index: [':b0', ':b1'].
- ',' .join(...) merges them with commas into a single string: ":b0,:b1".

#### Parameter Mapping 

`params = {f'b{i}': v for i, v in enumerate(branches)}`
- Use code with caution.enumerate(branches) extracts both index i and value v (e.g., 0, 'Mechanical').
- Dictionary comprehension pairs each placeholder key with its actual value.
- Creates the dictionary: {'b0': 'Mechanical', 'b1': 'Civil'}.

#### Query Execution

`q(f"SELECT id, name, branch, score FROM students WHERE branch IN ({placeholders}) ORDER BY score DESC", **params)`

- f"..." injects the placeholder string into the SQL text, resulting in IN (:b0,:b1).
- **params unpacks the dictionary to pass b0='Mechanical' and b1='Civil' as named arguments.
- The database driver safely binds these values to the placeholders before executing.

In [25]:
# Export a query to CSV directly from Pandas
df3 = q("SELECT id, name, branch, score, exam_date FROM students ORDER BY id")
df3.to_csv("C:/analytics/data/students_export.csv", index=False)

In [28]:
print(sorted(os.listdir("C:/analytics/data/")))

['sakila-db', 'sqlpractise1.xlsx', 'students_export.csv', 'studentsb2.csv', 'world-db']

## SQL Commands - run them in mysql

#### Peek at Data

SELECT * FROM students LIMIT 5;

#### Filter rows (WHERE, ORDER BY, LIMIT)

SELECT id, name, branch, score FROM students WHERE branch = 'Computer Science' AND score >= 80 ORDER BY score DESC LIMIT 10;

#### Aggregation (COUNT/AVG/MIN/MAX)

SELECT   COUNT(*)  AS n_students,  AVG(score) AS avg_score,  MIN(score) AS min_score,  MAX(score) AS max_score FROM students;

#### Group by branch

SELECT branch, COUNT(*) AS n, AVG(score) AS avg_score FROM students GROUP BY branch ORDER BY avg_score DESC;

#### Date filters (BETWEEN)

SELECT id, name, score, exam_date FROM students WHERE exam_date BETWEEN '2024-01-01' AND '2025-12-31' ORDER BY exam_date;

#### Pattern match (LIKE)
- names starting with A (case-sensitive depends on collation)
- case-insensitive regardless of column collation (utf8mb4 shown)

SELECT id, name, remarks FROM students WHERE name LIKE 'A%';

SELECT id, name, remarks FROM students WHERE name LIKE 'a%'; # same result like previous cell (case INsensitive by deault)

SELECT  id, name, remarks FROM students WHERE name COLLATE utf8mb4_bin LIKE 'a%'; # give empty set(CASE SENSITIVE)

#### Top 3 per branch (MySQL 8.0+ window function)

SELECT id, name, branch, score, rn FROM (   SELECT s.*, ROW_NUMBER() OVER (PARTITION BY branch ORDER BY score DESC) AS rn
  FROM students AS s ) AS t WHERE rn <= 3 ORDER BY branch, rn;

#### Bucket scores into grades (CASE)

SELECT   
CASE WHEN score >= 90 THEN 'A' WHEN score >= 80 THEN 'B' WHEN score >= 70 THEN 'C'  WHEN score >= 60 THEN 'D'    ELSE 'F' END AS grade,  
COUNT(*) AS n FROM students GROUP BY grade ORDER BY grade;

#### Null handling + derived columns

SELECT id,  name, COALESCE(remarks, 'No remark') AS remarks_clean,  ROUND(score, 0) AS score_rounded FROM students ORDER BY id LIMIT 10;

#### Insert rows

INSERT INTO students (id, name, branch, score, exam_date, remarks) VALUES   (2001, 'Demo One', 'Electrical', 88.25, '2025-06-15', 'Good'),  (2002, 'Demo Two', 'Civil',      72.50, '2025-06-20', 'Average');

#### Update rows

UPDATE students SET remarks = 'Outstanding' WHERE score >= 90  AND branch = 'Computer Science';

#### IN filter

SELECT id, name, branch, score FROM students WHERE branch IN ('Mechanical', 'Civil') ORDER BY score DESC;