# SQL Python connect

In [1]:
from sqlalchemy import create_engine, text
import pymysql
import pandas as pd
import os

In [2]:
engine1 = create_engine("mysql+pymysql://root:piit2026@localhost:3306/piit")
engine1

Engine(mysql+pymysql://root:***@localhost:3306/piit)

In [3]:
# function to run the query with parameters or query
def q(sql, **params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

In [4]:
q('show tables')

               Tables_in_piit
0                      aelita
1                     authors
2                       books
3        customer_public_view
4      customer_sales_summary
5               customer_view
6              customerorders
7                   customers
8                        dept
9   east_region_sales_summary
10                 east_sales
11                        emp
12                  employees
13                math_scores
14                     mtcars
15         order_details_view
16                order_items
17                     orders
18         product_sales_view
19                   products
20       region_sales_summary
21                      sales
22                     sales1
23                     sales2
24         salesperson_totals
25             student_scores
26             student_totals
27                   students
28         subject_avg_scores
29                top_sellers

In [5]:
q('show tables')

               Tables_in_piit
0                      aelita
1                     authors
2                       books
3        customer_public_view
4      customer_sales_summary
5               customer_view
6              customerorders
7                   customers
8                        dept
9   east_region_sales_summary
10                 east_sales
11                        emp
12                  employees
13                math_scores
14                     mtcars
15         order_details_view
16                order_items
17                     orders
18         product_sales_view
19                   products
20       region_sales_summary
21                      sales
22                     sales1
23                     sales2
24         salesperson_totals
25             student_scores
26             student_totals
27                   students
28         subject_avg_scores
29                top_sellers

In [6]:
q('select * from dept')

   deptno       dname       loc
0      10  ACCOUNTING  NEW YORK
1      20    RESEARCH    DALLAS
2      30       SALES   CHICAGO
3      40  OPERATIONS    BOSTON

In [7]:
q ('select * from emp')

    empno   ename        job     mgr    hiredate     sal    comm  deptno
0    1234  DHIRAJ    ANALYST  7839.0  1988-12-17  5000.0   100.0      10
1    1324    SHAN    ANALYST  7839.0  1988-12-17  4000.0    50.0      10
2    7369   SMITH      CLERK  7902.0  1980-12-17   800.0     NaN      20
3    7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0      30
4    7521    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0      30
5    7566   JONES    MANAGER  7839.0  1981-04-02  2975.0     NaN      20
6    7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0      30
7    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     NaN      30
8    7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0     NaN      10
9    7788   SCOTT    ANALYST  7566.0  1987-04-19  3000.0     NaN      20
10   7839    KING  PRESIDENT     NaN  1981-11-17  5000.0     NaN      10
11   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0      30
12   7876   ADAMS      CLERK  7788.0  1987-05-23  1100.0     NaN      20
13   7900   JAMES      CLERK  7698.0  1981-12-03   950.0     NaN      30
14   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0     NaN      20
15   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0     NaN      10

In [8]:
emp = q('select * from emp')
emp.head()

   empno   ename       job     mgr    hiredate     sal   comm  deptno
0   1234  DHIRAJ   ANALYST  7839.0  1988-12-17  5000.0  100.0      10
1   1324    SHAN   ANALYST  7839.0  1988-12-17  4000.0   50.0      10
2   7369   SMITH     CLERK  7902.0  1980-12-17   800.0    NaN      20
3   7499   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0  300.0      30
4   7521    WARD  SALESMAN  7698.0  1981-02-22  1250.0  500.0      30

In [9]:
dept = q('select * from dept')
dept.head()

   deptno       dname       loc
0      10  ACCOUNTING  NEW YORK
1      20    RESEARCH    DALLAS
2      30       SALES   CHICAGO
3      40  OPERATIONS    BOSTON

In [10]:
empdept= pd.merge(emp, dept, on='deptno', how='inner')
empdept

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,1234,DHIRAJ,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,ACCOUNTING,NEW YORK
1,1324,SHAN,ANALYST,7839.0,1988-12-17,4000.0,50.0,10,ACCOUNTING,NEW YORK
2,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS
3,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO
4,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO
5,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,NaN,20,RESEARCH,DALLAS
6,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30,SALES,CHICAGO
7,7698,BLAKE,MANAGER,7839.0,1981-05-01,2850.0,NaN,30,SALES,CHICAGO
8,7782,CLARK,MANAGER,7839.0,1981-06-09,2450.0,NaN,10,ACCOUNTING,NEW YORK
9,7788,SCOTT,ANALYST,7566.0,1987-04-19,3000.0,NaN,20,RESEARCH,DALLAS
10,7839,KING,PRESIDENT,NaN,1981-11-17,5000.0,NaN,10,ACCOUNTING,NEW YORK
11,7844,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30,SALES,CHICAGO
12,7876,ADAMS,CLERK,7788.0,1987-05-23,1100.0,NaN,20,RESEARCH,DALLAS
13,7900,JAMES,CLERK,7698.0,1981-12-03,950.0,NaN,30,SALES,CHICAGO
14,7902,FORD,ANALYST,7566.0,1981-12-03,3000.0,NaN,20,RESEARCH,DALLAS
15,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,NaN,10,ACCOUNTING,NEW YORK

- Use size when you want to know the total number of items or rows, regardless of whether data is missing(NAN).
- Use count() when you need to know how many valid, non-missing data points exist in your dataset

In [11]:
empdept.groupby('dname').size()

dname
ACCOUNTING    5
RESEARCH      5
SALES         6
dtype: int64

In [12]:
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,1234,DHIRAJ,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,ACCOUNTING,NEW YORK
1,1324,SHAN,ANALYST,7839.0,1988-12-17,4000.0,50.0,10,ACCOUNTING,NEW YORK
2,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS
3,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO
4,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO

In [13]:
empdept.shape

(16, 10)

In [14]:
empdept.dtypes

empno         int64
ename           str
job             str
mgr         float64
hiredate     object
sal         float64
comm        float64
deptno        int64
dname           str
loc             str
dtype: object

In [15]:
empdept.info()

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   empno     16 non-null     int64
 1   ename     16 non-null     str
 2   job       16 non-null     str
 3   mgr       15 non-null     float64
 4   hiredate  16 non-null     object
 5   sal       16 non-null     float64
 6   comm      6 non-null      float64
 7   deptno    16 non-null     int64
 8   dname     16 non-null     str
 9   loc       16 non-null     str
dtypes: float64(3), int64(2), object(1), str(4)
memory usage: 1.8+ KB

In [16]:
empdept.describe()

             empno          mgr          sal         comm     deptno
count    16.000000    15.000000    16.000000     6.000000  16.000000
mean   6920.625000  7752.600000  2376.562500   391.666667  20.625000
std    2208.572175   102.227897  1390.068006   527.652032   8.539126
min    1234.000000  7566.000000   800.000000     0.000000  10.000000
25%    7515.500000  7698.000000  1250.000000    62.500000  10.000000
50%    7740.000000  7782.000000  2025.000000   200.000000  20.000000
75%    7852.000000  7839.000000  3000.000000   450.000000  30.000000
max    7934.000000  7902.000000  5000.000000  1400.000000  30.000000

In [17]:
empdept.dtypes

empno         int64
ename           str
job             str
mgr         float64
hiredate     object
sal         float64
comm        float64
deptno        int64
dname           str
loc             str
dtype: object

In [18]:
empdept.isnull().sum()

empno        0
ename        0
job          0
mgr          1
hiredate     0
sal          0
comm        10
deptno       0
dname        0
loc          0
dtype: int64

In [19]:
#Using empdept['comm'].fillna(0, inplace=True) often fails to update the original DataFrame due to chained assignment, where pandas returns a copy of the column rather 
#than a view, causing the inplace update to be lost.
#empdept['comm'].fillna(0, inplace=True)# inplace discouraged in later versions.
empdept['comm'] = empdept['comm'].fillna(0)

In [20]:
empdept['comm'].isna().sum()

np.int64(0)

In [21]:
# Salary analysis
empdept['sal'].mean()

np.float64(2376.5625)

In [22]:
empdept['sal'].min()

800.0

In [23]:
empdept['sal'].sum()

np.float64(38025.0)

In [24]:
empdept['sal'].max()

5000.0

In [25]:
empdept['sal'].median()

2025.0

In [26]:
empdept['sal'].std()

1390.0680064299013

In [27]:
empdept.groupby('job')['sal'].mean()
#SQL equivalent
#SELECT job, AVG(sal) AS mean_sal FROM empdept GROUP BY job;

job
ANALYST      3750.000000
CLERK        1037.500000
MANAGER      2758.333333
PRESIDENT    5000.000000
SALESMAN     1400.000000
Name: sal, dtype: float64

In [28]:
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,1234,DHIRAJ,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,ACCOUNTING,NEW YORK
1,1324,SHAN,ANALYST,7839.0,1988-12-17,4000.0,50.0,10,ACCOUNTING,NEW YORK
2,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,0.0,20,RESEARCH,DALLAS
3,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO
4,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO

In [29]:
empdept.groupby('dname')['sal'].mean()

dname
ACCOUNTING    3550.000000
RESEARCH      2175.000000
SALES         1566.666667
Name: sal, dtype: float64

In [30]:
#filtering location
empdept.groupby('loc').size()

loc
CHICAGO     6
DALLAS      5
NEW YORK    5
dtype: int64

In [31]:
empdept.groupby('dname')['sal'].agg(['mean','max','count'])
# SQL Equivalent
# SELECT dname, AVG(sal) AS mean_sal, MAX(sal) AS max_sal, COUNT(sal) AS count_sal FROM empdept GROUP BY dname;

                   mean     max  count
dname
ACCOUNTING  3550.000000  5000.0      5
RESEARCH    2175.000000  3000.0      5
SALES       1566.666667  2850.0      6

In [32]:
empdept['hiredate'] = pd.to_datetime(empdept['hiredate'])
filtered = empdept[empdept['hiredate'] > '1980-12-31']
filtered

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,1234,DHIRAJ,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,ACCOUNTING,NEW YORK
1,1324,SHAN,ANALYST,7839.0,1988-12-17,4000.0,50.0,10,ACCOUNTING,NEW YORK
3,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO
4,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO
5,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,0.0,20,RESEARCH,DALLAS
6,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30,SALES,CHICAGO
7,7698,BLAKE,MANAGER,7839.0,1981-05-01,2850.0,0.0,30,SALES,CHICAGO
8,7782,CLARK,MANAGER,7839.0,1981-06-09,2450.0,0.0,10,ACCOUNTING,NEW YORK
9,7788,SCOTT,ANALYST,7566.0,1987-04-19,3000.0,0.0,20,RESEARCH,DALLAS
10,7839,KING,PRESIDENT,NaN,1981-11-17,5000.0,0.0,10,ACCOUNTING,NEW YORK
11,7844,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30,SALES,CHICAGO
12,7876,ADAMS,CLERK,7788.0,1987-05-23,1100.0,0.0,20,RESEARCH,DALLAS
13,7900,JAMES,CLERK,7698.0,1981-12-03,950.0,0.0,30,SALES,CHICAGO
14,7902,FORD,ANALYST,7566.0,1981-12-03,3000.0,0.0,20,RESEARCH,DALLAS
15,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,0.0,10,ACCOUNTING,NEW YORK

In [33]:
filtered.groupby(filtered['hiredate'].dt.year).size()

hiredate
1981    10
1982     1
1987     2
1988     2
dtype: int64

In [34]:
filtered.groupby(filtered['hiredate'].dt.year)['sal'].mean()
#Eqivalent SQL
#SELECT EXTRACT(YEAR FROM hiredate) AS hire_year, AVG(sal) AS mean_sal FROM filtered GROUP BY EXTRACT(YEAR FROM hiredate);

hiredate
1981    2282.5
1982    1300.0
1987    2050.0
1988    4500.0
Name: sal, dtype: float64

In [35]:
empdept.groupby('ename')['sal'].agg(['mean','max','count'])
# SQL
# SELECT ename, AVG(sal) AS mean_sal, MAX(sal) AS max_sal, COUNT(sal) AS count_sal FROM empdept GROUP BY ename;

          mean     max  count
ename
ADAMS   1100.0  1100.0      1
ALLEN   1600.0  1600.0      1
BLAKE   2850.0  2850.0      1
CLARK   2450.0  2450.0      1
DHIRAJ  5000.0  5000.0      1
FORD    3000.0  3000.0      1
JAMES    950.0   950.0      1
JONES   2975.0  2975.0      1
KING    5000.0  5000.0      1
MARTIN  1250.0  1250.0      1
MILLER  1300.0  1300.0      1
SCOTT   3000.0  3000.0      1
SHAN    4000.0  4000.0      1
SMITH    800.0   800.0      1
TURNER  1500.0  1500.0      1
WARD    1250.0  1250.0      1

In [36]:
empdept.groupby('dname').size()
# SQL
# SELECT dname, COUNT(*) AS size FROM empdept GROUP BY dname;

dname
ACCOUNTING    5
RESEARCH      5
SALES         6
dtype: int64

In [37]:
empdept.groupby('dname').count()

            empno  ename  job  mgr  hiredate  sal  comm  deptno  loc
dname
ACCOUNTING      5      5    5    4         5    5     5       5    5
RESEARCH        5      5    5    5         5    5     5       5    5
SALES           6      6    6    6         6    6     6       6    6

In [38]:
# Total compensation sal+comm
#empdept['total_comp'] = empdept['sal'] + empdept['comm'] # it is working fine but problematic for NAN values
empdept['total_comp'] = empdept['sal'].add(empdept['comm'], fill_value=0) # Best for skipping NaN implicitly
empdept[['ename','sal','comm','total_comp']].sort_values('total_comp', ascending=False)
# SQL
#SELECT ename, sal, comm, (sal + COALESCE(comm, 0)) AS total_comp FROM empdept ORDER BY total_comp DESC;

     ename     sal    comm  total_comp
0   DHIRAJ  5000.0   100.0      5100.0
10    KING  5000.0     0.0      5000.0
1     SHAN  4000.0    50.0      4050.0
9    SCOTT  3000.0     0.0      3000.0
14    FORD  3000.0     0.0      3000.0
5    JONES  2975.0     0.0      2975.0
7    BLAKE  2850.0     0.0      2850.0
6   MARTIN  1250.0  1400.0      2650.0
8    CLARK  2450.0     0.0      2450.0
3    ALLEN  1600.0   300.0      1900.0
4     WARD  1250.0   500.0      1750.0
11  TURNER  1500.0     0.0      1500.0
15  MILLER  1300.0     0.0      1300.0
12   ADAMS  1100.0     0.0      1100.0
13   JAMES   950.0     0.0       950.0
2    SMITH   800.0     0.0       800.0

In [39]:
# Sequencing order number
result = empdept[['ename','sal','comm','total_comp']]\
         .sort_values('total_comp', ascending=False)\
         .reset_index(drop=True)
result.index += 1  # start from 1 instead of 0
result

     ename     sal    comm  total_comp
1   DHIRAJ  5000.0   100.0      5100.0
2     KING  5000.0     0.0      5000.0
3     SHAN  4000.0    50.0      4050.0
4    SCOTT  3000.0     0.0      3000.0
5     FORD  3000.0     0.0      3000.0
6    JONES  2975.0     0.0      2975.0
7    BLAKE  2850.0     0.0      2850.0
8   MARTIN  1250.0  1400.0      2650.0
9    CLARK  2450.0     0.0      2450.0
10   ALLEN  1600.0   300.0      1900.0
11    WARD  1250.0   500.0      1750.0
12  TURNER  1500.0     0.0      1500.0
13  MILLER  1300.0     0.0      1300.0
14   ADAMS  1100.0     0.0      1100.0
15   JAMES   950.0     0.0       950.0
16   SMITH   800.0     0.0       800.0

In [40]:
#Pandas Equivalent
result = empdept[['ename', 'sal', 'comm', 'total_comp']].sort_values('total_comp', ascending=False).reset_index(drop=True).rename(lambda x: x + 1)
result
# .rename() method in Pandas targets the index labels (the rows) when you pass a function or a dictionary without specifying an axis

# SQl equivalent
# SELECT ROW_NUMBER() OVER (ORDER BY (e.sal + COALESCE(e.comm, 0)) DESC) AS "index", e.ename, e.sal, e.comm, (e.sal + COALESCE(e.comm, 0)) AS total_comp FROM emp e JOIN 
# dept d ON e.deptno = d.deptno ORDER BY total_comp DESC;

     ename     sal    comm  total_comp
1   DHIRAJ  5000.0   100.0      5100.0
2     KING  5000.0     0.0      5000.0
3     SHAN  4000.0    50.0      4050.0
4    SCOTT  3000.0     0.0      3000.0
5     FORD  3000.0     0.0      3000.0
6    JONES  2975.0     0.0      2975.0
7    BLAKE  2850.0     0.0      2850.0
8   MARTIN  1250.0  1400.0      2650.0
9    CLARK  2450.0     0.0      2450.0
10   ALLEN  1600.0   300.0      1900.0
11    WARD  1250.0   500.0      1750.0
12  TURNER  1500.0     0.0      1500.0
13  MILLER  1300.0     0.0      1300.0
14   ADAMS  1100.0     0.0      1100.0
15   JAMES   950.0     0.0       950.0
16   SMITH   800.0     0.0       800.0

In [41]:
empdept[empdept['hiredate'] > '1981-01-01']

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc,total_comp
0,1234,DHIRAJ,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,ACCOUNTING,NEW YORK,5100.0
1,1324,SHAN,ANALYST,7839.0,1988-12-17,4000.0,50.0,10,ACCOUNTING,NEW YORK,4050.0
3,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO,1900.0
4,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO,1750.0
5,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,0.0,20,RESEARCH,DALLAS,2975.0
6,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30,SALES,CHICAGO,2650.0
7,7698,BLAKE,MANAGER,7839.0,1981-05-01,2850.0,0.0,30,SALES,CHICAGO,2850.0
8,7782,CLARK,MANAGER,7839.0,1981-06-09,2450.0,0.0,10,ACCOUNTING,NEW YORK,2450.0
9,7788,SCOTT,ANALYST,7566.0,1987-04-19,3000.0,0.0,20,RESEARCH,DALLAS,3000.0
10,7839,KING,PRESIDENT,NaN,1981-11-17,5000.0,0.0,10,ACCOUNTING,NEW YORK,5000.0
11,7844,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30,SALES,CHICAGO,1500.0
12,7876,ADAMS,CLERK,7788.0,1987-05-23,1100.0,0.0,20,RESEARCH,DALLAS,1100.0
13,7900,JAMES,CLERK,7698.0,1981-12-03,950.0,0.0,30,SALES,CHICAGO,950.0
14,7902,FORD,ANALYST,7566.0,1981-12-03,3000.0,0.0,20,RESEARCH,DALLAS,3000.0
15,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,0.0,10,ACCOUNTING,NEW YORK,1300.0

In [42]:
empdept[empdept['hiredate'] > '1981-01-01'].sort_values('hiredate')

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc,total_comp
3,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO,1900.0
4,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO,1750.0
5,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,0.0,20,RESEARCH,DALLAS,2975.0
7,7698,BLAKE,MANAGER,7839.0,1981-05-01,2850.0,0.0,30,SALES,CHICAGO,2850.0
8,7782,CLARK,MANAGER,7839.0,1981-06-09,2450.0,0.0,10,ACCOUNTING,NEW YORK,2450.0
11,7844,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30,SALES,CHICAGO,1500.0
6,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30,SALES,CHICAGO,2650.0
10,7839,KING,PRESIDENT,NaN,1981-11-17,5000.0,0.0,10,ACCOUNTING,NEW YORK,5000.0
13,7900,JAMES,CLERK,7698.0,1981-12-03,950.0,0.0,30,SALES,CHICAGO,950.0
14,7902,FORD,ANALYST,7566.0,1981-12-03,3000.0,0.0,20,RESEARCH,DALLAS,3000.0
15,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,0.0,10,ACCOUNTING,NEW YORK,1300.0
9,7788,SCOTT,ANALYST,7566.0,1987-04-19,3000.0,0.0,20,RESEARCH,DALLAS,3000.0
12,7876,ADAMS,CLERK,7788.0,1987-05-23,1100.0,0.0,20,RESEARCH,DALLAS,1100.0
0,1234,DHIRAJ,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,ACCOUNTING,NEW YORK,5100.0
1,1324,SHAN,ANALYST,7839.0,1988-12-17,4000.0,50.0,10,ACCOUNTING,NEW YORK,4050.0