In [ ]:
# Pandas SQL

In [ ]:
#pip install pandasql

In [ ]:
import pandas as pd
from pandasql import sqldf
import os

In [ ]:
projectFolder ='/Users/du/dup/analytics/projects/piit/data/'
os.listdir(projectFolder)

In [ ]:
file_path = projectFolder + "sqlpractise1.xlsx"
employees_df = pd.read_excel(file_path, sheet_name="Employees")
departments_df = pd.read_excel(file_path, sheet_name="Departments")

In [4]:
employees_df

   emp_id first_name last_name  dept_id  salary  is_active
0       1      Alice     Smith      101   50000          1
1       2        Bob     Jones      102   60000          1
2       3    Charlie     Brown      101   55000          0
3       4      David    Wilson      103   70000          1
4       5        Eva    Taylor      102   65000          1

In [5]:
departments_df

   dept_id    dept_name  manager_id
0      101           HR           1
1      102  Engineering           2
2      103    Marketing           4

In [6]:
# Define SQL query function
pysqldf = lambda q: sqldf(q, globals())

## Select All Employees

In [7]:
pysqldf("SELECT * FROM employees_df;")

   emp_id first_name last_name  dept_id  salary  is_active
0       1      Alice     Smith      101   50000          1
1       2        Bob     Jones      102   60000          1
2       3    Charlie     Brown      101   55000          0
3       4      David    Wilson      103   70000          1
4       5        Eva    Taylor      102   65000          1

## Employees with salary > 55000

In [ ]:
pysqldf("SELECT * FROM employees_df WHERE salary > 55000;")

## Join Employees and Departments

In [ ]:
pysqldf("""
    SELECT e.first_name, e.last_name, d.dept_name
    FROM employees_df e
    JOIN departments_df d ON e.dept_id = d.dept_id;
""")

## Count Employees Per Department

In [ ]:
pysqldf("""
    SELECT d.dept_name, COUNT(e.emp_id) AS employee_count
    FROM employees_df e
    JOIN departments_df d ON e.dept_id = d.dept_id
    GROUP BY d.dept_name;
""")

## Inactive Employees

In [ ]:
pysqldf("SELECT * FROM employees_df WHERE is_active = 0;")

# DML Commands 
- limited features in pandasql

## Part-2

In [8]:
import pandas as pd
from pandasql import sqldf

In [9]:
# sample data
df = pd.DataFrame({ "branch": ["CSE", "CSE", "ECE"],  "score": [80, 90, 70]})
df

  branch  score
0    CSE     80
1    CSE     90
2    ECE     70

In [11]:
# function
pysqldf = lambda q: sqldf(q, globals())
pysqldf

In [12]:
# run SQL
result = pysqldf(""" SELECT branch, AVG(score) as avg_score FROM df GROUP BY branch """)
print(result)

  branch  avg_score
0    CSE       85.0
1    ECE       70.0

## SQL Lite - more control , production ready

In [13]:
import pandas as pd
import sqlite3

In [14]:
# sample data
df = pd.DataFrame({ "branch": ["CSE", "CSE", "ECE"],  "score": [80, 90, 70]})
df

  branch  score
0    CSE     80
1    CSE     90
2    ECE     70

In [16]:
# create in-memory database
conn = sqlite3.connect(":memory:")
conn

In [17]:
# load dataframe into SQL table
df.to_sql("students", conn, index=False)

3

In [18]:
# run SQL query
query = """ SELECT branch, AVG(score) as avg_score FROM students GROUP BY branch """
result = pd.read_sql(query, conn)
print(result)

  branch  avg_score
0    CSE       85.0
1    ECE       70.0

## Part-3 DuckDB

In [21]:
import duckdb
import pandas as pd

In [22]:
# sample data
df = pd.DataFrame({ "branch": ["CSE", "CSE", "ECE"],  "score": [80, 90, 70]})
df

  branch  score
0    CSE     80
1    CSE     90
2    ECE     70

In [24]:
result = duckdb.query(""" SELECT branch, AVG(score) as avg_score FROM df GROUP BY branch """).to_df()
result

  branch  avg_score
0    CSE       85.0
1    ECE       70.0

## which one to use 
- Tool   :     Best for
- pandasql :   Learning / quick queries
- SQLite   :   Structured workflows
- DuckDB   :   Large data + performance