# Pandas Data - Strings Manipulation

1. In Regex: "One or More"

In a regex pattern (like r"\d+"), + is a quantifier. It tells the engine to match the preceding character 1 or more times.

\d+: Matches one digit, or a whole string of digits (e.g., "5", "55", or "555").
\w+: Matches one or more word characters (useful for grabbing whole words).
a+: Matches "a", "aa", "aaa", but not an empty string.

Comparison:
\d: Matches exactly one digit (e.g., "1").
\d+: Matches the entire number (e.g., "123").

2. In Python: Concatenation
When working with strings in your code (like your pattern example), + is used to glue strings together.
Example: '^(' + 'Man|Aman' + ')'
Result: '^(Man|Aman)'

In [3]:
import pandas as pd
import re

# Tasks

In [4]:
# Create a small sample DataFrame
data = {
    'StudentID': [1, 2, 3, 4, 5, 6],
    'Name': ['Mandal A Kumar', 'Suroor Ahmed', 'Amandeep Kaur', 'Nayeema', 'Muhammad H Kabeer', 'Bijata Marjan'],
    'Score': [85, 92, 78, 88, 91, 84]
}

df = pd.DataFrame(data)

In [5]:
df

   StudentID               Name  Score
0          1     Mandal A Kumar     85
1          2       Suroor Ahmed     92
2          3      Amandeep Kaur     78
3          4            Nayeema     88
4          5  Muhammad H Kabeer     91
5          6      Bijata Marjan     84

In [6]:
# Search for 'john' in Name column (case-insensitive)
search_term = 'Nayeema'
matches = df[df['Name'].str.contains(search_term, case=False, na=False)]

# na= False, Tells pandas how to handle missing values (NaN).
#If False: Treats a missing value as "Not Found" (returns False).
#If True: Treats a missing value as "Found" (returns True).
# If omitted: Returns NaN for that row, which can break filters.
matches

   StudentID     Name  Score
3          4  Nayeema     88

In [7]:
df[df['Name'].str.startswith('M')]

   StudentID               Name  Score
0          1     Mandal A Kumar     85
4          5  Muhammad H Kabeer     91

In [8]:
startChar = ('M','A')  #tuple
df[df['Name'].str.startswith(startChar)]

   StudentID               Name  Score
0          1     Mandal A Kumar     85
2          3      Amandeep Kaur     78
4          5  Muhammad H Kabeer     91

In [9]:
df[df['Name'].str.contains(r'^(Man|Aman)', case=False, na=False)]

C:\Users\Jewel\AppData\Local\Temp\ipykernel_13896\3667526613.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[df['Name'].str.contains(r'^(Man|Aman)', case=False, na=False)]

   StudentID            Name  Score
0          1  Mandal A Kumar     85
2          3   Amandeep Kaur     78

In [10]:
words = ['Mu', 'Nay', 'Sur']
pattern = '^(' + '|'.join(words) + ')'
df[df['Name'].str.contains(pattern, case=False, na=False)]

C:\Users\Jewel\AppData\Local\Temp\ipykernel_13896\1767152750.py:3: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[df['Name'].str.contains(pattern, case=False, na=False)]

   StudentID               Name  Score
1          2       Suroor Ahmed     92
3          4            Nayeema     88
4          5  Muhammad H Kabeer     91

This line of code dynamically builds a regex string to search for any word from a list at the very beginning of a string.
It’s much more efficient than writing out a long regex by hand, especially if your list of words changes.

The Breakdown:

words: This is your list of target words (e.g., ['Man', 'Aman', 'Merc']).
'|'.join(words):
This takes the list and joins the items with a pipe (|) symbol.
In regex, | means OR.
Result: "Man|Aman|Merc"

'^(' + ... + ')':
^: The "Caret" anchor. It forces the match to happen at the start of the text.
(): "Parentheses" create a Capture Group. This keeps the "OR" logic contained so the ^ applies to everything inside.
Final Result: "^(Man|Aman|Merc)"

In the line pattern = '^(' + '|'.join(words) + ')', the + is used for String Concatenation. It glues separate pieces of text together to create one long string that 
Python can use as a regex rule.

Here is the step-by-step mechanical breakdown:

The "Glue" Logic:
Since this is regular Python code (not inside the regex engine yet), the + works like a physical link between three distinct parts:
Part A: '^(' — A literal string telling regex to "start at the beginning and open a group."
Part B: '|'.join(words) — A dynamic string created by putting pipes between your list items.
Part C: ')' — A literal string to "close the group."

A Visual Example

Imagine words = ['Man', 'Aman']. Here is how the + assembles the final pattern:
'^(' + 'Man|Aman' + ')'
Result: '^(Man|Aman)'

In [11]:
starts = tuple(words)
df[df['Name'].str.startswith(starts)]  #no warning

   StudentID               Name  Score
1          2       Suroor Ahmed     92
3          4            Nayeema     88
4          5  Muhammad H Kabeer     91

In [12]:
df

   StudentID               Name  Score
0          1     Mandal A Kumar     85
1          2       Suroor Ahmed     92
2          3      Amandeep Kaur     78
3          4            Nayeema     88
4          5  Muhammad H Kabeer     91
5          6      Bijata Marjan     84

In [13]:
# This code uses a lambda function to perform a "search and replace" operation on every single row in the 'Name' column using the re (regular expression) library.
df['Name'].apply(lambda x: re.sub(r'Suroor', 'Surur', x))

0       Mandal A Kumar
1          Surur Ahmed
2        Amandeep Kaur
3              Nayeema
4    Muhammad H Kabeer
5        Bijata Marjan
Name: Name, dtype: object

## Find & Replace Strings

In [12]:
import pandas as pd; import re

In [13]:
df = pd.DataFrame({'text_column': ['apple pie', 'banana bread', 'cherry tart']})
df

    text_column
0     apple pie
1  banana bread
2   cherry tart

In [14]:
# Find all occurrences of a pattern
df['found_matches'] = df['text_column'].apply(lambda x: re.findall(r'\b\w+a\w+\b', x))
df

    text_column    found_matches
0     apple pie               []
1  banana bread  [banana, bread]
2   cherry tart           [tart]

The regex engine only needs to find one "a" that fits the rule to return True.

The Regex Pattern: r'\b\w+a\w+\b'
\b (Word Boundary): Ensures the match starts and ends at the edge of a word (so it doesn't grab parts of words).
\w+: Matches one or more letters, numbers, or underscores.
a: Matches the literal letter "a".
\w+: Matches one or more letters after the "a".
\b: Closes the word boundary.

Note: This pattern will fail on words where "a" is the first letter (e.g., "apple") or the last letter (e.g., "data"), unless there is another "a" in the middle of that same word.
The Logic: Because there are \w+ tokens on both sides of the "a", this pattern only matches words where "a" is not the first or last letter.

The \b at the start and end ensures you are looking at the whole word, not just a piece of a longer word.

\b: "Start at the beginning of a word.......................only the begining not part of calculation
"\w+a\w+: "...find an 'a' with letters on both sides........part of the calculatiomn
"\b: "...and stop exactly when the word ends."..............only the end point not part of calculation

Examples of Matches
Word	   Match?	Reason
"Mazda"	   ✅ Yes	M+a+.
"Apple"	   ❌ No	 Starts with "a" (needs a letter before "a").
"Fast"	   ✅ Yes	"a" is surrounded by letters.
"Standard"	✅ Yes	"a" is in the middle. standard+a+rd
"Standarda"	✅ Yes	"a" is in the middle. standard+a+rda
"Standardaa"✅ Yes	"a" is in the middle. standard+a+rdaa

In [16]:
# Replace a pattern
df['replaced_text'] = df['text_column'].apply(lambda x: re.sub(r'apple', 'orange', x))

In [17]:
df

    text_column    found_matches replaced_text
0     apple pie               []    orange pie
1  banana bread  [banana, bread]  banana bread
2   cherry tart           [tart]   cherry tart

In [19]:
df['text_column'] = df['text_column'].apply(lambda x: re.sub(r'apple', 'orange', x))
df

    text_column    found_matches replaced_text
0    orange pie               []    orange pie
1  banana bread  [banana, bread]  banana bread
2   cherry tart           [tart]   cherry tart