# Strings in Python
- a sequence of characters used to represent text
- immutatable
    - name = 'Dhiraj'   -> 'DHraj'
-

In [1]:
string1 = 'Dhiraj'
print(string1)

Dhiraj

In [2]:
print(string1[0])
#string1[0]='N'
string1 ='Upadhyaya'
print(string1)

D
Upadhyaya

In [3]:
# -------------------------------
# 1. Creating Strings
# -------------------------------
print("1. Creating Strings")
s1 = "Hello"  #double quote
s2 = 'World'  #single quote
s3 = """This is a multiline 
       String"""  #triple quote (single or double)
print(s1)
print(s2)
print(s3)

1. Creating Strings
Hello
World
This is a multiline
       String

In [4]:
ms = '''In Python, a string is a sequence of characters used to represent text 
GeeksforGeeks
GeeksforGeeks
 +1
. Strings are one of the most fundamental and frequently used data types in the language'''
print(ms)
print(len(ms))

In Python, a string is a sequence of characters used to represent text
GeeksforGeeks
GeeksforGeeks
 +1
. Strings are one of the most fundamental and frequently used data types in the language
192

In [5]:
# -------------------------------
# 2. String Concatenation
# -------------------------------
print("\n2. Concatenation")
full = s1 + " " + s2
print("Concatenated:",full) 
# The space appears after "Concatenated" because Python's print() function automatically adds a space between arguments separated by a comma.

2. Concatenation
Concatenated: Hello World Hello

In [7]:
sc ='Aelita' + '....' + "Khulan"
print(sc)

Aelita....Khulan

In [8]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.

In [9]:
# -------------------------------
# 3. String Repetition
# -------------------------------
print("\t\t3. Repetition")
repeat = "Hi. How are you! " * 5
print(repeat, end=': I have reached end of string')

		3. Repetition
Hi. How are you! Hi. How are you! Hi. How are you! Hi. How are you! Hi. How are you! : I have reached end of string

- In Python, \n stands for the newline character 
- It is an escape sequence used to insert a line break within a string

In [10]:
# -------------------------------
# 4. Indexing (Access characters)
# -------------------------------
print('\n')
print("4. Indexing")
text = "PythonA"
print(' The string is ', text)
print("First character:", text[0])
print("Last character:", text[-1])
print("3rd character:", text[2])

4. Indexing
 The string is  PythonA
First character: P
Last character: A
3rd character: t

In [11]:
round(len(text)/2)

4

In [12]:
#!pip install pywho
import pywho
pywho

In [13]:
text[::-1]

'AnohtyP'

In [14]:
print('Actual String ', text, ' Reverse String is ', text[3::-1])

Actual String  PythonA  Reverse String is  htyP

In [15]:
print('Actual String ', text, ' Reverse String is ', text[3:2:-1])

Actual String  PythonA  Reverse String is  h

In [16]:
print('Actual String ', text, ' Reverse String is ', text[::-1])

Actual String  PythonA  Reverse String is  AnohtyP

In [17]:
print('Actual String ', text, "Middle character:", text[round(len(text)/2)-1])

Actual String  PythonA Middle character: h

In [20]:
# -------------------------------
# 5. Slicing (Get part of string)
# string[start:stop:step]
# -------------------------------
print("5. Slicing\n")
print("First 3 chars:", text[0:3])
print("From index 2:", text[2:])
print("Reverse string:", text[::-1])
print("All but last letter:", text[:-1])
print("last letter:", text[-1])

5. Slicing

First 3 chars: Pyt
From index 2: thonA
Reverse string: AnohtyP
All but last letter: Python
last letter: A

In [21]:
# -------------------------------
#  6. Strings
# -------------------------------
print("\nString Methods")
name = "  dAta science 1syed hasan - "
print("Original String with spaces - ", name)
print("Upper:", name.upper())
print("Lower:", name.lower())
print("Strip spaces:", name.strip())
#print("Capital case :" , name.capitalize()) # because d is not the first letter in name, ' 'space is
print("title case :" , name.title())
print("Replace:", name.replace("science", "analysis"))

String Methods
Original String with spaces -    dAta science 1syed hasan -
Upper:   DATA SCIENCE 1SYED HASAN -
Lower:   data science 1syed hasan -
Strip spaces: dAta science 1syed hasan -
title case :   Data Science 1Syed Hasan -
Replace:   dAta analysis 1syed hasan -

In [22]:
# -------------------------------
# 7. Checking Content
# -------------------------------
print("\n7. Checking Content")
sample = "Python123"
print("Is alphabet:", sample.isalpha())
print("Is digit:", sample.isdigit())
print("Is alphanumeric:", sample.isalnum())

7. Checking Content
Is alphabet: False
Is digit: False
Is alphanumeric: True

In [20]:
# -------------------------------
# 8. Splitting and Joining
# -------------------------------
print("\n8. Split & Join")
sentence = "Python is easy to learn"
print(' the Sentence is ', sentence)
words = sentence.split(" ")
print("Split:", words)
joined = "-".join(words)
print("Joined:", joined)

8. Split & Join
 the Sentence is  Python is easy to learn
Split: ['Python', 'is', 'easy', 'to', 'learn']
Joined: Python-is-easy-to-learn

In [23]:
# -------------------------------
# 9. String Formatting
# -------------------------------
print("\n9. Formatting")
name = "Taheera"
age = 25
gender ='female'
city ='New York'
# Old style
print("My name is %s and I am %d years old, and my gender is %s and I live in %s" % (name, age,gender,city))
# format()
print("My name is {} and I am {} years old with gender {} and lives in city of {}".format(name, age, gender, city))
# f-string (recommended)
print(f"My name is {name}, I am a {age} years old {gender}, lives in {city} ")

9. Formatting
My name is Taheera and I am 25 years old, and my gender is female and I live in New York
My name is Taheera and I am 25 years old with gender female and lives in city of New York
My name is Taheera, I am a 25 years old female, lives in New York

In [24]:
# 11. Important Concept: Strings are Immutable
# -------------------------------
print("\n11. Immutability")
text = "hello"
# text[0] = 'H'  # ❌ This will give an error
# Correct way:
text = "H" + text[1:]
print("Modified string:", text)
print("He said \"Python is fun\"")  #double quotes

11. Immutability
Modified string: Hello
He said "Python is fun"

In [25]:
#text[0] = 'H'

In [26]:
# -------------------------------
# 12. Length of String
# -------------------------------
text = 'Python'
print("\n12. Length")
print(f"Length of {text}: {len(text)}" )

12. Length
Length of Python: 6

In [30]:
# -------------------------------
# 13. Membership (in keyword)
# -------------------------------
print("\n13. Membership")
print("py" in "Python")
print("th" in "Python")
print("n" in "Python")
print("Java" in "Python")
print("Java" not in "Python")

13. Membership
False
True
True
False
True

## More

In [31]:
import pandas as pd
from pydataset import data

In [36]:
# Create mtcars dataset with car names
data = {
    "car_name": [ "Mazda RX4", "Mazda RX4    Wag", "Datsun 710","Hornet 4 Drive", "Hornet   Sportabout  ", "Valiant", "Duster 360", "merc 240D", "Merc 230", "Merc 280" ],
    "mpg": [21.0, 21.0, 22.8, 21.4, 18.7, 18.1, 14.3, 24.4, 22.8, 19.2]}
df = pd.DataFrame(data)
print("Original Data:\n", df)

Original Data:
                 car_name   mpg
0              Mazda RX4  21.0
1       Mazda RX4    Wag  21.0
2             Datsun 710  22.8
3         Hornet 4 Drive  21.4
4  Hornet   Sportabout    18.7
5                Valiant  18.1
6             Duster 360  14.3
7              merc 240D  24.4
8               Merc 230  22.8
9               Merc 280  19.2

In [37]:
# Search 
mazda_cars = df[df['car_name'].str.contains("Mazda")]
print( "\nCars with 'Mazda':\n",mazda_cars)
# .str.contains() → pattern search
# Case sensitive by default

Cars with 'Mazda':
            car_name   mpg
0         Mazda RX4  21.0
1  Mazda RX4    Wag  21.0

In [38]:
df[df['car_name'].str.contains("Merc", case=True)]

   car_name   mpg
8  Merc 230  22.8
9  Merc 280  19.2

In [39]:
df[df['car_name'].str.contains("merc", case=False)]
# case insenstive

    car_name   mpg
7  merc 240D  24.4
8   Merc 230  22.8
9   Merc 280  19.2

In [40]:
# FILTER (Start / End patterns
# Cars starting with “Merc”
merc_cars = df[df['car_name'].str.startswith("Merc")]
print("\nCars starting with 'Merc':\n", merc_cars)

Cars starting with 'Merc':
    car_name   mpg
8  Merc 230  22.8
9  Merc 280  19.2

In [44]:
# df[df['car_name'].str.startswith(["Merc",'merc'])] 
df[df['car_name'].str.startswith(("Merc",'merc'))] # only tuple no list

    car_name   mpg
7  merc 240D  24.4
8   Merc 230  22.8
9   Merc 280  19.2

In [45]:
df[df['car_name'].str.endswith("Drive")]

         car_name   mpg
3  Hornet 4 Drive  21.4

In [47]:
# Replace Strings
df['car_name_updated'] = df['car_name'].str.replace("Merc", "Mercedes", regex=False)
print("\nUpdated Names:\n", df[['car_name', 'car_name_updated']])

Updated Names:
                 car_name       car_name_updated
0              Mazda RX4              Mazda RX4
1       Mazda RX4    Wag       Mazda RX4    Wag
2             Datsun 710             Datsun 710
3         Hornet 4 Drive         Hornet 4 Drive
4  Hornet   Sportabout    Hornet   Sportabout
5                Valiant                Valiant
6             Duster 360             Duster 360
7              merc 240D              merc 240D
8               Merc 230           Mercedes 230
9               Merc 280           Mercedes 280

##### Literal String vs. Regular ExpressionWithout regex=False (default or True): 
- With regex=False: Treats "Merc" as a literal string, not a regular expression (faster and safer if you don't need regex).
- with regex=True: The string "Merc" is treated as a pattern. If it was "Me.c", the dot . acts as a wildcard, potentially matching "Merc", "Me-c", "Meac", etc.
- With regex=False: The string "Merc" is treated as a rigid, literal sequence of characters. The computer looks specifically for 'M' followed by 'e' followed by 'r' followed by 'c'.

In [48]:
df['car_name'].str.replace("Merc", "Mercedes", case=False, regex=False)

0                Mazda RX4
1         Mazda RX4    Wag
2               Datsun 710
3           Hornet 4 Drive
4    Hornet   Sportabout
5                  Valiant
6               Duster 360
7            Mercedes 240D
8             Mercedes 230
9             Mercedes 280
Name: car_name, dtype: str

In [49]:
# Split /Breaks
df['brand'] = df['car_name'].str.split().str[0]
print("\nExtracted Brand:\n", df[['car_name', 'brand']])
#👉 Very useful for: * extracting categories, * feature engineering

Extracted Brand:
                 car_name    brand
0              Mazda RX4    Mazda
1       Mazda RX4    Wag    Mazda
2             Datsun 710   Datsun
3         Hornet 4 Drive   Hornet
4  Hornet   Sportabout     Hornet
5                Valiant  Valiant
6             Duster 360   Duster
7              merc 240D     merc
8               Merc 230     Merc
9               Merc 280     Merc

In [50]:
# Change Case
df['upper_name'] = df['car_name'].str.upper()
df['lower_name'] = df['car_name'].str.lower()
df

,car_name,mpg,car_name_updated,brand,upper_name,lower_name
0,Mazda RX4,21.0,Mazda RX4,Mazda,MAZDA RX4,mazda rx4
1,Mazda RX4 Wag,21.0,Mazda RX4 Wag,Mazda,MAZDA RX4 WAG,mazda rx4 wag
2,Datsun 710,22.8,Datsun 710,Datsun,DATSUN 710,datsun 710
3,Hornet 4 Drive,21.4,Hornet 4 Drive,Hornet,HORNET 4 DRIVE,hornet 4 drive
4,Hornet Sportabout,18.7,Hornet Sportabout,Hornet,HORNET SPORTABOUT,hornet sportabout
5,Valiant,18.1,Valiant,Valiant,VALIANT,valiant
6,Duster 360,14.3,Duster 360,Duster,DUSTER 360,duster 360
7,merc 240D,24.4,merc 240D,merc,MERC 240D,merc 240d
8,Merc 230,22.8,Mercedes 230,Merc,MERC 230,merc 230
9,Merc 280,19.2,Mercedes 280,Merc,MERC 280,merc 280

In [51]:
# Cleaning (trim spaces)
df['clean_name'] = df['car_name'].str.strip()
df

,car_name,mpg,car_name_updated,brand,upper_name,lower_name,clean_name
0,Mazda RX4,21.0,Mazda RX4,Mazda,MAZDA RX4,mazda rx4,Mazda RX4
1,Mazda RX4 Wag,21.0,Mazda RX4 Wag,Mazda,MAZDA RX4 WAG,mazda rx4 wag,Mazda RX4 Wag
2,Datsun 710,22.8,Datsun 710,Datsun,DATSUN 710,datsun 710,Datsun 710
3,Hornet 4 Drive,21.4,Hornet 4 Drive,Hornet,HORNET 4 DRIVE,hornet 4 drive,Hornet 4 Drive
4,Hornet Sportabout,18.7,Hornet Sportabout,Hornet,HORNET SPORTABOUT,hornet sportabout,Hornet Sportabout
5,Valiant,18.1,Valiant,Valiant,VALIANT,valiant,Valiant
6,Duster 360,14.3,Duster 360,Duster,DUSTER 360,duster 360,Duster 360
7,merc 240D,24.4,merc 240D,merc,MERC 240D,merc 240d,merc 240D
8,Merc 230,22.8,Mercedes 230,Merc,MERC 230,merc 230,Merc 230
9,Merc 280,19.2,Mercedes 280,Merc,MERC 280,merc 280,Merc 280

# Regular Expression re
- Regex = a way to describe patterns in text
- “How would you find all phone numbers in a paragraph?”
- “How would you find emails in a dataset?”

# Simple Patterns
- \d  : digit: 1,2,3,4 etc
- \w  : Word (letter\number) : A, 3
- .   :  any character : a, @ except newline. A single dot matches exactly one character position. Examples:  h.t matches hat, hot, h8t, and h t.
- ..  : matches any two characters.
- .*  : matches everything (zero or more of any character) until the end of the line.
- \.  : matches a literal dot. To find .com, use the regex \.com. Using .com without the backslash would accidentally match things like acom, 1com, or !com.
- ^   : Starts with: start of the string
- $   : ends with: end of string

Anchor Tokens
These don't match actual characters; they match positions in the string.
^ (Caret): Matches the Start
Ensures the pattern is at the very beginning of the text.
Example: ^Apple matches "Apple pie" but not "Green Apple".

$ (Dollar): Matches the End
Ensures the pattern is at the very end of the text.
Example: dog$ matches "My dog" but not "doggy".

Character Tokens
These match specific types of characters.
. (Dot): The Wildcard
Matches any single character (except a new line).
Example: h.t matches "hat", "hot", "h8t", h t,and "h!t".
h.t will not match h\nt. In most regex engines, the dot . matches any character except for a newline (\n). because The dot is designed to stay on a single line.

Pattern t: Matches "t".
Pattern .t: Matches any character followed by "t" (including ".t"). Example: at,it, t (a space followed by a 't'. It cannot match only 't'). .t not matches put(..t matches put)
Pattern \.t: Matches only the literal characters ".t". Example: file.txt, a.t, file.temp 
How it works:
. (Dot): Acts as a wildcard for exactly one character (letter, number, space, or symbol).
t: Matches the literal lowercase letter "t".

\d (Digit): The Number Matcher. Matches any single decimal digit (0-9).
\d\d or \d{2}matches "42" or "07".

\w (Word Character): The Alphanumeric Matcher
Matches letters (A-Z, a-z), numbers (0-9), and underscores (_).
Example: \w matches "A", "9", or "_", but not "%" or "!".

In [63]:
import re
text = "Car prices: 10000, 20000, 30000"
# Find all numbers
numbers = re.findall(r"\d+", text)
numbers_wo_plus = re.findall(r"\d", text) # \d+  → one or more digits. It reads regex like a sentence. It stops at comma(,) beause , is not dight.
print(numbers,'\n')
print(numbers_wo_plus)

['10000', '20000', '30000']

['1', '0', '0', '0', '0', '2', '0', '0', '0', '0', '3', '0', '0', '0', '0']

In [64]:
# extract numbers from car names
import re
cars = ["Mazda RX4", "Duster 360", "Merc 240D"]
for car in cars:
    nums = re.findall(r"\d+", car)
    print(car, "→", nums)

Mazda RX4 → ['4']
Duster 360 → ['360']
Merc 240D → ['240']

In [65]:
# only numbrers as a list
import re

cars = ["Mazda RX4", "Duster 360", "Merc 240D"]
all_numbers = [] # 1. Create an empty list outside the loop

for car in cars:
    nums = re.findall(r"\d+", car)
    all_numbers.append(nums) # 2. Append the found numbers to the list

print(all_numbers)

[['4'], ['360'], ['240']]

In [66]:
# extract cars with numbers
import re
cars = ["Mazda RX4", "Valiant", "Duster 360"]
filtered = [car for car in cars if re.search(r"\d", car)]
print(filtered)

['Mazda RX4', 'Duster 360']

#### Breaking it Down
- for car in cars: This loops through every item in your list (named cars).
- re.search(): This function looks anywhere in the string for a specific pattern.
- r"\d": This is the regex pattern. As you noted earlier, \d stands for single digit (0-9).
- if...: The car is only added to the new list if re.search finds a digit.

In [67]:
# In pandas, str.contains() uses the re (regular expression) engine unless you explicitly tell it not to.
df[df['car_name'].str.contains(r"\d")]

,car_name,mpg,car_name_updated,brand,upper_name,lower_name,clean_name
0,Mazda RX4,21.0,Mazda RX4,Mazda,MAZDA RX4,mazda rx4,Mazda RX4
1,Mazda RX4 Wag,21.0,Mazda RX4 Wag,Mazda,MAZDA RX4 WAG,mazda rx4 wag,Mazda RX4 Wag
2,Datsun 710,22.8,Datsun 710,Datsun,DATSUN 710,datsun 710,Datsun 710
3,Hornet 4 Drive,21.4,Hornet 4 Drive,Hornet,HORNET 4 DRIVE,hornet 4 drive,Hornet 4 Drive
6,Duster 360,14.3,Duster 360,Duster,DUSTER 360,duster 360,Duster 360
7,merc 240D,24.4,merc 240D,merc,MERC 240D,merc 240d,merc 240D
8,Merc 230,22.8,Mercedes 230,Merc,MERC 230,merc 230,Merc 230
9,Merc 280,19.2,Mercedes 280,Merc,MERC 280,merc 280,Merc 280

#### Pandas Integration: Methods like .str.contains(), .str.replace(), and .str.extract() are designed to accept regex strings directly.

You only need the explicit import if you are using functions directly from the regex library outside of pandas, such as:
- re.search()
- re.match()
- re.findall()

# Small exercises
- find all 3 digit numbers \d{3}
- find words starting with M : ^M
- find names ending with D : D$

In [68]:
df[df['car_name'].str.contains(r"\d{3}")]

,car_name,mpg,car_name_updated,brand,upper_name,lower_name,clean_name
2,Datsun 710,22.8,Datsun 710,Datsun,DATSUN 710,datsun 710,Datsun 710
6,Duster 360,14.3,Duster 360,Duster,DUSTER 360,duster 360,Duster 360
7,merc 240D,24.4,merc 240D,merc,MERC 240D,merc 240d,merc 240D
8,Merc 230,22.8,Mercedes 230,Merc,MERC 230,merc 230,Merc 230
9,Merc 280,19.2,Mercedes 280,Merc,MERC 280,merc 280,Merc 280

In [69]:
df[df['car_name'].str.contains(r"^M")]

,car_name,mpg,car_name_updated,brand,upper_name,lower_name,clean_name
0,Mazda RX4,21.0,Mazda RX4,Mazda,MAZDA RX4,mazda rx4,Mazda RX4
1,Mazda RX4 Wag,21.0,Mazda RX4 Wag,Mazda,MAZDA RX4 WAG,mazda rx4 wag,Mazda RX4 Wag
8,Merc 230,22.8,Mercedes 230,Merc,MERC 230,merc 230,Merc 230
9,Merc 280,19.2,Mercedes 280,Merc,MERC 280,merc 280,Merc 280

In [70]:
df[df['car_name'].str.contains(r"D$")]

    car_name   mpg car_name_updated brand upper_name lower_name clean_name
7  merc 240D  24.4        merc 240D  merc  MERC 240D  merc 240d  merc 240D

# NLP
- clean text
- tokenize (split into words)
- count words
- find patterns

In [49]:
texts = [    "Python is easy to learn",     "Data Science is powerful",   "Python makes data analysis easy",  "Machine learning is part of data science"]
texts

['Python is easy to learn',
 'Data Science is powerful',
 'Python makes data analysis easy',
 'Machine learning is part of data science']

In [50]:
# Clean
clean_texts = [t.lower() for t in texts]
print(clean_texts)

['python is easy to learn', 'data science is powerful', 'python makes data analysis easy', 'machine learning is part of data science']

In [51]:
# Tokenization
tokens = [t.split() for t in clean_texts]
print(tokens)

[['python', 'is', 'easy', 'to', 'learn'], ['data', 'science', 'is', 'powerful'], ['python', 'makes', 'data', 'analysis', 'easy'], ['machine', 'learning', 'is', 'part', 'of', 'data', 'science']]

In [57]:
# Count words
word_count = sum(len(t.split()) for t in clean_texts)
print("Total words:", word_count)

Total words: 21

Step-by-Step Calculation

Original Text	                        t.lower()	                           t.split()	                                              len()
"Python is easy to learn"	        "python is easy to learn"	          ['python', 'is', 'easy', 'to', 'learn']	                        5
"Data Science is powerful"	        "data science is powerful"	          ['data', 'science', 'is', 'powerful']	                            4
"Python makes data analysis easy"	"python makes data analysis easy"	  ['python', 'makes', 'data', 'analysis', 'easy']	                5
"Machine learning is part of..."	"machine learning is part of..."	  ['machine', 'learning', 'is', 'part', 'of', 'data', 'science']	7
                                                                                                                           TOTAL			21
Final Result: word_count will be 21.

In [67]:
# Most frequent word
from collections import Counter
all_words = " ".join(clean_texts).split()
freq = Counter(all_words)
print(freq.most_common(3),'\n')
print(freq)

[('is', 3), ('data', 3), ('python', 2)]

Counter({'is': 3, 'data': 3, 'python': 2, 'easy': 2, 'science': 2, 'to': 1, 'learn': 1, 'powerful': 1, 'makes': 1, 'analysis': 1, 'machine': 1, 'learning': 1, 'part': 1, 'of': 1})

1. Merge into a Single String
all_words = " ".join(clean_texts)
.join(clean_texts): Takes all four sentences and glues them together into one giant string.
" ": Uses a space as the glue.
Result: "python is easy to learn data science is powerful..."

2. Tokenize (Create one big list)
... .split()
Breaks that giant string into individual words.
Result: ['python', 'is', 'easy', 'to', 'learn', 'data', 'science', 'is', ...]

3. Count Frequencies
freq = Counter(all_words)
Creates a dictionary-like object where the key is the word and the value is the count.
Internal logic: It sees "is", adds 1. Sees "is" again, adds 1.
Result: Counter({'is': 4, 'data': 3, 'python': 2, ...})

4. Extract the Top 3
print(freq.most_common(3))
This method sorts the words by their count in descending order and picks the top 3.
Result: [('is', 4), ('data', 3), ('python', 2)]

Why this is useful in NLP
Theme Detection: Finding out what the text is mostly about.
Stop Word Identification: Seeing if generic words like "is" or "the" are cluttering your data (in this case, "is" is the most common).

Want to see the count for every word, just print freq instead of freq.most_common(3)

In [68]:
# sentences with Python
python_sentences = [t for t in clean_texts if "python" in t]
print(python_sentences)

['python is easy to learn', 'python makes data analysis easy']

In [69]:
# Replace a word
updated = [t.replace("data", "information") for t in clean_texts]
print(updated)

['python is easy to learn', 'information science is powerful', 'python makes information analysis easy', 'machine learning is part of information science']