# Advanced Panda Functions
- read data, search, filter, etc

# Tasks of Data Analyst
- Collect Data
- Understand Trends and Pattern of the data
- Organise Data
- Clean the data
- Cut the data
- Analysis of Data, Make Conlcusions
- Corraborate data with different data - Storytelling with data
- Make the decision
- Predict the data
- Visualisation / Graphs
# Data Analyst Profile
- Assignment - List out tasks and skills of Data Analyst
- Steps of doing Data Analyst

In [116]:
# libraries
import numpy as np
import pandas as pd

In [117]:
#options
pd.set_option('display.max_columns', None)

In [119]:
from pydataset import data
mtcars = data('mtcars')
mtcars.head(3)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

In [124]:
', '.join(data()['dataset_id'])

'AirPassengers, BJsales, BOD, Formaldehyde, HairEyeColor, InsectSprays, JohnsonJohnson, LakeHuron, LifeCycleSavings, Nile, OrchardSprays, PlantGrowth, Puromycin, Titanic, ToothGrowth, UCBAdmissions, UKDriverDeaths, UKgas, USAccDeaths, USArrests, USJudgeRatings, USPersonalExpenditure, VADeaths, WWWusage, WorldPhones, airmiles, airquality, anscombe, attenu, attitude, austres, cars, chickwts, co2, crimtab, discoveries, esoph, euro, faithful, freeny, infert, iris, islands, lh, longley, lynx, morley, mtcars, nhtemp, nottem, npk, occupationalStatus, precip, presidents, pressure, quakes, randu, rivers, rock, sleep, stackloss, sunspot.month, sunspot.year, sunspots, swiss, treering, trees, uspop, volcano, warpbreaks, women, acme, aids, aircondit, aircondit7, amis, aml, bigcity, brambles, breslow, calcium, cane, capability, catsM, cav, cd4, channing, city, claridge, cloth, co.transfer, coal, darwin, dogs, downs.bc, ducks, fir, frets, grav, gravity, hirose, islay, manaus, melanoma, motor, neuro, nitrofen, nodal, nuclear, paulsen, poisons, polar, remission, salinity, survival, tau, tuna, urine, wool, aids, alloauto, allograft, azt, baboon, bcdeter, bfeed, bmt, bnct, btrial, burn, channing, drug6mp, drughiv, hodg, kidney, kidrecurr, kidtran, larynx, lung, pneumon, psych, rats, std, stddiag, tongue, twins, Animals2, CrohnD, NOxEmissions, SiegelsEx, aircraft, airmay, alcohol, ambientNOxCH, bushfire, carrots, cloud, coleman, condroz, cushny, delivery, education, epilepsy, exAM, foodstamp, hbk, heart, kootenay, lactic, milk, pension, phosphor, pilot, possumDiv, pulpfiber, radarImage, salinity, starsCYG, telef, toxicity, vaso, wagnerGrowth, wood, AMSsurvey, Adler, Angell, Anscombe, Baumann, Bfox, Blackmoor, Burt, CanPop, Chile, Chirot, Cowles, Davis, DavisThin, Depredations, Duncan, Ericksen, Florida, Freedman, Friendly, Ginzberg, Greene, Guyer, Hartnagel, Highway1, Leinhardt, Mandel, Migration, Moore, Mroz, OBrienKaiser, Ornstein, Pottery, Prestige, Quartet, Robey, SLID, Sahlins, Salaries, Soils, States, Transact, UN, USPop, Vocab, WeightLoss, Womenlf, Wool, agriculture, animals, chorSub, flower, plantTraits, pluton, ruspini, votes.repub, xclara, affairs, azcabgptca, azdrg112, azpro, azprocedure, badhealth, fasttrakg, fishing, lbw, lbwgrp, loomis, mdvis, medpar, nuts, rwm, rwm1984, rwm5yr, ships, smoking, titanic, titanicgrp, Accident, Airline, Airq, Benefits, Bids, BudgetFood, BudgetItaly, BudgetUK, Bwages, CPSch3, CRANpackages, Capm, Car, Caschool, Catsup, Cigar, Cigarette, Clothing, Computers, Cracker, Crime, DM, Diamond, Doctor, DoctorAUS, DoctorContacts, Earnings, Electricity, Fair, Fatality, Fishing, Forward, FriendFoe, Garch, Gasoline, Griliches, Grunfeld, HC, HI, Hdma, Heating, Hedonic, Housing, Icecream, Journals, Kakadu, Ketchup, Klein, LaborSupply, Labour, MCAS, Males, Mathlevel, MedExp, Metal, Mode, ModeChoice, Mofa, Mroz, MunExp, NaturalPark, Nerlove, OFP, Oil, PSID, Participation, PatentsHGH, PatentsRD, Pound, Produc, RetSchool, SP500, Schooling, Somerville, Star, Strike, StrikeDur, StrikeNb, SumHes, Tobacco, Train, TranspEq, Treatment, Tuna, USFinanceIndustry, USclassifiedDocuments, USstateAbbreviations, UStaxWords, UnempDur, Unemployment, University, VietNamH, VietNamI, Wages, Wages1, Workinghours, Yen, Yogurt, bankingCrises, incomeInequality, nonEnglishNames, politicalKnowledge, PD, aldh2, apoeapoc, cf, crohn, fa, fsnps, hla, hr1420, l51, lukas, mao, mfblong, mhtdata, nep499, diamonds, economics, midwest, movies, mpg, msleep, presidential, seals, Arbuthnot, Bowley, Cavendish, ChestSizes, CushnyPeebles, CushnyPeeblesN, Dactyl, DrinksWages, Fingerprints, Galton, GaltonFamilies, Guerry, Jevons, Langren.all, Langren1644, Macdonell, MacdonellDF, Michelson, MichelsonSets, Minard.cities, Minard.temp, Minard.troops, Nightingale, OldMaps, PearsonLee, PolioTrials, Prostitutes, Pyx, Quarrels, Snow.deaths, Snow.polygons, Snow.pumps, Snow.streets, Wheat, Wheat.monarchs, Yeast, YeastD.mat, ZeaMays, barley, environmental, ethanol, melanoma, singer, Aids2, Animals, Boston, Cars93, Cushings, DDT, GAGurine, Insurance, Melanoma, OME, Pima.te, Pima.tr, Pima.tr2, Rabbit, Rubber, SP500, Sitka, Sitka89, Skye, Traffic, UScereal, UScrime, VA, abbey, accdeaths, anorexia, bacteria, beav1, beav2, biopsy, birthwt, cabbages, caith, cats, cement, chem, coop, cpus, crabs, deaths, drivers, eagles, epil, farms, fgl, forbes, galaxies, gehan, genotype, geyser, gilgais, hills, housing, immer, leuk, mammals, mcycle, menarche, michelson, minn38, motors, muscle, newcomb, nlschools, npk, npr1, oats, painters, petrol, quine, road, rotifer, ships, shrimp, shuttle, snails, steam, stormer, survey, synth.te, synth.tr, topo, waders, whiteside, wtloss, Cigar, Crime, EmplUK, Gasoline, Grunfeld, Hedonic, LaborSupply, Males, Produc, Snmesp, SumHes, Wages, baseball, AustralianElectionPolling, AustralianElections, EfronMorris, RockTheVote, UKHouseOfCommons, absentee, admit, bioChemists, ca2006, iraqVote, politicalInformation, presidentialElections, prussian, unionDensity, vote92, french_fries, smiths, tips, car.test.frame, car90, cu.summary, kyphosis, solder, stagec, PublicSchools, Bollen, CNES, Klein, Kmenta, Tests, bladder, cancer, cgd, colon, flchain, heart, kidney, leukemia, logan, lung, mgus, nwtco, ovarian, pbc, rats, stanford2, tobin, veteran, Arthritis, Baseball, BrokenMarriage, Bundesliga, Bundestag2005, Butterfly, CoalMiners, DanishWelfare, Employment, Federalist, Hitters, HorseKicks, Hospital, JobSatisfaction, JointSports, Lifeboats, NonResponse, OvaryCancer, PreSex, Punishment, RepVict, Saxony, SexualFun, SpaceShuttle, Suicide, Trucks, UKSoccer, VisualAcuity, VonBort, WeldonDice, WomenQueue, MatchIt.url, PErisk, SupremeCourt, Weimar, Zelig.url, approval, bivariate, coalition, coalition2, eidat, free1, free2, friendship, grunfeld, hoff, homerun, immi1, immi2, immi3, immi4, immi5, immigration, klein, kmenta, macro, mexico, mid, newpainters, sanction, sna.ex, swiss, tobin, turnout, voteincome, BCG, BtheB, CYGOB1, Forbes2000, GHQ, Lanza, agefat, aspirin, birthdeathrates, bladdercancer, clouds, epilepsy, foster, heptathlon, mastectomy, meteo, orallesions, phosphate, pistonrings, planets, plasma, polyps, polyps3, pottery, rearrests, respiratory, roomwidth, schizophrenia, schizophrenia2, schooldays, skulls, smoking, students, suicides, toothpaste, voting, water, watervoles, waves, weightgain, womensrole, Bechtoldt, Bechtoldt.1, Bechtoldt.2, Dwyer, Gleser, Gorsuch, Harman.5, Harman.8, Harman.political, Holzinger, Holzinger.9, Reise, Schmid, Thurstone, Thurstone.33, Tucker, ability, affect, bfi, bfi.dictionary, blot, burt, cities, cubits, cushny, epi, epi.bfi, epi.dictionary, galton, heights, income, iqitems, msq, neo, peas, sat.act, withinBetween, Bosco, CobarOre, Mammals, barro, engel, uis, dietox, koch, ohio, respdis, respiratory, seizure, sitka89, spruce, liver, portpirie, rain, summer, wavesurge, winter, arthritis, housing, bmw, danish, nidd.annual, nidd.thresh, siemens, sp.raw, spto87, Dyestuff, Dyestuff2, InstEval, Pastes, Penicillin, VerbAgg, cake, cbpp, grouseticks, sleepstudy'

In [121]:
mtcars.sample(3)

                 mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  carb
Merc 280C       17.8    6  167.6  123  3.92  3.440  18.9   1   0     4     4
Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.9   1   1     4     1
Merc 450SE      16.4    8  275.8  180  3.07  4.070  17.4   0   0     3     3

In [126]:
data('iris').head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa
4           4.6          3.1           1.5          0.2  setosa
5           5.0          3.6           1.4          0.2  setosa

### Advanced
- change dtypes
- encode
- rowname to columns
- filter
- sort
- select dtypes
- pivot
- melt
- wide

### A data frame with 32 observations on 11 (numeric) variables.
- mpg	Miles/(US) gallon
- cyl	Number of cylinders : Discrete/Category
- disp	Displacement (cu.in.)
- hp	Gross horsepower
- drat	Rear axle ratio
- wt	Weight (1000 lbs)
- qsec	1/4 mile time
- vs	Engine (0 = V-shaped, 1 = straight) : Category
- am	Transmission (0 = automatic, 1 = manual) : Category
- gear	Number of forward gears : Category

In [127]:
mtcars.dtypes

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [128]:
# change data types
mtcars.head(3)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

In [130]:
# Convert selected columns to category
mtcars = data('mtcars')
mtcars = mtcars.astype({ 'cyl':'category', 'vs': 'category',  'carb': 'category',  
                         'am':   'category',  'gear':  'category' } )

In [131]:
mtcars.dtypes

mpg      float64
cyl     category
disp     float64
hp         int64
drat     float64
wt       float64
qsec     float64
vs      category
am      category
gear    category
carb    category
dtype: object

In [132]:
mtcars.head()

                    mpg cyl   disp   hp  drat     wt   qsec vs am gear carb
Mazda RX4          21.0   6  160.0  110  3.90  2.620  16.46  0  1    4    4
Mazda RX4 Wag      21.0   6  160.0  110  3.90  2.875  17.02  0  1    4    4
Datsun 710         22.8   4  108.0   93  3.85  2.320  18.61  1  1    4    1
Hornet 4 Drive     21.4   6  258.0  110  3.08  3.215  19.44  1  0    3    1
Hornet Sportabout  18.7   8  360.0  175  3.15  3.440  17.02  0  0    3    2

In [134]:
mtcars.describe(include='all')

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.0,32.000000,32.000000,32.000000,32.000000,32.000000,32.0,32.0,32.0,32.0
unique,NaN,3.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,3.0,6.0
top,NaN,8.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,3.0,2.0
freq,NaN,14.0,NaN,NaN,NaN,NaN,NaN,18.0,19.0,15.0,10.0
mean,20.090625,NaN,230.721875,146.687500,3.596563,3.217250,17.848750,NaN,NaN,NaN,NaN
std,6.026948,NaN,123.938694,68.562868,0.534679,0.978457,1.786943,NaN,NaN,NaN,NaN
min,10.400000,NaN,71.100000,52.000000,2.760000,1.513000,14.500000,NaN,NaN,NaN,NaN
25%,15.425000,NaN,120.825000,96.500000,3.080000,2.581250,16.892500,NaN,NaN,NaN,NaN
50%,19.200000,NaN,196.300000,123.000000,3.695000,3.325000,17.710000,NaN,NaN,NaN,NaN
75%,22.800000,NaN,326.000000,180.000000,3.920000,3.610000,18.900000,NaN,NaN,NaN,NaN
max,33.900000,NaN,472.000000,335.000000,4.930000,5.424000,22.900000,NaN,NaN,NaN,NaN

In [135]:
# encode - map
mtcars['am'] = mtcars['am'].map({0: 'auto', 1: 'manual'})
mtcars.head()
#mtcars['am'] = mtcars['am'].replace({0: 'auto', 1: 'manual'})

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,manual,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,manual,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,manual,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,auto,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,auto,3,2

In [136]:
mtcars['mpg'].max()

33.9

In [137]:
mtcars[mtcars['mpg'] > 30].sort_values('mpg', ascending=False)

                 mpg cyl  disp   hp  drat     wt   qsec vs      am gear carb
Toyota Corolla  33.9   4  71.1   65  4.22  1.835  19.90  1  manual    4    1
Fiat 128        32.4   4  78.7   66  4.08  2.200  19.47  1  manual    4    1
Honda Civic     30.4   4  75.7   52  4.93  1.615  18.52  1  manual    4    2
Lotus Europa    30.4   4  95.1  113  3.77  1.513  16.90  1  manual    5    2

In [138]:
mtcars[mtcars['mpg'] == mtcars['mpg'].max()]

                 mpg cyl  disp  hp  drat     wt  qsec vs      am gear carb
Toyota Corolla  33.9   4  71.1  65  4.22  1.835  19.9  1  manual    4    1

In [ ]:
mtcars[mtcars['mpg'] >= mtcars['mpg'].mean()]

In [ ]:
bins = [0, 17, 29, mtcars['mpg'].max()]
labels = ['Low', 'Medium', 'High']

# Create the new categorical column
mtcars['mpg_level'] = pd.cut(mtcars['mpg'], bins=bins, labels=labels, include_lowest=True)

In [ ]:
mtcars.describe()

In [ ]:
bins = [0, 70, 150, 250, mtcars['hp'].max()]
labels = ['Low', 'Medium', 'High', 'VeryHigh']
mtcars['hp_level'] = pd.cut(mtcars['hp'], bins=bins, labels=labels, include_lowest=True)

In [ ]:
mtcars['hp_level'].value_counts()

In [ ]:
mtcars.head()

In [ ]:
mtcars.groupby('mpg_level')['mpg'].count()

In [ ]:
mtcars.mpg_level.value_counts()

In [ ]:
mtcars['vs'] = mtcars['vs'].map({0: 'Vshaped', 1: 'Straight'})
mtcars.head()

In [ ]:
#mtcars.reset_index()

In [ ]:
mtcars.index

In [ ]:
mtcars.head()

In [ ]:
# carnames
mtcars['car_name'] = mtcars.index

In [ ]:
mtcars.head()

In [ ]:
mtcars.dtypes  #float, category, object(text), int

In [ ]:
print(len(mtcars[mtcars['mpg'] > 25]))
mtcars[mtcars['mpg'] > 25]
# list cars with mileage more than 25

In [ ]:
mtcars[mtcars['wt'] >= 5]

In [ ]:
mtcars[mtcars['mpg_level'] == 'High' ]

In [ ]:
mtcars.query("mpg < 23")

In [ ]:
mtcars.filter(items =['mpg','hp'])
# list the data with columns mpg & hp

In [ ]:
mtcars[mtcars['am'] == 'auto']
# list cars which auto

In [ ]:
mtcars[(mtcars['am'] == 'auto') & (mtcars['cyl'] != '5') & (mtcars['mpg'] > 22 )]
# Use & for “AND” between them. cars = auto, cyl <> 5, mpg>22 ; all 3 conditions
# in Pandas, | = OR, ~ = NOT.

In [ ]:
mtcars[mtcars['mpg'].between(left=23, right=26.1, inclusive='left')] #inclusive{“both”, “neither”, “left”, “right”}
# cars with mpg between 23 and 26

In [139]:
mtcars[mtcars['mpg'].between(23, 30, inclusive='neither')]

                mpg cyl   disp  hp  drat     wt  qsec vs      am gear carb
Merc 240D      24.4   4  146.7  62  3.69  3.190  20.0  1    auto    4    2
Fiat X1-9      27.3   4   79.0  66  4.08  1.935  18.9  1  manual    4    1
Porsche 914-2  26.0   4  120.3  91  4.43  2.140  16.7  0  manual    5    2

In [140]:
mtcars[mtcars['mpg'].between(23, 30) & (mtcars['am'] == 'manual')]

                mpg cyl   disp  hp  drat     wt  qsec vs      am gear carb
Fiat X1-9      27.3   4   79.0  66  4.08  1.935  18.9  1  manual    4    1
Porsche 914-2  26.0   4  120.3  91  4.43  2.140  16.7  0  manual    5    2

In [ ]:
mtcars[mtcars['gear'].isin([4,5])]
#mtcars['gear'].isin([4,5])
# list cars whose gear is in values 4,5

In [ ]:
mtcars[ (mtcars['gear'].isin([4, 5])) | (mtcars['am'] =='auto')]
# all auto or gear = 4,5

In [ ]:
mtcars[~mtcars['gear'].isin([4, 5])]
# cars other gears values in 4,5 : ~ opposite

### select dtypes

In [ ]:
mtcars.dtypes

In [ ]:
mtcars.select_dtypes(include='number') #.head
# list columns which are numeric

In [ ]:
mtcars.select_dtypes(include='category').head()
# list columns which category type

In [ ]:
mtcars.select_dtypes(include='object').head()
# string, car names

### nlargest for a column

In [ ]:
mtcars.nlargest(5, 'mpg')
# list cars which are among top 5 mpg

In [ ]:
mtcars.nsmallest(5, 'wt')

### sort values

In [ ]:
#mtcars= mtcars.sort_values(by='mpg', ascending=True, inplace=False)
#mtcars.sort_values(by='mpg', ascending=True, inplace=True)

In [ ]:
mtcars.sort_values(by='mpg', ascending=True, inplace=True) #.head()
# list mtcars by mpg, in increasing order

In [ ]:
mtcars

In [ ]:
mtcars.sort_values(['gear','mpg']) #.head()  #first by gear, mpg

In [ ]:
mtcars.sort_values(['gear','mpg'], ascending=[False,True])#.head()  #first by gear, mpg

## Hold - 12 Apr 2026 - 18 Apr 2026

In [141]:
import pandas as pd
import numpy as np
from pydataset import data
mtcars = data('mtcars')
mtcars.shape

(32, 11)

### Pivot Table
- index= → What goes down the rows
- columns= → What goes across the top
- values= → What fills the table
- aggfunc= → How to summarize if there are duplicates

In [142]:
# how may cars have gear=5, am=0

In [144]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [143]:
mtcars.pivot_table(values = 'mpg', index='gear', observed=False)
# no aggregation or default aggregation ie mean
# Mean mpg of Gear 3 cars is 16

            mpg
gear
3     16.106667
4     24.533333
5     21.380000

In [145]:
mtcars.pivot_table(values = 'hp', index='cyl', observed=False)
# mean hp of Cyl-4 cars is 82

             hp
cyl
4     82.636364
6    122.285714
8    209.214286

In [159]:
mtcars.pivot_table(values = ['mpg','hp'], index=['gear','am'], observed=True, 
                   aggfunc=['sum','mean','count']).reset_index()
#sum of mpg for each gear type

  gear am   sum               mean            count
             hp    mpg          hp        mpg    hp mpg
0    3  0  2642  241.6  176.133333  16.106667    15  15
1    4  0   403   84.2  100.750000  21.050000     4   4
2    4  1   671  210.2   83.875000  26.275000     8   8
3    5  1   978  106.9  195.600000  21.380000     5   5

In [150]:
#?mtcars.pivot_table

In [160]:
pd.pivot_table( data=mtcars, observed=False,
    index='gear',          # Rows
    values='mpg',          # Values to summarize
    aggfunc='median'         # Aggregation function
)
# Median of Gear-3 cars is 15.5

       mpg
gear
3     15.5
4     22.8
5     19.7

In [161]:
pivot1 = pd.pivot_table(
    data=mtcars, observed=False,
    index='gear',          # Rows
    columns='am',          # Columns
    values='mpg',          # Values to summarize
    aggfunc='mean'         # Aggregation function
)

In [162]:
pivot1
# Mean of Gear-3 & Auto Tx - 16, while for Gear-3 & Manual Tx- No cars

am            0       1
gear
3     16.106667     NaN
4     21.050000  26.275
5           NaN  21.380

In [163]:
print(mtcars.am.value_counts(), mtcars.cyl.value_counts())

am
0    19
1    13
Name: count, dtype: int64 cyl
8    14
4    11
6     7
Name: count, dtype: int64

In [167]:
pd.pivot_table( observed=True , data= mtcars,  index='gear',  columns='am', \
                values='mpg',
                aggfunc=['mean', 'max', 'min' ,'count','sum']\
              )
# 32 cars

           mean           max         min       count         sum
am            0       1     0     1     0     1     0    1      0      1
gear
3     16.106667     NaN  21.5   NaN  10.4   NaN  15.0  NaN  241.6    NaN
4     21.050000  26.275  24.4  33.9  17.8  21.0   4.0  8.0   84.2  210.2
5           NaN  21.380   NaN  30.4   NaN  15.0   NaN  5.0    NaN  106.9

In [ ]:
pd.pivot_table(data= mtcars,  index=['gear','am'],  columns='cyl',  values='mpg', \
                aggfunc=['mean', 'max', 'min' ,'count','sum','std'] ).reset_index()
#19.75 mean mpg - gear3, am0, cyl6

In [ ]:
pd.pivot_table(data=mtcars, index='cyl', columns='carb', values='hp', aggfunc=['min','max','count'])

##  Advanced - 2
- wide, long
- missing values
- airquality dataset is perfect
    - Wide format: Columns for Ozone, Solar.R, Wind, Temp, Month, Day
    - Has missing values in Ozone and Solar.R → great for .isnull(), .fillna(), .dropna() practice
    - Can be melted into long format to have "variable" and "value" columns

In [ ]:
from pydataset import data

aq = data('airquality')
aq.head()

In [ ]:
aq.info()   #153 rows, 6 cols

In [ ]:
print(aq.isnull().sum())  # Shows missing values

In [ ]:
aq.head()  #original data

In [ ]:
# long
aq_long = aq.melt(  id_vars=['Month', 'Day'],  value_vars=['Ozone', 'Solar.R', 'Wind', 'Temp'], \
                     var_name='Measurement',    value_name='Value' )

aq_long.head()

In [ ]:
153 * 4

In [ ]:
aq_long  # 153 rows x 4 columns

### Melt
- https://pandas.pydata.org/docs/reference/api/pandas.melt.html
-  id_vars=['Month', 'Day'],  value_vars=['Ozone', 'Solar.R', 'Wind', 'Temp'], \
                     var_name='Measurement',    value_name='Value' )

In [ ]:
pd.melt(frame=aq, id_vars=['Month', 'Day'], value_vars=['Ozone', 'Wind'],\
        var_name='Measurement', value_name='value', col_level=None, ignore_index=True)

In [ ]:
aq_long.head()

In [ ]:
# wide
aq_wide = aq_long.pivot_table( index=['Month', 'Day'], columns='Measurement', values='Value' ).reset_index()
aq_wide.head(2)

In [ ]:
aq.head(2)

In [ ]:
# missing data
# Drop rows with any missing values
aq_drop = aq.dropna()

# Fill missing Ozone with mean
aq_fill = aq.copy()
aq_fill['Ozone'] = aq_fill['Ozone'].fillna(aq_fill['Ozone'].mean())  #fill missing values in Ozone only

In [ ]:
aq_fill.head()  #ozone missing values filled

## Practise with Student Data
- https://docs.google.com/spreadsheets/d/1jPk4sZyDn5NSIQ4iQK1P3aGh5ZAS2oaYexRoUyocAw0
- sheet_id = '1ABCDefGhIJklMNopQRstuVWxyz12345678'
- gid1 = 'pData1'
- gid2 = 'sData1'
- url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid}"
- df = pd.read_csv(url)

In [ ]:
sheet_id = '1jPk4sZyDn5NSIQ4iQK1P3aGh5ZAS2oaYexRoUyocAw0'
gid1 = '132995188' #pData1
gid2 = '330609257' #'sData1

In [ ]:
url1 = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid1}"
print(url1)

In [ ]:
url2 = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid2}"
print(url2)

In [ ]:
#url1 = "https://docs.google.com/spreadsheets/d/1jPk4sZyDn5NSIQ4iQK1P3aGh5ZAS2oaYexRoUyocAw0/export?format=csv&gid=132995188"
pdata = pd.read_csv(url1)

In [ ]:
pdata.head()

In [ ]:
sdata = pd.read_csv(url2)
sdata.head()

In [ ]:
## Join Data
#https://pandas.pydata.org/docs/reference/api/pandas.merge.html
#how{‘left’, ‘right’, ‘outer’, ‘inner’, ‘cross’}, default ‘inner’
merged = pd.merge(left=pdata, right=sdata, on='rollno' , how = 'inner')
merged.head()

In [ ]:
merged.shape

In [ ]:
## Melt data -  Wide to Long
subvar = ['maths','english', 'stats','python']
idvar = ['rollno','name','gender','program']
marks_long = merged.melt( id_vars = idvar, value_vars =  subvar, var_name='subject', value_name ='marks')

In [ ]:
marks_long.head()

In [ ]:
# Long to Wide 
marks_wide = marks_long.pivot_table( index=idvar, columns = "subject", values= "marks").reset_index()
# first - first observation per group

In [ ]:
marks_wide.head()

In [ ]:
## Missing Data
missing_summary = merged.isnull().sum()
missing_summary

In [ ]:
merged

In [ ]:
merged2 = merged.copy()
merged2["gender"] = merged2["gender"].fillna("Not Specified")
merged2

In [ ]:
subvar

In [ ]:
merged2[subvar].mean()

In [ ]:
for s in subvar:
    merged2[s] = merged2[s].fillna(merged2[s].mean())
merged2.head()  #see changes in missing values of maths, english, stats, python

### Missing Values
- Remove Rows or Columns

In [ ]:
subvar

In [ ]:
merged3R = merged.dropna(subset=subvar) #rows remove

In [ ]:
merged3R.shape  #less rows now

In [ ]:
merged3R

In [ ]:
# Columns wise Missing %
merged.isnull().mean()

In [ ]:
threshold = 0.07  #remove columns which have missing values more than 30%
merged3C = merged.loc[:, merged.isnull().mean() <= threshold]

In [ ]:
merged3C

### Lambda Function
-

In [ ]:
merged.head()

In [ ]:
merged["maths"].apply( lambda x: x * 1.20 if pd.notnull(x) else x)

In [ ]:
merged.assign( englishU = lambda df: merged["english"] * 1.10 ).head()

## Dates
- pd.Timestamp(date.today()) → current date
- errors="coerce" → invalid dates become NaT (Not a Time) instead of crashing.
- Pandas auto-detects most formats (YYYY-MM-DD, DD/MM/YYYY, etc.), but you can force a format:
- Subtract DOB from today → 
- To calculate age in years, you need to divide the timedelta by a constant (e.g., 365.25 days) or use dateutil.relativedelta for an exact year/month calculation.

In [ ]:
import pandas as pd
from datetime import date
from dateutil.relativedelta import relativedelta

In [ ]:
merged.head()

In [ ]:
merged.dtypes

In [ ]:
merged['dob'] = pd.to_datetime(merged['dob'], errors="coerce")
# pd.to_datetime(merged['dob'], format="%Y-%m-%d")
merged.dtypes

In [ ]:
merged.head()

In [ ]:
today = pd.Timestamp(date.today())
today

In [ ]:
merged["age"] = (today - merged["dob"]).dt.days // 365 # // as to interpret division
merged.head()

In [ ]:
merged["ageYM"] = merged["dob"].apply (
    lambda dob: f"{relativedelta(date.today(), dob).years} years, {relativedelta(date.today(), dob).months} months"
    if pd.notnull(dob) else None
)
merged.head()

In [ ]:
# students whose bday comes in Sep
merged[merged["dob"].dt.month == 2]

## END HERE
- now practise aggregations, groupby,
- time series