# Advanced Panda Functions
- read data, search, filter, etc

# Tasks of Data Analyst
- Collect Data
- Understand Trends and Pattern of the data
- Organise Data
- Clean the data
- Cut the data
- Analysis of Data, Make Conlcusions
- Corraborate data with different data - Storytelling with data
- Make the decision
- Predict the data
- Visualisation / Graphs
# Data Analyst Profile
- Assignment - List out tasks and skills of Data Analyst
- Steps of doing Data Analyst

In [1]:
# libraries
import numpy as np
import pandas as pd

In [2]:
#options
pd.set_option('display.max_columns', None)

In [3]:
from pydataset import data
mtcars = data('mtcars')
mtcars.head(3)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

In [4]:
', '.join(data()['dataset_id'])

'AirPassengers, BJsales, BOD, Formaldehyde, HairEyeColor, InsectSprays, JohnsonJohnson, LakeHuron, LifeCycleSavings, Nile, OrchardSprays, PlantGrowth, Puromycin, Titanic, ToothGrowth, UCBAdmissions, UKDriverDeaths, UKgas, USAccDeaths, USArrests, USJudgeRatings, USPersonalExpenditure, VADeaths, WWWusage, WorldPhones, airmiles, airquality, anscombe, attenu, attitude, austres, cars, chickwts, co2, crimtab, discoveries, esoph, euro, faithful, freeny, infert, iris, islands, lh, longley, lynx, morley, mtcars, nhtemp, nottem, npk, occupationalStatus, precip, presidents, pressure, quakes, randu, rivers, rock, sleep, stackloss, sunspot.month, sunspot.year, sunspots, swiss, treering, trees, uspop, volcano, warpbreaks, women, acme, aids, aircondit, aircondit7, amis, aml, bigcity, brambles, breslow, calcium, cane, capability, catsM, cav, cd4, channing, city, claridge, cloth, co.transfer, coal, darwin, dogs, downs.bc, ducks, fir, frets, grav, gravity, hirose, islay, manaus, melanoma, motor, neuro, nitrofen, nodal, nuclear, paulsen, poisons, polar, remission, salinity, survival, tau, tuna, urine, wool, aids, alloauto, allograft, azt, baboon, bcdeter, bfeed, bmt, bnct, btrial, burn, channing, drug6mp, drughiv, hodg, kidney, kidrecurr, kidtran, larynx, lung, pneumon, psych, rats, std, stddiag, tongue, twins, Animals2, CrohnD, NOxEmissions, SiegelsEx, aircraft, airmay, alcohol, ambientNOxCH, bushfire, carrots, cloud, coleman, condroz, cushny, delivery, education, epilepsy, exAM, foodstamp, hbk, heart, kootenay, lactic, milk, pension, phosphor, pilot, possumDiv, pulpfiber, radarImage, salinity, starsCYG, telef, toxicity, vaso, wagnerGrowth, wood, AMSsurvey, Adler, Angell, Anscombe, Baumann, Bfox, Blackmoor, Burt, CanPop, Chile, Chirot, Cowles, Davis, DavisThin, Depredations, Duncan, Ericksen, Florida, Freedman, Friendly, Ginzberg, Greene, Guyer, Hartnagel, Highway1, Leinhardt, Mandel, Migration, Moore, Mroz, OBrienKaiser, Ornstein, Pottery, Prestige, Quartet, Robey, SLID, Sahlins, Salaries, Soils, States, Transact, UN, USPop, Vocab, WeightLoss, Womenlf, Wool, agriculture, animals, chorSub, flower, plantTraits, pluton, ruspini, votes.repub, xclara, affairs, azcabgptca, azdrg112, azpro, azprocedure, badhealth, fasttrakg, fishing, lbw, lbwgrp, loomis, mdvis, medpar, nuts, rwm, rwm1984, rwm5yr, ships, smoking, titanic, titanicgrp, Accident, Airline, Airq, Benefits, Bids, BudgetFood, BudgetItaly, BudgetUK, Bwages, CPSch3, CRANpackages, Capm, Car, Caschool, Catsup, Cigar, Cigarette, Clothing, Computers, Cracker, Crime, DM, Diamond, Doctor, DoctorAUS, DoctorContacts, Earnings, Electricity, Fair, Fatality, Fishing, Forward, FriendFoe, Garch, Gasoline, Griliches, Grunfeld, HC, HI, Hdma, Heating, Hedonic, Housing, Icecream, Journals, Kakadu, Ketchup, Klein, LaborSupply, Labour, MCAS, Males, Mathlevel, MedExp, Metal, Mode, ModeChoice, Mofa, Mroz, MunExp, NaturalPark, Nerlove, OFP, Oil, PSID, Participation, PatentsHGH, PatentsRD, Pound, Produc, RetSchool, SP500, Schooling, Somerville, Star, Strike, StrikeDur, StrikeNb, SumHes, Tobacco, Train, TranspEq, Treatment, Tuna, USFinanceIndustry, USclassifiedDocuments, USstateAbbreviations, UStaxWords, UnempDur, Unemployment, University, VietNamH, VietNamI, Wages, Wages1, Workinghours, Yen, Yogurt, bankingCrises, incomeInequality, nonEnglishNames, politicalKnowledge, PD, aldh2, apoeapoc, cf, crohn, fa, fsnps, hla, hr1420, l51, lukas, mao, mfblong, mhtdata, nep499, diamonds, economics, midwest, movies, mpg, msleep, presidential, seals, Arbuthnot, Bowley, Cavendish, ChestSizes, CushnyPeebles, CushnyPeeblesN, Dactyl, DrinksWages, Fingerprints, Galton, GaltonFamilies, Guerry, Jevons, Langren.all, Langren1644, Macdonell, MacdonellDF, Michelson, MichelsonSets, Minard.cities, Minard.temp, Minard.troops, Nightingale, OldMaps, PearsonLee, PolioTrials, Prostitutes, Pyx, Quarrels, Snow.deaths, Snow.polygons, Snow.pumps, Snow.streets, Wheat, Wheat.monarchs, Yeast, YeastD.mat, ZeaMays, barley, environmental, ethanol, melanoma, singer, Aids2, Animals, Boston, Cars93, Cushings, DDT, GAGurine, Insurance, Melanoma, OME, Pima.te, Pima.tr, Pima.tr2, Rabbit, Rubber, SP500, Sitka, Sitka89, Skye, Traffic, UScereal, UScrime, VA, abbey, accdeaths, anorexia, bacteria, beav1, beav2, biopsy, birthwt, cabbages, caith, cats, cement, chem, coop, cpus, crabs, deaths, drivers, eagles, epil, farms, fgl, forbes, galaxies, gehan, genotype, geyser, gilgais, hills, housing, immer, leuk, mammals, mcycle, menarche, michelson, minn38, motors, muscle, newcomb, nlschools, npk, npr1, oats, painters, petrol, quine, road, rotifer, ships, shrimp, shuttle, snails, steam, stormer, survey, synth.te, synth.tr, topo, waders, whiteside, wtloss, Cigar, Crime, EmplUK, Gasoline, Grunfeld, Hedonic, LaborSupply, Males, Produc, Snmesp, SumHes, Wages, baseball, AustralianElectionPolling, AustralianElections, EfronMorris, RockTheVote, UKHouseOfCommons, absentee, admit, bioChemists, ca2006, iraqVote, politicalInformation, presidentialElections, prussian, unionDensity, vote92, french_fries, smiths, tips, car.test.frame, car90, cu.summary, kyphosis, solder, stagec, PublicSchools, Bollen, CNES, Klein, Kmenta, Tests, bladder, cancer, cgd, colon, flchain, heart, kidney, leukemia, logan, lung, mgus, nwtco, ovarian, pbc, rats, stanford2, tobin, veteran, Arthritis, Baseball, BrokenMarriage, Bundesliga, Bundestag2005, Butterfly, CoalMiners, DanishWelfare, Employment, Federalist, Hitters, HorseKicks, Hospital, JobSatisfaction, JointSports, Lifeboats, NonResponse, OvaryCancer, PreSex, Punishment, RepVict, Saxony, SexualFun, SpaceShuttle, Suicide, Trucks, UKSoccer, VisualAcuity, VonBort, WeldonDice, WomenQueue, MatchIt.url, PErisk, SupremeCourt, Weimar, Zelig.url, approval, bivariate, coalition, coalition2, eidat, free1, free2, friendship, grunfeld, hoff, homerun, immi1, immi2, immi3, immi4, immi5, immigration, klein, kmenta, macro, mexico, mid, newpainters, sanction, sna.ex, swiss, tobin, turnout, voteincome, BCG, BtheB, CYGOB1, Forbes2000, GHQ, Lanza, agefat, aspirin, birthdeathrates, bladdercancer, clouds, epilepsy, foster, heptathlon, mastectomy, meteo, orallesions, phosphate, pistonrings, planets, plasma, polyps, polyps3, pottery, rearrests, respiratory, roomwidth, schizophrenia, schizophrenia2, schooldays, skulls, smoking, students, suicides, toothpaste, voting, water, watervoles, waves, weightgain, womensrole, Bechtoldt, Bechtoldt.1, Bechtoldt.2, Dwyer, Gleser, Gorsuch, Harman.5, Harman.8, Harman.political, Holzinger, Holzinger.9, Reise, Schmid, Thurstone, Thurstone.33, Tucker, ability, affect, bfi, bfi.dictionary, blot, burt, cities, cubits, cushny, epi, epi.bfi, epi.dictionary, galton, heights, income, iqitems, msq, neo, peas, sat.act, withinBetween, Bosco, CobarOre, Mammals, barro, engel, uis, dietox, koch, ohio, respdis, respiratory, seizure, sitka89, spruce, liver, portpirie, rain, summer, wavesurge, winter, arthritis, housing, bmw, danish, nidd.annual, nidd.thresh, siemens, sp.raw, spto87, Dyestuff, Dyestuff2, InstEval, Pastes, Penicillin, VerbAgg, cake, cbpp, grouseticks, sleepstudy'

In [5]:
mtcars.sample(3)

                 mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4 Wag   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Ferrari Dino    19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1

In [6]:
data('iris').head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa
4           4.6          3.1           1.5          0.2  setosa
5           5.0          3.6           1.4          0.2  setosa

### Advanced
- change dtypes
- encode
- rowname to columns
- filter
- sort
- select dtypes
- pivot
- melt
- wide

### A data frame with 32 observations on 11 (numeric) variables.
- mpg	Miles/(US) gallon
- cyl	Number of cylinders : Discrete/Category
- disp	Displacement (cu.in.)
- hp	Gross horsepower
- drat	Rear axle ratio
- wt	Weight (1000 lbs)
- qsec	1/4 mile time
- vs	Engine (0 = V-shaped, 1 = straight) : Category
- am	Transmission (0 = automatic, 1 = manual) : Category
- gear	Number of forward gears : Category

In [7]:
mtcars.dtypes

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [8]:
# change data types
mtcars.head(3)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

In [9]:
# Convert selected columns to category
mtcars = data('mtcars')
mtcars = mtcars.astype({ 'cyl':'category', 'vs': 'category',  'carb': 'category',  
                         'am':   'category',  'gear':  'category' } )

In [10]:
mtcars.dtypes

mpg      float64
cyl     category
disp     float64
hp         int64
drat     float64
wt       float64
qsec     float64
vs      category
am      category
gear    category
carb    category
dtype: object

In [11]:
mtcars.head()

                    mpg cyl   disp   hp  drat     wt   qsec vs am gear carb
Mazda RX4          21.0   6  160.0  110  3.90  2.620  16.46  0  1    4    4
Mazda RX4 Wag      21.0   6  160.0  110  3.90  2.875  17.02  0  1    4    4
Datsun 710         22.8   4  108.0   93  3.85  2.320  18.61  1  1    4    1
Hornet 4 Drive     21.4   6  258.0  110  3.08  3.215  19.44  1  0    3    1
Hornet Sportabout  18.7   8  360.0  175  3.15  3.440  17.02  0  0    3    2

In [12]:
mtcars.describe(include='all')

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.0,32.000000,32.000000,32.000000,32.000000,32.000000,32.0,32.0,32.0,32.0
unique,NaN,3.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,3.0,6.0
top,NaN,8.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,3.0,2.0
freq,NaN,14.0,NaN,NaN,NaN,NaN,NaN,18.0,19.0,15.0,10.0
mean,20.090625,NaN,230.721875,146.687500,3.596563,3.217250,17.848750,NaN,NaN,NaN,NaN
std,6.026948,NaN,123.938694,68.562868,0.534679,0.978457,1.786943,NaN,NaN,NaN,NaN
min,10.400000,NaN,71.100000,52.000000,2.760000,1.513000,14.500000,NaN,NaN,NaN,NaN
25%,15.425000,NaN,120.825000,96.500000,3.080000,2.581250,16.892500,NaN,NaN,NaN,NaN
50%,19.200000,NaN,196.300000,123.000000,3.695000,3.325000,17.710000,NaN,NaN,NaN,NaN
75%,22.800000,NaN,326.000000,180.000000,3.920000,3.610000,18.900000,NaN,NaN,NaN,NaN
max,33.900000,NaN,472.000000,335.000000,4.930000,5.424000,22.900000,NaN,NaN,NaN,NaN

In [13]:
# encode - map
mtcars['am'] = mtcars['am'].map({0: 'auto', 1: 'manual'})
mtcars.head()
#mtcars['am'] = mtcars['am'].replace({0: 'auto', 1: 'manual'})

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,manual,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,manual,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,manual,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,auto,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,auto,3,2

In [14]:
mtcars['mpg'].max()

33.9

In [15]:
mtcars[mtcars['mpg'] > 30].sort_values('mpg', ascending=False)

                 mpg cyl  disp   hp  drat     wt   qsec vs      am gear carb
Toyota Corolla  33.9   4  71.1   65  4.22  1.835  19.90  1  manual    4    1
Fiat 128        32.4   4  78.7   66  4.08  2.200  19.47  1  manual    4    1
Honda Civic     30.4   4  75.7   52  4.93  1.615  18.52  1  manual    4    2
Lotus Europa    30.4   4  95.1  113  3.77  1.513  16.90  1  manual    5    2

In [16]:
mtcars[mtcars['mpg'] == mtcars['mpg'].max()]

                 mpg cyl  disp  hp  drat     wt  qsec vs      am gear carb
Toyota Corolla  33.9   4  71.1  65  4.22  1.835  19.9  1  manual    4    1

In [17]:
mtcars[mtcars['mpg'] >= mtcars['mpg'].mean()]

                 mpg cyl   disp   hp  drat     wt   qsec vs      am gear carb
Mazda RX4       21.0   6  160.0  110  3.90  2.620  16.46  0  manual    4    4
Mazda RX4 Wag   21.0   6  160.0  110  3.90  2.875  17.02  0  manual    4    4
Datsun 710      22.8   4  108.0   93  3.85  2.320  18.61  1  manual    4    1
Hornet 4 Drive  21.4   6  258.0  110  3.08  3.215  19.44  1    auto    3    1
Merc 240D       24.4   4  146.7   62  3.69  3.190  20.00  1    auto    4    2
Merc 230        22.8   4  140.8   95  3.92  3.150  22.90  1    auto    4    2
Fiat 128        32.4   4   78.7   66  4.08  2.200  19.47  1  manual    4    1
Honda Civic     30.4   4   75.7   52  4.93  1.615  18.52  1  manual    4    2
Toyota Corolla  33.9   4   71.1   65  4.22  1.835  19.90  1  manual    4    1
Toyota Corona   21.5   4  120.1   97  3.70  2.465  20.01  1    auto    3    1
Fiat X1-9       27.3   4   79.0   66  4.08  1.935  18.90  1  manual    4    1
Porsche 914-2   26.0   4  120.3   91  4.43  2.140  16.70  0  manual    5    2
Lotus Europa    30.4   4   95.1  113  3.77  1.513  16.90  1  manual    5    2
Volvo 142E      21.4   4  121.0  109  4.11  2.780  18.60  1  manual    4    2

In [18]:
bins = [0, 17, 29, mtcars['mpg'].max()]
labels = ['Low', 'Medium', 'High']

# Create the new categorical column
mtcars['mpg_level'] = pd.cut(mtcars['mpg'], bins=bins, labels=labels, include_lowest=True)

In [19]:
mtcars.describe()

             mpg        disp          hp       drat         wt       qsec
count  32.000000   32.000000   32.000000  32.000000  32.000000  32.000000
mean   20.090625  230.721875  146.687500   3.596563   3.217250  17.848750
std     6.026948  123.938694   68.562868   0.534679   0.978457   1.786943
min    10.400000   71.100000   52.000000   2.760000   1.513000  14.500000
25%    15.425000  120.825000   96.500000   3.080000   2.581250  16.892500
50%    19.200000  196.300000  123.000000   3.695000   3.325000  17.710000
75%    22.800000  326.000000  180.000000   3.920000   3.610000  18.900000
max    33.900000  472.000000  335.000000   4.930000   5.424000  22.900000

In [20]:
bins = [0, 70, 150, 250, mtcars['hp'].max()]
labels = ['Low', 'Medium', 'High', 'VeryHigh']
mtcars['hp_level'] = pd.cut(mtcars['hp'], bins=bins, labels=labels, include_lowest=True)

In [21]:
mtcars['hp_level'].value_counts()

hp_level
Medium      14
High        11
Low          5
VeryHigh     2
Name: count, dtype: int64

In [22]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,manual,4,4,Medium,Medium
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,manual,4,4,Medium,Medium
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,manual,4,1,Medium,Medium
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,auto,3,1,Medium,Medium
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,auto,3,2,Medium,High

In [23]:
mtcars.groupby('mpg_level')['mpg'].count()

mpg_level
Low       11
Medium    17
High       4
Name: mpg, dtype: int64

In [24]:
mtcars.mpg_level.value_counts()

mpg_level
Medium    17
Low       11
High       4
Name: count, dtype: int64

In [25]:
mtcars['vs'] = mtcars['vs'].map({0: 'Vshaped', 1: 'Straight'})
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,Medium,Medium
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,Medium,Medium
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,Medium,Medium
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,Medium,Medium
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,Medium,High

In [26]:
#mtcars.reset_index()

In [27]:
mtcars.index

Index(['Mazda RX4', 'Mazda RX4 Wag', 'Datsun 710', 'Hornet 4 Drive',
       'Hornet Sportabout', 'Valiant', 'Duster 360', 'Merc 240D', 'Merc 230',
       'Merc 280', 'Merc 280C', 'Merc 450SE', 'Merc 450SL', 'Merc 450SLC',
       'Cadillac Fleetwood', 'Lincoln Continental', 'Chrysler Imperial',
       'Fiat 128', 'Honda Civic', 'Toyota Corolla', 'Toyota Corona',
       'Dodge Challenger', 'AMC Javelin', 'Camaro Z28', 'Pontiac Firebird',
       'Fiat X1-9', 'Porsche 914-2', 'Lotus Europa', 'Ford Pantera L',
       'Ferrari Dino', 'Maserati Bora', 'Volvo 142E'],
      dtype='str')

In [28]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,Medium,Medium
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,Medium,Medium
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,Medium,Medium
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,Medium,Medium
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,Medium,High

In [29]:
# carnames
mtcars['car_name'] = mtcars.index

In [30]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,car_name
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,Medium,Medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,Medium,Medium,Mazda RX4 Wag
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,Medium,Medium,Datsun 710
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,Medium,Medium,Hornet 4 Drive
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,Medium,High,Hornet Sportabout

In [31]:
mtcars.dtypes  #float, category, object(text), int

mpg           float64
cyl          category
disp          float64
hp              int64
drat          float64
wt            float64
qsec          float64
vs           category
am           category
gear         category
carb         category
mpg_level    category
hp_level     category
car_name          str
dtype: object

In [32]:
print(len(mtcars[mtcars['mpg'] > 25]))
mtcars[mtcars['mpg'] > 25]
# list cars with mileage more than 25

6

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,car_name
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,manual,4,1,High,Low,Fiat 128
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,manual,4,2,High,Low,Honda Civic
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,manual,4,1,High,Low,Toyota Corolla
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,manual,4,1,Medium,Low,Fiat X1-9
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,Vshaped,manual,5,2,Medium,Medium,Porsche 914-2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,manual,5,2,High,Medium,Lotus Europa

In [33]:
mtcars[mtcars['wt'] >= 5]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,car_name
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,auto,3,4,Low,High,Cadillac Fleetwood
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,auto,3,4,Low,High,Lincoln Continental
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,auto,3,4,Low,High,Chrysler Imperial

In [34]:
mtcars[mtcars['mpg_level'] == 'High' ]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,car_name
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,manual,4,1,High,Low,Fiat 128
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,manual,4,2,High,Low,Honda Civic
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,manual,4,1,High,Low,Toyota Corolla
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,manual,5,2,High,Medium,Lotus Europa

In [35]:
mtcars.query("mpg < 23")

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,car_name
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,Medium,Medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,Medium,Medium,Mazda RX4 Wag
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,Medium,Medium,Datsun 710
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,Medium,Medium,Hornet 4 Drive
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,Medium,High,Hornet Sportabout
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,Straight,auto,3,1,Medium,Medium,Valiant
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,auto,3,4,Low,High,Duster 360
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,Straight,auto,4,2,Medium,Medium,Merc 230
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,Straight,auto,4,4,Medium,Medium,Merc 280
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,Straight,auto,4,4,Medium,Medium,Merc 280C
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,auto,3,3,Low,High,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,auto,3,3,Medium,High,Merc 450SL
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,auto,3,3,Low,High,Merc 450SLC
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,auto,3,4,Low,High,Cadillac Fleetwood
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,auto,3,4,Low,High,Lincoln Continental
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,auto,3,4,Low,High,Chrysler Imperial
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,Straight,auto,3,1,Medium,Medium,Toyota Corona
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,Vshaped,auto,3,2,Low,Medium,Dodge Challenger
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,Vshaped,auto,3,2,Low,Medium,AMC Javelin
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,auto,3,4,Low,High,Camaro Z28
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,auto,3,2,Medium,High,Pontiac Firebird
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,Vshaped,manual,5,4,Low,VeryHigh,Ford Pantera L
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,Vshaped,manual,5,6,Medium,High,Ferrari Dino
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,Vshaped,manual,5,8,Low,VeryHigh,Maserati Bora
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,Straight,manual,4,2,Medium,Medium,Volvo 142E

In [36]:
mtcars.filter(items =['mpg','hp'])
# list the data with columns mpg & hp

                      mpg   hp
Mazda RX4            21.0  110
Mazda RX4 Wag        21.0  110
Datsun 710           22.8   93
Hornet 4 Drive       21.4  110
Hornet Sportabout    18.7  175
Valiant              18.1  105
Duster 360           14.3  245
Merc 240D            24.4   62
Merc 230             22.8   95
Merc 280             19.2  123
Merc 280C            17.8  123
Merc 450SE           16.4  180
Merc 450SL           17.3  180
Merc 450SLC          15.2  180
Cadillac Fleetwood   10.4  205
Lincoln Continental  10.4  215
Chrysler Imperial    14.7  230
Fiat 128             32.4   66
Honda Civic          30.4   52
Toyota Corolla       33.9   65
Toyota Corona        21.5   97
Dodge Challenger     15.5  150
AMC Javelin          15.2  150
Camaro Z28           13.3  245
Pontiac Firebird     19.2  175
Fiat X1-9            27.3   66
Porsche 914-2        26.0   91
Lotus Europa         30.4  113
Ford Pantera L       15.8  264
Ferrari Dino         19.7  175
Maserati Bora        15.0  335
Volvo 142E           21.4  109

In [37]:
mtcars[mtcars['am'] == 'auto']
# list cars which auto

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,car_name
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,Medium,Medium,Hornet 4 Drive
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,Medium,High,Hornet Sportabout
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,Straight,auto,3,1,Medium,Medium,Valiant
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,auto,3,4,Low,High,Duster 360
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,Straight,auto,4,2,Medium,Low,Merc 240D
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,Straight,auto,4,2,Medium,Medium,Merc 230
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,Straight,auto,4,4,Medium,Medium,Merc 280
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,Straight,auto,4,4,Medium,Medium,Merc 280C
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,auto,3,3,Low,High,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,auto,3,3,Medium,High,Merc 450SL
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,auto,3,3,Low,High,Merc 450SLC
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,auto,3,4,Low,High,Cadillac Fleetwood
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,auto,3,4,Low,High,Lincoln Continental
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,auto,3,4,Low,High,Chrysler Imperial
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,Straight,auto,3,1,Medium,Medium,Toyota Corona
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,Vshaped,auto,3,2,Low,Medium,Dodge Challenger
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,Vshaped,auto,3,2,Low,Medium,AMC Javelin
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,auto,3,4,Low,High,Camaro Z28
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,auto,3,2,Medium,High,Pontiac Firebird

In [38]:
mtcars[(mtcars['am'] == 'auto') & (mtcars['cyl'] != '5') & (mtcars['mpg'] > 22 )]
# Use & for “AND” between them. cars = auto, cyl <> 5, mpg>22 ; all 3 conditions
# in Pandas, | = OR, ~ = NOT.

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,car_name
Merc 240D,24.4,4,146.7,62,3.69,3.19,20.0,Straight,auto,4,2,Medium,Low,Merc 240D
Merc 230,22.8,4,140.8,95,3.92,3.15,22.9,Straight,auto,4,2,Medium,Medium,Merc 230

In [39]:
mtcars[mtcars['mpg'].between(left=23, right=26.1, inclusive='left')] #inclusive{“both”, “neither”, “left”, “right”}
# cars with mpg between 23 and 26

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,car_name
Merc 240D,24.4,4,146.7,62,3.69,3.19,20.0,Straight,auto,4,2,Medium,Low,Merc 240D
Porsche 914-2,26.0,4,120.3,91,4.43,2.14,16.7,Vshaped,manual,5,2,Medium,Medium,Porsche 914-2

In [40]:
mtcars[mtcars['mpg'].between(23, 30, inclusive='neither')]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,car_name
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.0,Straight,auto,4,2,Medium,Low,Merc 240D
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.9,Straight,manual,4,1,Medium,Low,Fiat X1-9
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.7,Vshaped,manual,5,2,Medium,Medium,Porsche 914-2

In [41]:
mtcars[mtcars['mpg'].between(23, 30) & (mtcars['am'] == 'manual')]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,car_name
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.9,Straight,manual,4,1,Medium,Low,Fiat X1-9
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.7,Vshaped,manual,5,2,Medium,Medium,Porsche 914-2

In [42]:
mtcars[mtcars['gear'].isin([4,5])]
#mtcars['gear'].isin([4,5])
# list cars whose gear is in values 4,5

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,car_name
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,Medium,Medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,Medium,Medium,Mazda RX4 Wag
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,Medium,Medium,Datsun 710
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,Straight,auto,4,2,Medium,Low,Merc 240D
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,Straight,auto,4,2,Medium,Medium,Merc 230
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,Straight,auto,4,4,Medium,Medium,Merc 280
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,Straight,auto,4,4,Medium,Medium,Merc 280C
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,manual,4,1,High,Low,Fiat 128
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,manual,4,2,High,Low,Honda Civic
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,manual,4,1,High,Low,Toyota Corolla
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,manual,4,1,Medium,Low,Fiat X1-9
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,Vshaped,manual,5,2,Medium,Medium,Porsche 914-2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,manual,5,2,High,Medium,Lotus Europa
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,Vshaped,manual,5,4,Low,VeryHigh,Ford Pantera L
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,Vshaped,manual,5,6,Medium,High,Ferrari Dino
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,Vshaped,manual,5,8,Low,VeryHigh,Maserati Bora
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,Straight,manual,4,2,Medium,Medium,Volvo 142E

In [43]:
mtcars[ (mtcars['gear'].isin([4, 5])) | (mtcars['am'] =='auto')]
# all auto or gear = 4,5

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,car_name
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,Medium,Medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,Medium,Medium,Mazda RX4 Wag
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,Medium,Medium,Datsun 710
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,Medium,Medium,Hornet 4 Drive
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,Medium,High,Hornet Sportabout
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,Straight,auto,3,1,Medium,Medium,Valiant
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,auto,3,4,Low,High,Duster 360
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,Straight,auto,4,2,Medium,Low,Merc 240D
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,Straight,auto,4,2,Medium,Medium,Merc 230
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,Straight,auto,4,4,Medium,Medium,Merc 280
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,Straight,auto,4,4,Medium,Medium,Merc 280C
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,auto,3,3,Low,High,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,auto,3,3,Medium,High,Merc 450SL
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,auto,3,3,Low,High,Merc 450SLC
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,auto,3,4,Low,High,Cadillac Fleetwood
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,auto,3,4,Low,High,Lincoln Continental
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,auto,3,4,Low,High,Chrysler Imperial
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,manual,4,1,High,Low,Fiat 128
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,manual,4,2,High,Low,Honda Civic
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,manual,4,1,High,Low,Toyota Corolla
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,Straight,auto,3,1,Medium,Medium,Toyota Corona
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,Vshaped,auto,3,2,Low,Medium,Dodge Challenger
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,Vshaped,auto,3,2,Low,Medium,AMC Javelin
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,auto,3,4,Low,High,Camaro Z28
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,auto,3,2,Medium,High,Pontiac Firebird
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,manual,4,1,Medium,Low,Fiat X1-9
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,Vshaped,manual,5,2,Medium,Medium,Porsche 914-2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,manual,5,2,High,Medium,Lotus Europa
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,Vshaped,manual,5,4,Low,VeryHigh,Ford Pantera L
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,Vshaped,manual,5,6,Medium,High,Ferrari Dino
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,Vshaped,manual,5,8,Low,VeryHigh,Maserati Bora
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,Straight,manual,4,2,Medium,Medium,Volvo 142E

In [44]:
mtcars[~mtcars['gear'].isin([4, 5])]
# cars other gears values in 4,5 : ~ opposite

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,car_name
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,Medium,Medium,Hornet 4 Drive
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,Medium,High,Hornet Sportabout
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,Straight,auto,3,1,Medium,Medium,Valiant
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,auto,3,4,Low,High,Duster 360
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,auto,3,3,Low,High,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,auto,3,3,Medium,High,Merc 450SL
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,auto,3,3,Low,High,Merc 450SLC
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,auto,3,4,Low,High,Cadillac Fleetwood
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,auto,3,4,Low,High,Lincoln Continental
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,auto,3,4,Low,High,Chrysler Imperial
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,Straight,auto,3,1,Medium,Medium,Toyota Corona
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,Vshaped,auto,3,2,Low,Medium,Dodge Challenger
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,Vshaped,auto,3,2,Low,Medium,AMC Javelin
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,auto,3,4,Low,High,Camaro Z28
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,auto,3,2,Medium,High,Pontiac Firebird

### select dtypes

In [45]:
mtcars.dtypes

mpg           float64
cyl          category
disp          float64
hp              int64
drat          float64
wt            float64
qsec          float64
vs           category
am           category
gear         category
carb         category
mpg_level    category
hp_level     category
car_name          str
dtype: object

In [46]:
mtcars.select_dtypes(include='number') #.head
# list columns which are numeric

                      mpg   disp   hp  drat     wt   qsec
Mazda RX4            21.0  160.0  110  3.90  2.620  16.46
Mazda RX4 Wag        21.0  160.0  110  3.90  2.875  17.02
Datsun 710           22.8  108.0   93  3.85  2.320  18.61
Hornet 4 Drive       21.4  258.0  110  3.08  3.215  19.44
Hornet Sportabout    18.7  360.0  175  3.15  3.440  17.02
Valiant              18.1  225.0  105  2.76  3.460  20.22
Duster 360           14.3  360.0  245  3.21  3.570  15.84
Merc 240D            24.4  146.7   62  3.69  3.190  20.00
Merc 230             22.8  140.8   95  3.92  3.150  22.90
Merc 280             19.2  167.6  123  3.92  3.440  18.30
Merc 280C            17.8  167.6  123  3.92  3.440  18.90
Merc 450SE           16.4  275.8  180  3.07  4.070  17.40
Merc 450SL           17.3  275.8  180  3.07  3.730  17.60
Merc 450SLC          15.2  275.8  180  3.07  3.780  18.00
Cadillac Fleetwood   10.4  472.0  205  2.93  5.250  17.98
Lincoln Continental  10.4  460.0  215  3.00  5.424  17.82
Chrysler Imperial    14.7  440.0  230  3.23  5.345  17.42
Fiat 128             32.4   78.7   66  4.08  2.200  19.47
Honda Civic          30.4   75.7   52  4.93  1.615  18.52
Toyota Corolla       33.9   71.1   65  4.22  1.835  19.90
Toyota Corona        21.5  120.1   97  3.70  2.465  20.01
Dodge Challenger     15.5  318.0  150  2.76  3.520  16.87
AMC Javelin          15.2  304.0  150  3.15  3.435  17.30
Camaro Z28           13.3  350.0  245  3.73  3.840  15.41
Pontiac Firebird     19.2  400.0  175  3.08  3.845  17.05
Fiat X1-9            27.3   79.0   66  4.08  1.935  18.90
Porsche 914-2        26.0  120.3   91  4.43  2.140  16.70
Lotus Europa         30.4   95.1  113  3.77  1.513  16.90
Ford Pantera L       15.8  351.0  264  4.22  3.170  14.50
Ferrari Dino         19.7  145.0  175  3.62  2.770  15.50
Maserati Bora        15.0  301.0  335  3.54  3.570  14.60
Volvo 142E           21.4  121.0  109  4.11  2.780  18.60

In [47]:
mtcars.select_dtypes(include='category').head()
# list columns which category type

                  cyl        vs      am gear carb mpg_level hp_level
Mazda RX4           6   Vshaped  manual    4    4    Medium   Medium
Mazda RX4 Wag       6   Vshaped  manual    4    4    Medium   Medium
Datsun 710          4  Straight  manual    4    1    Medium   Medium
Hornet 4 Drive      6  Straight    auto    3    1    Medium   Medium
Hornet Sportabout   8   Vshaped    auto    3    2    Medium     High

In [48]:
mtcars.select_dtypes(include=['object','str']).head()
# string, car names

                            car_name
Mazda RX4                  Mazda RX4
Mazda RX4 Wag          Mazda RX4 Wag
Datsun 710                Datsun 710
Hornet 4 Drive        Hornet 4 Drive
Hornet Sportabout  Hornet Sportabout

### nlargest for a column

In [49]:
mtcars.nlargest(5, 'mpg')
# list cars which are among top 5 mpg

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,car_name
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,manual,4,1,High,Low,Toyota Corolla
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,manual,4,1,High,Low,Fiat 128
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,manual,4,2,High,Low,Honda Civic
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,manual,5,2,High,Medium,Lotus Europa
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,manual,4,1,Medium,Low,Fiat X1-9

In [50]:
mtcars.nsmallest(5, 'wt')

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,car_name
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,manual,5,2,High,Medium,Lotus Europa
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,manual,4,2,High,Low,Honda Civic
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,manual,4,1,High,Low,Toyota Corolla
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,manual,4,1,Medium,Low,Fiat X1-9
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,Vshaped,manual,5,2,Medium,Medium,Porsche 914-2

### sort values

In [51]:
#mtcars= mtcars.sort_values(by='mpg', ascending=True, inplace=False)
#mtcars.sort_values(by='mpg', ascending=True, inplace=True)

In [52]:
mtcars.sort_values(by='mpg', ascending=True, inplace=True) #.head()
# list mtcars by mpg, in increasing order

In [53]:
mtcars

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,car_name
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,auto,3,4,Low,High,Lincoln Continental
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,auto,3,4,Low,High,Cadillac Fleetwood
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,auto,3,4,Low,High,Camaro Z28
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,auto,3,4,Low,High,Duster 360
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,auto,3,4,Low,High,Chrysler Imperial
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,Vshaped,manual,5,8,Low,VeryHigh,Maserati Bora
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,Vshaped,auto,3,2,Low,Medium,AMC Javelin
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,auto,3,3,Low,High,Merc 450SLC
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,Vshaped,auto,3,2,Low,Medium,Dodge Challenger
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,Vshaped,manual,5,4,Low,VeryHigh,Ford Pantera L
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,auto,3,3,Low,High,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,auto,3,3,Medium,High,Merc 450SL
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,Straight,auto,4,4,Medium,Medium,Merc 280C
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,Straight,auto,3,1,Medium,Medium,Valiant
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,Medium,High,Hornet Sportabout
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,Straight,auto,4,4,Medium,Medium,Merc 280
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,auto,3,2,Medium,High,Pontiac Firebird
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,Vshaped,manual,5,6,Medium,High,Ferrari Dino
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,Medium,Medium,Mazda RX4 Wag
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,Medium,Medium,Mazda RX4
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,Straight,manual,4,2,Medium,Medium,Volvo 142E
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,Medium,Medium,Hornet 4 Drive
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,Straight,auto,3,1,Medium,Medium,Toyota Corona
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,Medium,Medium,Datsun 710
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,Straight,auto,4,2,Medium,Medium,Merc 230
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,Straight,auto,4,2,Medium,Low,Merc 240D
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,Vshaped,manual,5,2,Medium,Medium,Porsche 914-2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,manual,4,1,Medium,Low,Fiat X1-9
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,manual,4,2,High,Low,Honda Civic
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,manual,5,2,High,Medium,Lotus Europa
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,manual,4,1,High,Low,Fiat 128
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,manual,4,1,High,Low,Toyota Corolla

In [54]:
mtcars.sort_values(['gear','mpg']) #.head()  #first by gear, mpg

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,car_name
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,auto,3,4,Low,High,Lincoln Continental
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,auto,3,4,Low,High,Cadillac Fleetwood
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,auto,3,4,Low,High,Camaro Z28
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,auto,3,4,Low,High,Duster 360
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,auto,3,4,Low,High,Chrysler Imperial
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,Vshaped,auto,3,2,Low,Medium,AMC Javelin
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,auto,3,3,Low,High,Merc 450SLC
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,Vshaped,auto,3,2,Low,Medium,Dodge Challenger
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,auto,3,3,Low,High,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,auto,3,3,Medium,High,Merc 450SL
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,Straight,auto,3,1,Medium,Medium,Valiant
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,Medium,High,Hornet Sportabout
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,auto,3,2,Medium,High,Pontiac Firebird
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,Medium,Medium,Hornet 4 Drive
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,Straight,auto,3,1,Medium,Medium,Toyota Corona
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,Straight,auto,4,4,Medium,Medium,Merc 280C
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,Straight,auto,4,4,Medium,Medium,Merc 280
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,Medium,Medium,Mazda RX4 Wag
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,Medium,Medium,Mazda RX4
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,Straight,manual,4,2,Medium,Medium,Volvo 142E
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,Medium,Medium,Datsun 710
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,Straight,auto,4,2,Medium,Medium,Merc 230
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,Straight,auto,4,2,Medium,Low,Merc 240D
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,manual,4,1,Medium,Low,Fiat X1-9
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,manual,4,2,High,Low,Honda Civic
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,manual,4,1,High,Low,Fiat 128
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,manual,4,1,High,Low,Toyota Corolla
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,Vshaped,manual,5,8,Low,VeryHigh,Maserati Bora
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,Vshaped,manual,5,4,Low,VeryHigh,Ford Pantera L
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,Vshaped,manual,5,6,Medium,High,Ferrari Dino
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,Vshaped,manual,5,2,Medium,Medium,Porsche 914-2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,manual,5,2,High,Medium,Lotus Europa

In [55]:
mtcars.sort_values(['gear','mpg'], ascending=[False,True])#.head()  #first by gear, mpg

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,hp_level,car_name
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,Vshaped,manual,5,8,Low,VeryHigh,Maserati Bora
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,Vshaped,manual,5,4,Low,VeryHigh,Ford Pantera L
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,Vshaped,manual,5,6,Medium,High,Ferrari Dino
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,Vshaped,manual,5,2,Medium,Medium,Porsche 914-2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,manual,5,2,High,Medium,Lotus Europa
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,Straight,auto,4,4,Medium,Medium,Merc 280C
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,Straight,auto,4,4,Medium,Medium,Merc 280
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,Medium,Medium,Mazda RX4 Wag
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,Medium,Medium,Mazda RX4
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,Straight,manual,4,2,Medium,Medium,Volvo 142E
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,Medium,Medium,Datsun 710
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,Straight,auto,4,2,Medium,Medium,Merc 230
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,Straight,auto,4,2,Medium,Low,Merc 240D
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,manual,4,1,Medium,Low,Fiat X1-9
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,manual,4,2,High,Low,Honda Civic
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,manual,4,1,High,Low,Fiat 128
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,manual,4,1,High,Low,Toyota Corolla
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,auto,3,4,Low,High,Lincoln Continental
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,auto,3,4,Low,High,Cadillac Fleetwood
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,auto,3,4,Low,High,Camaro Z28
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,auto,3,4,Low,High,Duster 360
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,auto,3,4,Low,High,Chrysler Imperial
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,Vshaped,auto,3,2,Low,Medium,AMC Javelin
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,auto,3,3,Low,High,Merc 450SLC
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,Vshaped,auto,3,2,Low,Medium,Dodge Challenger
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,auto,3,3,Low,High,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,auto,3,3,Medium,High,Merc 450SL
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,Straight,auto,3,1,Medium,Medium,Valiant
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,Medium,High,Hornet Sportabout
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,auto,3,2,Medium,High,Pontiac Firebird
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,Medium,Medium,Hornet 4 Drive
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,Straight,auto,3,1,Medium,Medium,Toyota Corona

## Hold - 12 Apr 2026 - 18 Apr 2026

In [56]:
import pandas as pd
import numpy as np
from pydataset import data
mtcars = data('mtcars')
mtcars.shape

(32, 11)

### Pivot Table
- index= → What goes down the rows
- columns= → What goes across the top
- values= → What fills the table
- aggfunc= → How to summarize if there are duplicates

In [57]:
# how may cars have gear=5, am=0

In [58]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [59]:
mtcars.pivot_table(values = 'mpg', index='gear', observed=False)
# no aggregation or default aggregation ie mean
# Mean mpg of Gear 3 cars is 16

            mpg
gear
3     16.106667
4     24.533333
5     21.380000

In [60]:
mtcars.pivot_table(values = 'hp', index='cyl', observed=False)
# mean hp of Cyl-4 cars is 82

             hp
cyl
4     82.636364
6    122.285714
8    209.214286

In [61]:
mtcars.pivot_table(values = ['mpg','hp'], index=['gear','am'], observed=True, 
                   aggfunc=['sum','mean','count']).reset_index()
#sum of mpg for each gear type

  gear am   sum               mean            count
             hp    mpg          hp        mpg    hp mpg
0    3  0  2642  241.6  176.133333  16.106667    15  15
1    4  0   403   84.2  100.750000  21.050000     4   4
2    4  1   671  210.2   83.875000  26.275000     8   8
3    5  1   978  106.9  195.600000  21.380000     5   5

In [62]:
#?mtcars.pivot_table

In [63]:
pd.pivot_table( data=mtcars, observed=False,
    index='gear',          # Rows
    values='mpg',          # Values to summarize
    aggfunc='median'         # Aggregation function
)
# Median of Gear-3 cars is 15.5

       mpg
gear
3     15.5
4     22.8
5     19.7

In [64]:
pivot1 = pd.pivot_table(
    data=mtcars, observed=False,
    index='gear',          # Rows
    columns='am',          # Columns
    values='mpg',          # Values to summarize
    aggfunc='mean'         # Aggregation function
)

In [65]:
pivot1
# Mean of Gear-3 & Auto Tx - 16, while for Gear-3 & Manual Tx- No cars

am            0       1
gear
3     16.106667     NaN
4     21.050000  26.275
5           NaN  21.380

In [66]:
print(mtcars.am.value_counts(), mtcars.cyl.value_counts())

am
0    19
1    13
Name: count, dtype: int64 cyl
8    14
4    11
6     7
Name: count, dtype: int64

In [67]:
pd.pivot_table( observed=True , data= mtcars,  index='gear',  columns='am', \
                values='mpg',
                aggfunc=['mean', 'max', 'min' ,'count','sum']\
              )
# 32 cars

           mean           max         min       count         sum
am            0       1     0     1     0     1     0    1      0      1
gear
3     16.106667     NaN  21.5   NaN  10.4   NaN  15.0  NaN  241.6    NaN
4     21.050000  26.275  24.4  33.9  17.8  21.0   4.0  8.0   84.2  210.2
5           NaN  21.380   NaN  30.4   NaN  15.0   NaN  5.0    NaN  106.9

In [68]:
pd.pivot_table(data= mtcars,  index=['gear','am'],  columns='cyl',  values='mpg', \
                aggfunc=['mean', 'max', 'min' ,'count','sum','std'] ).reset_index()
#19.75 mean mpg - gear3, am0, cyl6

    gear am       mean                 max               min              \
cyl                  4      6      8     4     6     8     4     6     8
0      3  0  21.500000  19.75  15.05  21.5  21.4  19.2  21.5  18.1  10.4
1      4  0  23.600000  18.50    NaN  24.4  19.2   NaN  22.8  17.8   NaN
2      4  1  28.033333  21.00    NaN  33.9  21.0   NaN  21.4  21.0   NaN
3      5  1  28.200000  19.70  15.40  30.4  19.7  15.8  26.0  19.7  15.0

    count               sum                    std
cyl     4    6     8      4     6      8         4         6         8
0     1.0  2.0  12.0   21.5  39.5  180.6       NaN  2.333452  2.774396
1     2.0  2.0   NaN   47.2  37.0    NaN  1.131371  0.989949       NaN
2     6.0  2.0   NaN  168.2  42.0    NaN  5.118854  0.000000       NaN
3     2.0  1.0   2.0   56.4  19.7   30.8  3.111270       NaN  0.565685

In [69]:
pd.pivot_table(data=mtcars, index='cyl', columns='carb', values='hp', aggfunc=['min','max','count'])

        min                                       max                       \
carb      1      2      3      4      6      8      1      2      3      4
cyl
4      65.0   52.0    NaN    NaN    NaN    NaN   97.0  113.0    NaN    NaN
6     105.0    NaN    NaN  110.0  175.0    NaN  110.0    NaN    NaN  123.0
8       NaN  150.0  180.0  205.0    NaN  335.0    NaN  175.0  180.0  264.0

                   count
carb      6      8     1    2    3    4    6    8
cyl
4       NaN    NaN   5.0  6.0  NaN  NaN  NaN  NaN
6     175.0    NaN   2.0  NaN  NaN  4.0  1.0  NaN
8       NaN  335.0   NaN  4.0  3.0  6.0  NaN  1.0

##  Advanced - 2 : 19 Apr 2026
- wide, long
- missing values
- airquality dataset is perfect
    - Wide format: Columns for Ozone, Solar.R, Wind, Temp, Month, Day
    - Has missing values in Ozone and Solar.R → great for .isnull(), .fillna(), .dropna() practice
    - Can be melted into long format to have "variable" and "value" columns

In [70]:
#Create Data
data = [
    [1, 'Taheera', 70, 86],
    [2, 'Aelita', 56, 90],
    [3, 'Khulan', 87, 90],
    [4, 'Batgerel', 71, 79],
    [5, 'Manisha', 88, 76],
]

df = pd.DataFrame(data, columns=['Rollno','Name', 'Maths', 'English'])

The `pd.DataFrame()` function is a fundamental pandas constructor that creates a DataFrame object. Here's what it does:

1. Creates a two-dimensional, size-mutable, potentially heterogeneous tabular data structure with labeled axes (rows and columns).

2. Accepts various input types to create a DataFrame:
   - Lists or arrays (as shown in the example)
   - Dictionaries
   - Other DataFrames
   - NumPy arrays
   - CSV files and other data sources

3. Allows specification of column names through the `columns` parameter.

4. Provides a powerful data structure similar to a spreadsheet or SQL table where you can:
   - Access data by row, column, or cell
   - Perform operations on entire columns or rows
   - Filter, sort, and transform data
   - Handle missing values
   - Merge and join datasets

In the selected code, it's converting the raw list data into a structured table format that's optimized for data analysis.

In [71]:
df

   Rollno      Name  Maths  English
0       1   Taheera     70       86
1       2    Aelita     56       90
2       3    Khulan     87       90
3       4  Batgerel     71       79
4       5   Manisha     88       76

### Wide to Long Data
`Rollno, Name, Subject, Marks`

In [72]:
df_long = df.melt(id_vars=['Rollno','Name'], 
                 value_vars=['Maths','English'], 
                 var_name='Subject', 
                 value_name='Marks')
df_long

   Rollno      Name  Subject  Marks
0       1   Taheera    Maths     70
1       2    Aelita    Maths     56
2       3    Khulan    Maths     87
3       4  Batgerel    Maths     71
4       5   Manisha    Maths     88
5       1   Taheera  English     86
6       2    Aelita  English     90
7       3    Khulan  English     90
8       4  Batgerel  English     79
9       5   Manisha  English     76

In [73]:
wide_df = df_long.pivot(index=['Rollno','Name'], columns='Subject',
             values='Marks').reset_index(drop=False).rename_axis(None, axis=1)

wide_df

   Rollno      Name  English  Maths
0       1   Taheera       86     70
1       2    Aelita       90     56
2       3    Khulan       90     87
3       4  Batgerel       79     71
4       5   Manisha       76     88

In [74]:
wide_df2 = df_long.pivot_table(index=['Rollno','Name'], columns='Subject',
                               values='Marks', aggfunc='sum').reset_index(drop=False).rename_axis(None, axis=1)
wide_df2

   Rollno      Name  English  Maths
0       1   Taheera       86     70
1       2    Aelita       90     56
2       3    Khulan       90     87
3       4  Batgerel       79     71
4       5   Manisha       76     88

In the pandas library, both pivot() and pivot_table() are used to reshape data from a "long" format to a "wide" format, but they differ primarily in their ability to handle duplicate entries and aggregate data. 
Key Differences

    Aggregation:
        pivot(): Does not perform aggregation. It is strictly for reshaping data.
        pivot_table(): Can aggregate data using functions like sum, mean (default), or count. It is designed to summarize data.
    Handling Duplicates:
        pivot(): Will raise a ValueError if there are duplicate entries for a specific index/column combination.
        pivot_table(): Handles duplicates by applying an aggregation function to all values that share the same index and column labels.
    Performance:
        pivot(): Generally faster and more memory-efficient because it has a simpler internal logic without aggregation overhead.
        pivot_table(): Slightly slower due to the additional computational steps required for grouping and calculating aggregates. 

Comparison Table
Feature 	     pivot()	                      pivot_table()
Purpose:	     Simple reshaping	        Reshaping + Aggregation
Duplicates:	 Raises ValueError	       Aggregates them
Default Aggregation:  	None	                mean
Parameters:	index, columns, values    index, columns, values, aggfunc, fill_value, margins
Flexibility: Limited to unique pairs	 High (handles missing data, subtotals)  

When to Use Which?

    Use pivot() when your dataset is already "clean" and each index-column pair maps to exactly one value.
    Use pivot_table() if your data has multiple entries for the same categories (e.g., multiple sales records for the same store on the same day) and you need to see a summary like a total or average.

In [75]:
df_long

   Rollno      Name  Subject  Marks
0       1   Taheera    Maths     70
1       2    Aelita    Maths     56
2       3    Khulan    Maths     87
3       4  Batgerel    Maths     71
4       5   Manisha    Maths     88
5       1   Taheera  English     86
6       2    Aelita  English     90
7       3    Khulan  English     90
8       4  Batgerel  English     79
9       5   Manisha  English     76

In [76]:
df_long.groupby('Subject')['Marks'].agg(['sum', 'mean', 'count'])

         sum  mean  count
Subject
English  421  84.2      5
Maths    372  74.4      5

The selected code performs aggregation operations on a DataFrame grouped by subject. Here's a step-by-step explanation:

1. `df_long.groupby('Subject')` - This groups the DataFrame `df_long` by the values in the 'Subject' column, creating a GroupBy object.

2. `['Marks']` - This selects only the 'Marks' column from each group for the aggregation operations.

3. `.agg(['sum', 'mean', 'count'])` - This applies multiple aggregation functions to the grouped data:
   - `'sum'`: Calculates the total sum of marks for each subject
   - `'mean'`: Calculates the average marks for each subject
   - `'count'`: Counts the number of mark entries for each subject

The result will be a DataFrame with subjects as the index and three columns showing the sum, mean, and count of marks for each subject.

In [81]:
df[['Maths','English']].mean()

Maths      74.4
English    84.2
dtype: float64

In [82]:
df.dtypes

Rollno     int64
Name         str
Maths      int64
English    int64
dtype: object

In [79]:
df.select_dtypes(include='number').mean()

Rollno      3.0
Maths      74.4
English    84.2
dtype: float64

## Practice - 19  Apr

In [80]:
from pydataset import data
import pandas as pd

aq = data('airquality')
aq.head()

   Ozone  Solar.R  Wind  Temp  Month  Day
1   41.0    190.0   7.4    67      5    1
2   36.0    118.0   8.0    72      5    2
3   12.0    149.0  12.6    74      5    3
4   18.0    313.0  11.5    62      5    4
5    NaN      NaN  14.3    56      5    5

In [81]:
aq.info()   #153 rows, 6 cols

<class 'pandas.DataFrame'>
RangeIndex: 153 entries, 1 to 153
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Ozone    116 non-null    float64
 1   Solar.R  146 non-null    float64
 2   Wind     153 non-null    float64
 3   Temp     153 non-null    int64
 4   Month    153 non-null    int64
 5   Day      153 non-null    int64
dtypes: float64(3), int64(3)
memory usage: 7.3 KB

In [82]:
print(aq.isnull().sum())  # Shows missing values

Ozone      37
Solar.R     7
Wind        0
Temp        0
Month       0
Day         0
dtype: int64

In [83]:
aq.head()  #original data

   Ozone  Solar.R  Wind  Temp  Month  Day
1   41.0    190.0   7.4    67      5    1
2   36.0    118.0   8.0    72      5    2
3   12.0    149.0  12.6    74      5    3
4   18.0    313.0  11.5    62      5    4
5    NaN      NaN  14.3    56      5    5

In [84]:
# long
aq_long = aq.melt(  id_vars=['Month', 'Day'],  value_vars=['Ozone', 'Solar.R', 'Wind', 'Temp'], \
                     var_name='Measurement',    value_name='Value' )

aq_long.head()

   Month  Day Measurement  Value
0      5    1       Ozone   41.0
1      5    2       Ozone   36.0
2      5    3       Ozone   12.0
3      5    4       Ozone   18.0
4      5    5       Ozone    NaN

In [85]:
153 * 4

612

In [86]:
aq_long  # 153 rows x 4 columns

     Month  Day Measurement  Value
0        5    1       Ozone   41.0
1        5    2       Ozone   36.0
2        5    3       Ozone   12.0
3        5    4       Ozone   18.0
4        5    5       Ozone    NaN
..     ...  ...         ...    ...
607      9   26        Temp   70.0
608      9   27        Temp   77.0
609      9   28        Temp   75.0
610      9   29        Temp   76.0
611      9   30        Temp   68.0

[612 rows x 4 columns]

### Melt
- https://pandas.pydata.org/docs/reference/api/pandas.melt.html
-  id_vars=['Month', 'Day'],  value_vars=['Ozone', 'Solar.R', 'Wind', 'Temp'], \
                     var_name='Measurement',    value_name='Value' )

In [87]:
pd.melt(frame=aq, id_vars=['Month', 'Day'], value_vars=['Ozone', 'Wind'],\
        var_name='Measurement', value_name='value', col_level=None, ignore_index=True)

     Month  Day Measurement  value
0        5    1       Ozone   41.0
1        5    2       Ozone   36.0
2        5    3       Ozone   12.0
3        5    4       Ozone   18.0
4        5    5       Ozone    NaN
..     ...  ...         ...    ...
301      9   26        Wind    6.9
302      9   27        Wind   13.2
303      9   28        Wind   14.3
304      9   29        Wind    8.0
305      9   30        Wind   11.5

[306 rows x 4 columns]

In [88]:
aq_long.head()

   Month  Day Measurement  Value
0      5    1       Ozone   41.0
1      5    2       Ozone   36.0
2      5    3       Ozone   12.0
3      5    4       Ozone   18.0
4      5    5       Ozone    NaN

In [89]:
# wide
aq_wide = aq_long.pivot_table( index=['Month', 'Day'], columns='Measurement', values='Value' ).reset_index()
aq_wide.head(2)

Measurement  Month  Day  Ozone  Solar.R  Temp  Wind
0                5    1   41.0    190.0  67.0   7.4
1                5    2   36.0    118.0  72.0   8.0

In [90]:
aq.head(2)

   Ozone  Solar.R  Wind  Temp  Month  Day
1   41.0    190.0   7.4    67      5    1
2   36.0    118.0   8.0    72      5    2

## Missing Values

In [91]:
#Create Data
import numpy as np
data = [
    [1, 'Taheera', None, 86],
    [2, 'Aelita', 56, 90],
    [3, 'Khulan', np.nan, None],
    [4, 'Batgerel', 71, 79],
    [5, 'Manisha', np.nan, 76],
]

df = pd.DataFrame(data, columns=['Rollno','Name', 'Maths', 'English'])
df

   Rollno      Name  Maths  English
0       1   Taheera    NaN     86.0
1       2    Aelita   56.0     90.0
2       3    Khulan    NaN      NaN
3       4  Batgerel   71.0     79.0
4       5   Manisha    NaN     76.0

In [92]:
df.isna().sum()

Rollno     0
Name       0
Maths      3
English    1
dtype: int64

In [93]:
df.isna().sum(axis=1)

0    1
1    0
2    2
3    0
4    1
dtype: int64

In [94]:
#df.fillna(40)
df

   Rollno      Name  Maths  English
0       1   Taheera    NaN     86.0
1       2    Aelita   56.0     90.0
2       3    Khulan    NaN      NaN
3       4  Batgerel   71.0     79.0
4       5   Manisha    NaN     76.0

In [95]:
df['Maths'].mean()

np.float64(63.5)

In [96]:
df['Maths'] = df['Maths'].fillna(df['Maths'].mean())
df

   Rollno      Name  Maths  English
0       1   Taheera   63.5     86.0
1       2    Aelita   56.0     90.0
2       3    Khulan   63.5      NaN
3       4  Batgerel   71.0     79.0
4       5   Manisha   63.5     76.0

In [97]:
df['English'] = df['English'].fillna(df['English'].min())
df

   Rollno      Name  Maths  English
0       1   Taheera   63.5     86.0
1       2    Aelita   56.0     90.0
2       3    Khulan   63.5     76.0
3       4  Batgerel   71.0     79.0
4       5   Manisha   63.5     76.0

In [99]:
#df.loc[df['Rollno']==1,['Maths']] = 88
#df.loc[df['Rollno']==3,['Maths','English']] = [100,100]

In [103]:
df

   Rollno      Name  Maths  English
0       1   Taheera   63.5     86.0
1       2    Aelita   56.0     90.0
2       3    Khulan   63.5     76.0
3       4  Batgerel   71.0     79.0
4       5   Manisha   63.5     76.0

In [104]:
data2 = [
    [1, 'Taheera', 77],
    [2, 'Aelita', 77],
    [3, 'Khulan', 77],
    [4, 'Batgerel', 77],
    [5, 'Manisha', 77],
]

df2 = pd.DataFrame(data2, columns=['Rollno','Name', 'French'])
df2

   Rollno      Name  French
0       1   Taheera      77
1       2    Aelita      77
2       3    Khulan      77
3       4  Batgerel      77
4       5   Manisha      77

In [105]:
df

   Rollno      Name  Maths  English
0       1   Taheera   63.5     86.0
1       2    Aelita   56.0     90.0
2       3    Khulan   63.5     76.0
3       4  Batgerel   71.0     79.0
4       5   Manisha   63.5     76.0

In [106]:
df3 = pd.merge(df, df2, on=['Rollno','Name'])
df3

   Rollno      Name  Maths  English  French
0       1   Taheera   63.5     86.0      77
1       2    Aelita   56.0     90.0      77
2       3    Khulan   63.5     76.0      77
3       4  Batgerel   71.0     79.0      77
4       5   Manisha   63.5     76.0      77

## Class ending 19 Apr
- Create Data Frame
- Long to Wide, Wide to Long
- Group by Summary
- Missing Values - Insert, Find count of Missing Values, Imputing Value
- Merge 2 Data frame

In [107]:
# missing data
# Drop rows with any missing values
aq_drop = aq.dropna()

# Fill missing Ozone with mean
aq_fill = aq.copy()
aq_fill['Ozone'] = aq_fill['Ozone'].fillna(aq_fill['Ozone'].mean())  #fill missing values in Ozone only

In [108]:
aq_fill.head()  #ozone missing values filled

      Ozone  Solar.R  Wind  Temp  Month  Day
1  41.00000    190.0   7.4    67      5    1
2  36.00000    118.0   8.0    72      5    2
3  12.00000    149.0  12.6    74      5    3
4  18.00000    313.0  11.5    62      5    4
5  42.12931      NaN  14.3    56      5    5

## Practise with Student Data
- https://docs.google.com/spreadsheets/d/1jPk4sZyDn5NSIQ4iQK1P3aGh5ZAS2oaYexRoUyocAw0
- sheet_id = '1ABCDefGhIJklMNopQRstuVWxyz12345678'
- gid1 = 'pData1'
- gid2 = 'sData1'
- url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid}"
- df = pd.read_csv(url)

In [22]:
sheet_id = '1jPk4sZyDn5NSIQ4iQK1P3aGh5ZAS2oaYexRoUyocAw0'
gid1 = '132995188' #pData1
gid2 = '330609257' #'sData1

In [23]:
url1 = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid1}"
print(url1)

https://docs.google.com/spreadsheets/d/1jPk4sZyDn5NSIQ4iQK1P3aGh5ZAS2oaYexRoUyocAw0/export?format=csv&gid=132995188

In [24]:
url2 = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid2}"
print(url2)

https://docs.google.com/spreadsheets/d/1jPk4sZyDn5NSIQ4iQK1P3aGh5ZAS2oaYexRoUyocAw0/export?format=csv&gid=330609257

In [25]:
#url1 = "https://docs.google.com/spreadsheets/d/1jPk4sZyDn5NSIQ4iQK1P3aGh5ZAS2oaYexRoUyocAw0/export?format=csv&gid=132995188"
pdata = pd.read_csv(url1)

In [26]:
pdata.head()

   rollno      name  gender         dob  height program
0       1  Jugurtha    Male  2000-08-16     156     BCA
1       2  Amandeep  Female  2000-02-21     170     BBA
2       3    Barkat  Female  2001-07-17     158     BCA
3       4    Suroor  Female  2001-11-16     188     BBA
4       5   Sultana    Male  2001-04-02     167     BCA

In [27]:
sdata = pd.read_csv(url2)
sdata.head()

   rollno  maths  english  stats  python
0       1    NaN      NaN   63.0    40.0
1       2   83.0     47.0   63.0    50.0
2       3   90.0     56.0   47.0    74.0
3       4   74.0     72.0   98.0     NaN
4       5   81.0     78.0    NaN    80.0

In [28]:
## Join Data
#https://pandas.pydata.org/docs/reference/api/pandas.merge.html
#how{‘left’, ‘right’, ‘outer’, ‘inner’, ‘cross’}, default ‘inner’
merged = pd.merge(left=pdata, right=sdata, on='rollno' , how = 'inner')
merged.head()

,rollno,name,gender,dob,height,program,maths,english,stats,python
0,1,Jugurtha,Male,2000-08-16,156,BCA,NaN,NaN,63.0,40.0
1,2,Amandeep,Female,2000-02-21,170,BBA,83.0,47.0,63.0,50.0
2,3,Barkat,Female,2001-07-17,158,BCA,90.0,56.0,47.0,74.0
3,4,Suroor,Female,2001-11-16,188,BBA,74.0,72.0,98.0,NaN
4,5,Sultana,Male,2001-04-02,167,BCA,81.0,78.0,NaN,80.0

In [29]:
merged.shape

(30, 10)

In [30]:
## Melt data -  Wide to Long
subvar = ['maths','english', 'stats','python']
idvar = ['rollno','name','gender','program']
marks_long = merged.melt( id_vars = idvar, value_vars =  subvar, var_name='subject', value_name ='marks')

In [31]:
marks_long.head()

   rollno      name  gender program subject  marks
0       1  Jugurtha    Male     BCA   maths    NaN
1       2  Amandeep  Female     BBA   maths   83.0
2       3    Barkat  Female     BCA   maths   90.0
3       4    Suroor  Female     BBA   maths   74.0
4       5   Sultana    Male     BCA   maths   81.0

In [32]:
# Long to Wide 
marks_wide = marks_long.pivot_table( index=idvar, columns = "subject", values= "marks").reset_index()
# first - first observation per group

In [33]:
marks_wide.head()

subject  rollno      name  gender program  english  maths  python  stats
0             1  Jugurtha    Male     BCA      NaN    NaN    40.0   63.0
1             2  Amandeep  Female     BBA     47.0   83.0    50.0   63.0
2             3    Barkat  Female     BCA     56.0   90.0    74.0   47.0
3             4    Suroor  Female     BBA     72.0   74.0     NaN   98.0
4             5   Sultana    Male     BCA     78.0   81.0    80.0    NaN

In [34]:
## Missing Data
missing_summary = merged.isnull().sum()
missing_summary

rollno     0
name       0
gender     2
dob        0
height     0
program    0
maths      4
english    3
stats      5
python     2
dtype: int64

In [35]:
merged

,rollno,name,gender,dob,height,program,maths,english,stats,python
0,1,Jugurtha,Male,2000-08-16,156,BCA,NaN,NaN,63.0,40.0
1,2,Amandeep,Female,2000-02-21,170,BBA,83.0,47.0,63.0,50.0
2,3,Barkat,Female,2001-07-17,158,BCA,90.0,56.0,47.0,74.0
3,4,Suroor,Female,2001-11-16,188,BBA,74.0,72.0,98.0,NaN
4,5,Sultana,Male,2001-04-02,167,BCA,81.0,78.0,NaN,80.0
5,6,Sajjad,Male,2000-10-12,153,BCA,67.0,46.0,48.0,47.0
6,7,Sharan,Male,2000-07-28,174,BBA,51.0,73.0,72.0,87.0
7,8,Djedjiga,Female,2000-06-27,163,BCA,94.0,62.0,63.0,76.0
8,9,Bijata,Female,2002-05-14,158,BBA,74.0,83.0,79.0,61.0
9,10,Mahadi,Female,2000-03-06,175,BCA,66.0,74.0,40.0,74.0
10,11,Sundas,Male,2000-03-02,151,BCA,76.0,NaN,53.0,42.0
11,12,Mandal,Male,2000-07-10,169,BBA,40.0,44.0,65.0,94.0
12,13,Najmul,Female,2001-03-23,177,BCA,53.0,78.0,66.0,48.0
13,14,Deniz,Male,2001-04-21,156,BBA,54.0,54.0,65.0,81.0
14,15,Sharmin,Male,2002-10-31,157,BCA,99.0,52.0,90.0,71.0
15,16,Emran,Male,2000-02-24,184,BBA,78.0,88.0,NaN,NaN
16,17,Sundas,Male,2001-02-11,163,BBA,71.0,43.0,69.0,76.0
17,18,Tanzeel,Female,2002-05-09,166,BCA,NaN,78.0,84.0,54.0
18,19,Student_19,Male,2001-03-27,185,BCA,82.0,68.0,NaN,52.0
19,20,Student_20,Male,2002-07-08,189,BBA,71.0,46.0,98.0,90.0
20,21,Student_21,Female,2001-07-23,153,BCA,61.0,67.0,41.0,81.0
21,22,Student_22,Male,2000-01-14,151,BCA,84.0,96.0,92.0,45.0
22,23,Student_23,Male,2000-11-22,155,BCA,67.0,67.0,83.0,83.0
23,24,Student_24,NaN,2002-05-15,153,BBA,59.0,69.0,50.0,97.0
24,25,Student_25,Female,2001-11-27,178,BBA,94.0,67.0,NaN,78.0
25,26,Student_26,NaN,2001-07-23,167,BBA,NaN,40.0,96.0,66.0
26,27,Student_27,Male,2000-11-14,175,BBA,96.0,NaN,52.0,80.0
27,28,Student_28,Female,2001-03-16,183,BBA,NaN,78.0,NaN,47.0
28,29,Student_29,Female,2001-11-20,159,BBA,66.0,48.0,76.0,72.0
29,30,Student_30,Male,2000-07-28,185,BBA,90.0,81.0,83.0,63.0

In [36]:
merged2 = merged.copy()
merged2["gender"] = merged2["gender"].fillna("Not Specified")
merged2

,rollno,name,gender,dob,height,program,maths,english,stats,python
0,1,Jugurtha,Male,2000-08-16,156,BCA,NaN,NaN,63.0,40.0
1,2,Amandeep,Female,2000-02-21,170,BBA,83.0,47.0,63.0,50.0
2,3,Barkat,Female,2001-07-17,158,BCA,90.0,56.0,47.0,74.0
3,4,Suroor,Female,2001-11-16,188,BBA,74.0,72.0,98.0,NaN
4,5,Sultana,Male,2001-04-02,167,BCA,81.0,78.0,NaN,80.0
5,6,Sajjad,Male,2000-10-12,153,BCA,67.0,46.0,48.0,47.0
6,7,Sharan,Male,2000-07-28,174,BBA,51.0,73.0,72.0,87.0
7,8,Djedjiga,Female,2000-06-27,163,BCA,94.0,62.0,63.0,76.0
8,9,Bijata,Female,2002-05-14,158,BBA,74.0,83.0,79.0,61.0
9,10,Mahadi,Female,2000-03-06,175,BCA,66.0,74.0,40.0,74.0
10,11,Sundas,Male,2000-03-02,151,BCA,76.0,NaN,53.0,42.0
11,12,Mandal,Male,2000-07-10,169,BBA,40.0,44.0,65.0,94.0
12,13,Najmul,Female,2001-03-23,177,BCA,53.0,78.0,66.0,48.0
13,14,Deniz,Male,2001-04-21,156,BBA,54.0,54.0,65.0,81.0
14,15,Sharmin,Male,2002-10-31,157,BCA,99.0,52.0,90.0,71.0
15,16,Emran,Male,2000-02-24,184,BBA,78.0,88.0,NaN,NaN
16,17,Sundas,Male,2001-02-11,163,BBA,71.0,43.0,69.0,76.0
17,18,Tanzeel,Female,2002-05-09,166,BCA,NaN,78.0,84.0,54.0
18,19,Student_19,Male,2001-03-27,185,BCA,82.0,68.0,NaN,52.0
19,20,Student_20,Male,2002-07-08,189,BBA,71.0,46.0,98.0,90.0
20,21,Student_21,Female,2001-07-23,153,BCA,61.0,67.0,41.0,81.0
21,22,Student_22,Male,2000-01-14,151,BCA,84.0,96.0,92.0,45.0
22,23,Student_23,Male,2000-11-22,155,BCA,67.0,67.0,83.0,83.0
23,24,Student_24,Not Specified,2002-05-15,153,BBA,59.0,69.0,50.0,97.0
24,25,Student_25,Female,2001-11-27,178,BBA,94.0,67.0,NaN,78.0
25,26,Student_26,Not Specified,2001-07-23,167,BBA,NaN,40.0,96.0,66.0
26,27,Student_27,Male,2000-11-14,175,BBA,96.0,NaN,52.0,80.0
27,28,Student_28,Female,2001-03-16,183,BBA,NaN,78.0,NaN,47.0
28,29,Student_29,Female,2001-11-20,159,BBA,66.0,48.0,76.0,72.0
29,30,Student_30,Male,2000-07-28,185,BBA,90.0,81.0,83.0,63.0

In [37]:
subvar

['maths', 'english', 'stats', 'python']

In [38]:
merged2[subvar].mean()

maths      73.884615
english    65.000000
stats      69.440000
python     68.178571
dtype: float64

In [39]:
for s in subvar:
    merged2[s] = merged2[s].fillna(merged2[s].mean())
merged2.head()  #see changes in missing values of maths, english, stats, python

,rollno,name,gender,dob,height,program,maths,english,stats,python
0,1,Jugurtha,Male,2000-08-16,156,BCA,73.884615,65.0,63.00,40.000000
1,2,Amandeep,Female,2000-02-21,170,BBA,83.000000,47.0,63.00,50.000000
2,3,Barkat,Female,2001-07-17,158,BCA,90.000000,56.0,47.00,74.000000
3,4,Suroor,Female,2001-11-16,188,BBA,74.000000,72.0,98.00,68.178571
4,5,Sultana,Male,2001-04-02,167,BCA,81.000000,78.0,69.44,80.000000

### Missing Values
- Remove Rows or Columns

In [40]:
subvar

['maths', 'english', 'stats', 'python']

In [41]:
merged3R = merged.dropna(subset=subvar) #rows remove

In [42]:
merged3R.shape  #less rows now

(19, 10)

In [43]:
merged3R

,rollno,name,gender,dob,height,program,maths,english,stats,python
1,2,Amandeep,Female,2000-02-21,170,BBA,83.0,47.0,63.0,50.0
2,3,Barkat,Female,2001-07-17,158,BCA,90.0,56.0,47.0,74.0
5,6,Sajjad,Male,2000-10-12,153,BCA,67.0,46.0,48.0,47.0
6,7,Sharan,Male,2000-07-28,174,BBA,51.0,73.0,72.0,87.0
7,8,Djedjiga,Female,2000-06-27,163,BCA,94.0,62.0,63.0,76.0
8,9,Bijata,Female,2002-05-14,158,BBA,74.0,83.0,79.0,61.0
9,10,Mahadi,Female,2000-03-06,175,BCA,66.0,74.0,40.0,74.0
11,12,Mandal,Male,2000-07-10,169,BBA,40.0,44.0,65.0,94.0
12,13,Najmul,Female,2001-03-23,177,BCA,53.0,78.0,66.0,48.0
13,14,Deniz,Male,2001-04-21,156,BBA,54.0,54.0,65.0,81.0
14,15,Sharmin,Male,2002-10-31,157,BCA,99.0,52.0,90.0,71.0
16,17,Sundas,Male,2001-02-11,163,BBA,71.0,43.0,69.0,76.0
19,20,Student_20,Male,2002-07-08,189,BBA,71.0,46.0,98.0,90.0
20,21,Student_21,Female,2001-07-23,153,BCA,61.0,67.0,41.0,81.0
21,22,Student_22,Male,2000-01-14,151,BCA,84.0,96.0,92.0,45.0
22,23,Student_23,Male,2000-11-22,155,BCA,67.0,67.0,83.0,83.0
23,24,Student_24,NaN,2002-05-15,153,BBA,59.0,69.0,50.0,97.0
28,29,Student_29,Female,2001-11-20,159,BBA,66.0,48.0,76.0,72.0
29,30,Student_30,Male,2000-07-28,185,BBA,90.0,81.0,83.0,63.0

In [44]:
# Columns wise Missing %
merged.isnull().mean()

rollno     0.000000
name       0.000000
gender     0.066667
dob        0.000000
height     0.000000
program    0.000000
maths      0.133333
english    0.100000
stats      0.166667
python     0.066667
dtype: float64

In [45]:
threshold = 0.07  #remove columns which have missing values more than 30%
merged3C = merged.loc[:, merged.isnull().mean() <= threshold]

In [46]:
merged3C

    rollno        name  gender         dob  height program  python
0        1    Jugurtha    Male  2000-08-16     156     BCA    40.0
1        2    Amandeep  Female  2000-02-21     170     BBA    50.0
2        3      Barkat  Female  2001-07-17     158     BCA    74.0
3        4      Suroor  Female  2001-11-16     188     BBA     NaN
4        5     Sultana    Male  2001-04-02     167     BCA    80.0
5        6      Sajjad    Male  2000-10-12     153     BCA    47.0
6        7      Sharan    Male  2000-07-28     174     BBA    87.0
7        8    Djedjiga  Female  2000-06-27     163     BCA    76.0
8        9      Bijata  Female  2002-05-14     158     BBA    61.0
9       10      Mahadi  Female  2000-03-06     175     BCA    74.0
10      11      Sundas    Male  2000-03-02     151     BCA    42.0
11      12      Mandal    Male  2000-07-10     169     BBA    94.0
12      13      Najmul  Female  2001-03-23     177     BCA    48.0
13      14       Deniz    Male  2001-04-21     156     BBA    81.0
14      15     Sharmin    Male  2002-10-31     157     BCA    71.0
15      16       Emran    Male  2000-02-24     184     BBA     NaN
16      17      Sundas    Male  2001-02-11     163     BBA    76.0
17      18     Tanzeel  Female  2002-05-09     166     BCA    54.0
18      19  Student_19    Male  2001-03-27     185     BCA    52.0
19      20  Student_20    Male  2002-07-08     189     BBA    90.0
20      21  Student_21  Female  2001-07-23     153     BCA    81.0
21      22  Student_22    Male  2000-01-14     151     BCA    45.0
22      23  Student_23    Male  2000-11-22     155     BCA    83.0
23      24  Student_24     NaN  2002-05-15     153     BBA    97.0
24      25  Student_25  Female  2001-11-27     178     BBA    78.0
25      26  Student_26     NaN  2001-07-23     167     BBA    66.0
26      27  Student_27    Male  2000-11-14     175     BBA    80.0
27      28  Student_28  Female  2001-03-16     183     BBA    47.0
28      29  Student_29  Female  2001-11-20     159     BBA    72.0
29      30  Student_30    Male  2000-07-28     185     BBA    63.0

### Lambda Function
-

In [ ]:
merged.head()

In [ ]:
merged["maths"].apply( lambda x: x * 1.20 if pd.notnull(x) else x)

In [ ]:
merged.assign( englishU = lambda df: merged["english"] * 1.10 ).head()

## Dates
- pd.Timestamp(date.today()) → current date
- errors="coerce" → invalid dates become NaT (Not a Time) instead of crashing.
- Pandas auto-detects most formats (YYYY-MM-DD, DD/MM/YYYY, etc.), but you can force a format:
- Subtract DOB from today → 
- To calculate age in years, you need to divide the timedelta by a constant (e.g., 365.25 days) or use dateutil.relativedelta for an exact year/month calculation.

In [ ]:
import pandas as pd
from datetime import date
from dateutil.relativedelta import relativedelta

In [ ]:
merged.head()

In [ ]:
merged.dtypes

In [ ]:
merged['dob'] = pd.to_datetime(merged['dob'], errors="coerce")
# pd.to_datetime(merged['dob'], format="%Y-%m-%d")
merged.dtypes

In [ ]:
merged.head()

In [ ]:
today = pd.Timestamp(date.today())
today

In [ ]:
merged["age"] = (today - merged["dob"]).dt.days // 365 # // as to interpret division
merged.head()

In [ ]:
merged["ageYM"] = merged["dob"].apply (
    lambda dob: f"{relativedelta(date.today(), dob).years} years, {relativedelta(date.today(), dob).months} months"
    if pd.notnull(dob) else None
)
merged.head()

In [ ]:
# students whose bday comes in Sep
merged[merged["dob"].dt.month == 2]

## END HERE
- now practise aggregations, groupby,
- time series