In [1]:
import pandas as pd
from pydataset import data

In [2]:
mtcars_R = data('mtcars')
mtcars_R.head(3)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

In [3]:
import pandas as pd

# Load mtcars dataset directly from URL
url = "https://vincentarelbundock.github.io/Rdatasets/csv/datasets/mtcars.csv"
mtcars_python= pd.read_csv(url, index_col=0) # index_col=0 handles car names correctly

In [4]:
mtcars_python.head(3)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
rownames
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

In [5]:
print(mtcars_R.equals(mtcars_python))

True