### Pandas
- https://pandas.pydata.org/
- library or set of modules available for data manipulation

In [2]:
import pandas as pd  #pd is an alias for pandas
import numpy as np

In [3]:
#pd.

In [4]:
# Set Pandas options for wrapping
pd.set_option('display.max_columns', None)   # Show all columns
pd.set_option('display.width', 100)          # Set line width before wrapping
pd.set_option('display.max_colwidth', None)  # Don't truncate text

In [5]:
from pydataset import data  #load library of pydataset and import mtcars data from it
mtcars = data('mtcars')
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [6]:
type(mtcars)

pandas.DataFrame

In [7]:
#pd.Dat # after dot(.) press tab to get functions

In [8]:
#?pd.DataFrame.head

In [9]:
#help(pd.DataFrame.head)

In [10]:
mtcars.head(n=3)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

## Functions in Pandas
- Understanding Data
    - type  # type of object
    - shape # rows & cols in data
    - columns # column names
    - dtypes  # datatype 
    - info()  # datatypes & non-null counts
    - sample(x) # randon x rows
    - head(x) # first x rows
    - tail(x) # last x rows
- Summary Statistics
    - describe()  #summary stats for numeric cols
    - describe(include='all')  #summary stats for all cols
    - mtcars.nunique() #count of unique values per column
    - value_counts()  # freq count for a series
- Missing/Duplicates
    -  isnull().sum()   # missing value count per cols
    -  notnull().sum()  # non missing value count
    -  duplicated(().sum() # count of duplicate rows
- View Specific Col/ Row
    -  ['col_name']   # single column
    -  [['col1','col2']] # multiple columns
    -  iloc[0]   #1st row by index position
    -  loc[0] #1st row by label
    -  iloc[0:5]   # first 5 rows
-  Basic Data Insights
    -  corr(numeric_only=True)  #correlation matrix (numeric only)
    -  mean(numeric_only=True)   #mean of numeric cols
    -  mode().iloc(0) #most frequent values
    -  median(numeric_only=True) # median of numeric cols

In [11]:
type(mtcars)  #type of object

pandas.DataFrame

In [12]:
mtcars.head() #first 5 rows of mtcars data set  (which is impported from pydataset library)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [13]:
mtcars.tail(4) #Last 4 rows from mtcars dataset

                 mpg  cyl   disp   hp  drat    wt  qsec  vs  am  gear  carb
Ford Pantera L  15.8    8  351.0  264  4.22  3.17  14.5   0   1     5     4
Ferrari Dino    19.7    6  145.0  175  3.62  2.77  15.5   0   1     5     6
Maserati Bora   15.0    8  301.0  335  3.54  3.57  14.6   0   1     5     8
Volvo 142E      21.4    4  121.0  109  4.11  2.78  18.6   1   1     4     2

In [16]:
mtcars.sample(3)  #any 3 row on sampling / random

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Camaro Z28     13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
Valiant        18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4

In [17]:
mtcars.shape #rows , columns - structure

(32, 11)

In [18]:
mtcars.columns # title, names of columns

Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear',
       'carb'],
      dtype='str')

In [19]:
mtcars.info() # info about dataset, every col - non-null , data type; float -  decimal; int- without decimal; 64 - bit
#10020202020.222

<class 'pandas.DataFrame'>
Index: 32 entries, Mazda RX4 to Volvo 142E
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   mpg     32 non-null     float64
 1   cyl     32 non-null     int64
 2   disp    32 non-null     float64
 3   hp      32 non-null     int64
 4   drat    32 non-null     float64
 5   wt      32 non-null     float64
 6   qsec    32 non-null     float64
 7   vs      32 non-null     int64
 8   am      32 non-null     int64
 9   gear    32 non-null     int64
 10  carb    32 non-null     int64
dtypes: float64(5), int64(6)
memory usage: 3.4 KB

In [20]:
mtcars.dtypes #column names and types

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [21]:
mtcars.index

Index(['Mazda RX4', 'Mazda RX4 Wag', 'Datsun 710', 'Hornet 4 Drive',
       'Hornet Sportabout', 'Valiant', 'Duster 360', 'Merc 240D', 'Merc 230',
       'Merc 280', 'Merc 280C', 'Merc 450SE', 'Merc 450SL', 'Merc 450SLC',
       'Cadillac Fleetwood', 'Lincoln Continental', 'Chrysler Imperial',
       'Fiat 128', 'Honda Civic', 'Toyota Corolla', 'Toyota Corona',
       'Dodge Challenger', 'AMC Javelin', 'Camaro Z28', 'Pontiac Firebird',
       'Fiat X1-9', 'Porsche 914-2', 'Lotus Europa', 'Ford Pantera L',
       'Ferrari Dino', 'Maserati Bora', 'Volvo 142E'],
      dtype='str')

In [22]:
mtcars.head(2)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110   3.9  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110   3.9  2.875  17.02   0   1     4     4

## Summary

In [23]:
mtcars.describe() #for all numeric cols - count, min, max, mean, std dev, Q1, Q2, Q3

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [24]:
mtcars.mpg.describe()

count    32.000000
mean     20.090625
std       6.026948
min      10.400000
25%      15.425000
50%      19.200000
75%      22.800000
max      33.900000
Name: mpg, dtype: float64

In [25]:
mtcars['mpg'].describe()

count    32.000000
mean     20.090625
std       6.026948
min      10.400000
25%      15.425000
50%      19.200000
75%      22.800000
max      33.900000
Name: mpg, dtype: float64

In [24]:
mtcars.describe(include='all')  #for all types of columns

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [26]:
mtcars.cyl.value_counts() # count of each cyl type cars

cyl
8    14
4    11
6     7
Name: count, dtype: int64

In [27]:
mtcars.nunique()   # count of unique values in each col(number of unique)

mpg     25
cyl      3
disp    27
hp      22
drat    22
wt      29
qsec    30
vs       2
am       2
gear     3
carb     6
dtype: int64

In [28]:
mtcars['gear'].value_counts()

gear
3    15
4    12
5     5
Name: count, dtype: int64

In [29]:
mtcars['am'].value_counts()  #by tx

am
0    19
1    13
Name: count, dtype: int64

## Read/ Write - CSV/ EXCEL
-

## Read/write to CSV

In [30]:
mtcars.to_csv('mtcarsdata.csv', index=False)

In [33]:
mtcars2 = pd.read_csv('mtcarsdata.csv')
mtcars2.info()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   mpg     32 non-null     float64
 1   cyl     32 non-null     int64
 2   disp    32 non-null     float64
 3   hp      32 non-null     int64
 4   drat    32 non-null     float64
 5   wt      32 non-null     float64
 6   qsec    32 non-null     float64
 7   vs      32 non-null     int64
 8   am      32 non-null     int64
 9   gear    32 non-null     int64
 10  carb    32 non-null     int64
dtypes: float64(5), int64(6)
memory usage: 2.9 KB

## read/write to Excel
- https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_excel.html

In [34]:
#?mtcars.to_excel

In [35]:
mtcars.to_excel('mtcarsdata2.xlsx', index=False)
# index - rownames get stored if index -T

In [36]:
mtcars3 = pd.read_excel('mtcarsdata2.xlsx', sheet_name=0)
mtcars3.head(5)

    mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [ ]:
#mtcars.to_excel('mtcarsdata2.xlsx', index=True) - same mtcars.to_excel('mtcarsdata2.xlsx')

## Missing
- df.isnull() - missing values
- https://pandas.pydata.org/docs/reference/api/pandas.isnull.html
- df.notnull()  - not null values

In [37]:
mtcars.shape  #rows, cols

(32, 11)

In [38]:
mtcars.isnull()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,False,False,False,False,False,False,False,False,False,False,False
Mazda RX4 Wag,False,False,False,False,False,False,False,False,False,False,False
Datsun 710,False,False,False,False,False,False,False,False,False,False,False
Hornet 4 Drive,False,False,False,False,False,False,False,False,False,False,False
Hornet Sportabout,False,False,False,False,False,False,False,False,False,False,False
Valiant,False,False,False,False,False,False,False,False,False,False,False
Duster 360,False,False,False,False,False,False,False,False,False,False,False
Merc 240D,False,False,False,False,False,False,False,False,False,False,False
Merc 230,False,False,False,False,False,False,False,False,False,False,False
Merc 280,False,False,False,False,False,False,False,False,False,False,False
Merc 280C,False,False,False,False,False,False,False,False,False,False,False
Merc 450SE,False,False,False,False,False,False,False,False,False,False,False
Merc 450SL,False,False,False,False,False,False,False,False,False,False,False
Merc 450SLC,False,False,False,False,False,False,False,False,False,False,False
Cadillac Fleetwood,False,False,False,False,False,False,False,False,False,False,False
Lincoln Continental,False,False,False,False,False,False,False,False,False,False,False
Chrysler Imperial,False,False,False,False,False,False,False,False,False,False,False
Fiat 128,False,False,False,False,False,False,False,False,False,False,False
Honda Civic,False,False,False,False,False,False,False,False,False,False,False
Toyota Corolla,False,False,False,False,False,False,False,False,False,False,False
Toyota Corona,False,False,False,False,False,False,False,False,False,False,False
Dodge Challenger,False,False,False,False,False,False,False,False,False,False,False
AMC Javelin,False,False,False,False,False,False,False,False,False,False,False
Camaro Z28,False,False,False,False,False,False,False,False,False,False,False
Pontiac Firebird,False,False,False,False,False,False,False,False,False,False,False
Fiat X1-9,False,False,False,False,False,False,False,False,False,False,False
Porsche 914-2,False,False,False,False,False,False,False,False,False,False,False
Lotus Europa,False,False,False,False,False,False,False,False,False,False,False
Ford Pantera L,False,False,False,False,False,False,False,False,False,False,False
Ferrari Dino,False,False,False,False,False,False,False,False,False,False,False
Maserati Bora,False,False,False,False,False,False,False,False,False,False,False
Volvo 142E,False,False,False,False,False,False,False,False,False,False,False

In [39]:
mtcars.isnull().sum()

mpg     0
cyl     0
disp    0
hp      0
drat    0
wt      0
qsec    0
vs      0
am      0
gear    0
carb    0
dtype: int64

In [40]:
mtcars.isnull().sum().sum() # missing values in full Data Frame

np.int64(0)

The selected code mtcars.isnull().sum().sum() counts the total number of missing values in the entire mtcars DataFrame. Here's a step-by-step explanation:

1. mtcars.isnull() - Creates a DataFrame of the same shape as mtcars, with boolean values indicating whether each value is null (True) or not (False).

2. .sum() - When applied to the boolean DataFrame, it counts the number of True values (missing values) in each column, returning a Series.

3. .sum() - The second sum aggregates the Series values to give the total count of missing values across all columns in the DataFrame.

This is a quick way to check how many missing values exist in your entire dataset.

In [41]:
mtcars.isnull().head()  # False -> 0, True - 1

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,False,False,False,False,False,False,False,False,False,False,False
Mazda RX4 Wag,False,False,False,False,False,False,False,False,False,False,False
Datsun 710,False,False,False,False,False,False,False,False,False,False,False
Hornet 4 Drive,False,False,False,False,False,False,False,False,False,False,False
Hornet Sportabout,False,False,False,False,False,False,False,False,False,False,False

In [42]:
mtcars.isnull().sum(axis=0)  #counting missing values, columns wise, axis=0 (Columns)

mpg     0
cyl     0
disp    0
hp      0
drat    0
wt      0
qsec    0
vs      0
am      0
gear    0
carb    0
dtype: int64

There is no functional difference between mtcars.isnull().sum(axis=0) and mtcars.isnull().sum() in Pandas. Both calculate the total number of missing values for each column (column-wise sum) because axis=0 is the default behavior for the sum function.

In [43]:
mtcars.isnull().sum(axis=1)  # count missing values, rowwise , axis=1 (Rows)

Mazda RX4              0
Mazda RX4 Wag          0
Datsun 710             0
Hornet 4 Drive         0
Hornet Sportabout      0
Valiant                0
Duster 360             0
Merc 240D              0
Merc 230               0
Merc 280               0
Merc 280C              0
Merc 450SE             0
Merc 450SL             0
Merc 450SLC            0
Cadillac Fleetwood     0
Lincoln Continental    0
Chrysler Imperial      0
Fiat 128               0
Honda Civic            0
Toyota Corolla         0
Toyota Corona          0
Dodge Challenger       0
AMC Javelin            0
Camaro Z28             0
Pontiac Firebird       0
Fiat X1-9              0
Porsche 914-2          0
Lotus Europa           0
Ford Pantera L         0
Ferrari Dino           0
Maserati Bora          0
Volvo 142E             0
dtype: int64

In [44]:
mtcars.notnull()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,True,True,True,True,True,True,True,True,True,True,True
Mazda RX4 Wag,True,True,True,True,True,True,True,True,True,True,True
Datsun 710,True,True,True,True,True,True,True,True,True,True,True
Hornet 4 Drive,True,True,True,True,True,True,True,True,True,True,True
Hornet Sportabout,True,True,True,True,True,True,True,True,True,True,True
Valiant,True,True,True,True,True,True,True,True,True,True,True
Duster 360,True,True,True,True,True,True,True,True,True,True,True
Merc 240D,True,True,True,True,True,True,True,True,True,True,True
Merc 230,True,True,True,True,True,True,True,True,True,True,True
Merc 280,True,True,True,True,True,True,True,True,True,True,True
Merc 280C,True,True,True,True,True,True,True,True,True,True,True
Merc 450SE,True,True,True,True,True,True,True,True,True,True,True
Merc 450SL,True,True,True,True,True,True,True,True,True,True,True
Merc 450SLC,True,True,True,True,True,True,True,True,True,True,True
Cadillac Fleetwood,True,True,True,True,True,True,True,True,True,True,True
Lincoln Continental,True,True,True,True,True,True,True,True,True,True,True
Chrysler Imperial,True,True,True,True,True,True,True,True,True,True,True
Fiat 128,True,True,True,True,True,True,True,True,True,True,True
Honda Civic,True,True,True,True,True,True,True,True,True,True,True
Toyota Corolla,True,True,True,True,True,True,True,True,True,True,True
Toyota Corona,True,True,True,True,True,True,True,True,True,True,True
Dodge Challenger,True,True,True,True,True,True,True,True,True,True,True
AMC Javelin,True,True,True,True,True,True,True,True,True,True,True
Camaro Z28,True,True,True,True,True,True,True,True,True,True,True
Pontiac Firebird,True,True,True,True,True,True,True,True,True,True,True
Fiat X1-9,True,True,True,True,True,True,True,True,True,True,True
Porsche 914-2,True,True,True,True,True,True,True,True,True,True,True
Lotus Europa,True,True,True,True,True,True,True,True,True,True,True
Ford Pantera L,True,True,True,True,True,True,True,True,True,True,True
Ferrari Dino,True,True,True,True,True,True,True,True,True,True,True
Maserati Bora,True,True,True,True,True,True,True,True,True,True,True
Volvo 142E,True,True,True,True,True,True,True,True,True,True,True

In [45]:
# Opposite of isnull or notnull
mtcars.notnull().sum(axis=0) # for each column, count non-missing values, 32

mpg     32
cyl     32
disp    32
hp      32
drat    32
wt      32
qsec    32
vs      32
am      32
gear    32
carb    32
dtype: int64

In [46]:
mtcars.notnull()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,True,True,True,True,True,True,True,True,True,True,True
Mazda RX4 Wag,True,True,True,True,True,True,True,True,True,True,True
Datsun 710,True,True,True,True,True,True,True,True,True,True,True
Hornet 4 Drive,True,True,True,True,True,True,True,True,True,True,True
Hornet Sportabout,True,True,True,True,True,True,True,True,True,True,True
Valiant,True,True,True,True,True,True,True,True,True,True,True
Duster 360,True,True,True,True,True,True,True,True,True,True,True
Merc 240D,True,True,True,True,True,True,True,True,True,True,True
Merc 230,True,True,True,True,True,True,True,True,True,True,True
Merc 280,True,True,True,True,True,True,True,True,True,True,True
Merc 280C,True,True,True,True,True,True,True,True,True,True,True
Merc 450SE,True,True,True,True,True,True,True,True,True,True,True
Merc 450SL,True,True,True,True,True,True,True,True,True,True,True
Merc 450SLC,True,True,True,True,True,True,True,True,True,True,True
Cadillac Fleetwood,True,True,True,True,True,True,True,True,True,True,True
Lincoln Continental,True,True,True,True,True,True,True,True,True,True,True
Chrysler Imperial,True,True,True,True,True,True,True,True,True,True,True
Fiat 128,True,True,True,True,True,True,True,True,True,True,True
Honda Civic,True,True,True,True,True,True,True,True,True,True,True
Toyota Corolla,True,True,True,True,True,True,True,True,True,True,True
Toyota Corona,True,True,True,True,True,True,True,True,True,True,True
Dodge Challenger,True,True,True,True,True,True,True,True,True,True,True
AMC Javelin,True,True,True,True,True,True,True,True,True,True,True
Camaro Z28,True,True,True,True,True,True,True,True,True,True,True
Pontiac Firebird,True,True,True,True,True,True,True,True,True,True,True
Fiat X1-9,True,True,True,True,True,True,True,True,True,True,True
Porsche 914-2,True,True,True,True,True,True,True,True,True,True,True
Lotus Europa,True,True,True,True,True,True,True,True,True,True,True
Ford Pantera L,True,True,True,True,True,True,True,True,True,True,True
Ferrari Dino,True,True,True,True,True,True,True,True,True,True,True
Maserati Bora,True,True,True,True,True,True,True,True,True,True,True
Volvo 142E,True,True,True,True,True,True,True,True,True,True,True

In [47]:
mtcars.notnull().sum(axis=1)  # for each row, count of non-missing values, 11

Mazda RX4              11
Mazda RX4 Wag          11
Datsun 710             11
Hornet 4 Drive         11
Hornet Sportabout      11
Valiant                11
Duster 360             11
Merc 240D              11
Merc 230               11
Merc 280               11
Merc 280C              11
Merc 450SE             11
Merc 450SL             11
Merc 450SLC            11
Cadillac Fleetwood     11
Lincoln Continental    11
Chrysler Imperial      11
Fiat 128               11
Honda Civic            11
Toyota Corolla         11
Toyota Corona          11
Dodge Challenger       11
AMC Javelin            11
Camaro Z28             11
Pontiac Firebird       11
Fiat X1-9              11
Porsche 914-2          11
Lotus Europa           11
Ford Pantera L         11
Ferrari Dino           11
Maserati Bora          11
Volvo 142E             11
dtype: int64

In [48]:
32 * 11

352

In [49]:
mtcars.notnull().sum(axis=0).sum()

np.int64(352)

In [50]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [51]:
mtcars.max(axis=0)

mpg      33.900
cyl       8.000
disp    472.000
hp      335.000
drat      4.930
wt        5.424
qsec     22.900
vs        1.000
am        1.000
gear      5.000
carb      8.000
dtype: float64

In [52]:
mtcars.notnull().sum(axis=0).sum() # 32 x 11

np.int64(352)

# Check for Duplicates
- duplicated()  #check for duplicate rows
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop_duplicates.html

In [53]:
#?mtcars.duplicated
mtcars = data('mtcars')
mtcars.head(2)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110   3.9  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110   3.9  2.875  17.02   0   1     4     4

In [54]:
mtcars2 = mtcars.copy().reset_index().rename(columns={'index':'car'})  #duplicate, reset_index (rownames to column by index), rename by index to car
mtcars2.head()

,car,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [55]:
mtcars2.shape   #car - 12

(32, 12)

### simulate duplicate rows

In [56]:
mtcars2['car'] == 'Mazda RX4'

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
Name: car, dtype: bool

In [57]:
mtcars2[mtcars2['car'] == 'Mazda RX4']  #all cars with name of Mazda RX4

         car   mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
0  Mazda RX4  21.0    6  160.0  110   3.9  2.62  16.46   0   1     4     4

In [59]:
mazda2 = mtcars2[mtcars2['car'] == 'Mazda RX4']
datson2 = mtcars2[mtcars2['car'] == 'Datsun 710']
# copied mazda and datson car in variable/ row

In [60]:
mtcars_dup = pd.concat([mtcars2, mazda2, datson2, mazda2], ignore_index=True) # 2 more cars Mazda, 1 more car for Datson
mtcars_dup #.sort_values('car')

,car,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
32,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
33,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
34,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4

In [61]:
mtcars_dup.shape

(35, 12)

In [62]:
mtcars_dup[mtcars_dup['car'] == 'Mazda RX4']
#duplicate cars - 3 cars of Mazda RX4

          car   mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
0   Mazda RX4  21.0    6  160.0  110   3.9  2.62  16.46   0   1     4     4
32  Mazda RX4  21.0    6  160.0  110   3.9  2.62  16.46   0   1     4     4
34  Mazda RX4  21.0    6  160.0  110   3.9  2.62  16.46   0   1     4     4

In [63]:
mtcars_dup[mtcars_dup['car'] == 'Datsun 710']

           car   mpg  cyl   disp  hp  drat    wt   qsec  vs  am  gear  carb
2   Datsun 710  22.8    4  108.0  93  3.85  2.32  18.61   1   1     4     1
33  Datsun 710  22.8    4  108.0  93  3.85  2.32  18.61   1   1     4     1

In [70]:
mtcars_dup.duplicated() # keep = True

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32     True
33     True
34     True
dtype: bool

In [71]:
mtcars_dup.duplicated().sum()  #duplicate rows - 3

np.int64(3)

In [72]:
mtcars['gear'].value_counts()

gear
3    15
4    12
5     5
Name: count, dtype: int64

In [73]:
mtcars_dup['gear'].value_counts()

gear
4    15
3    15
5     5
Name: count, dtype: int64

In [74]:
mtcars_dup.duplicated(subset = ['gear'])

0     False
1      True
2      True
3     False
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26    False
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
dtype: bool

In [75]:
mtcars_dup.duplicated(subset = ['gear']).sum()

np.int64(32)

In [69]:
mtcars_dup.duplicated(keep=False)  #mark all duplicates

0      True
1     False
2      True
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32     True
33     True
34     True
dtype: bool

In [71]:
mtcars_dup.duplicated(keep=False).sum()

np.int64(5)

The pandas duplicated() method identifies duplicate rows in a DataFrame. The primary difference lies in which rows are flagged as True: duplicated() (defaulting to keep='first') marks only subsequent occurrences, while duplicated(keep=False) marks all occurrences of a duplicate, including the first

In [74]:
#mtcars_dup.drop_duplicates()

,car,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [80]:
mtcars_dup.drop_duplicates

<bound method DataFrame.drop_duplicates of                     car   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1
32            Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1
33           Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1
34            Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1

    gear  carb
0      4     4
1      4     4
2      4     1
3      3     1
4      3     2
5      3     1
6      3     4
7      4     2
8      4     2
9      4     4
10     4     4
11     3     3
12     3     3
13     3     3
14     3     4
15     3     4
16     3     4
17     4     1
18     4     2
19     4     1
20     3     1
21     3     2
22     3     2
23     3     4
24     3     2
25     4     1
26     5     2
27     5     2
28     5     4
29     5     6
30     5     8
31     4     2
32     4     4
33     4     1
34     4     4  >

In [89]:
mtcars_dup

,car,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
32,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
33,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
34,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4

In [88]:
mtcars_dup.drop_duplicates(keep='first')  #first

,car,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [90]:
mtcars_dup.drop_duplicates(keep='last')

,car,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
33,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
34,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4

In [91]:
mtcars_dup.drop_duplicates(keep=False)  #remove duplicates

,car,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [94]:
mtcars_dup

,car,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
32,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
33,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
34,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4

In [92]:
mtcars_dup.duplicated(subset = ['vs','am','gear','carb'])

0     False
1      True
2     False
3     False
4     False
5      True
6     False
7     False
8      True
9     False
10     True
11    False
12     True
13     True
14     True
15     True
16     True
17     True
18    False
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26    False
27    False
28    False
29    False
30    False
31     True
32     True
33     True
34     True
dtype: bool

In [80]:
mtcars_dup[mtcars_dup.duplicated(subset = ['vs','am','gear','carb'])].sort_values(['vs','am','gear','carb'])

,car,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
32,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
34,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
33,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [81]:
mtcars[mtcars.duplicated(subset = ['gear','am','cyl','carb'], keep=False)].sort_values(by=['gear','am','cyl','carb'])
#keep=False marks all occurrences of duplicates, not just the later ones.

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2

In [82]:
mtcars_dup[~ mtcars_dup.duplicated(subset = ['gear','am','cyl','carb'], keep=False)].sort_values(by=['gear','am','cyl','carb'])
# non duplicates wrt column in subjset

,car,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8

In [83]:
mtcars_dup.drop_duplicates(subset = ['gear','am','cyl','carb'], inplace=False)
#remove duplicates by selected columns

,car,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8

### View rows/ columns

In [91]:
mtcars['mpg'].tail()

Lotus Europa      30.4
Ford Pantera L    15.8
Ferrari Dino      19.7
Maserati Bora     15.0
Volvo 142E        21.4
Name: mpg, dtype: float64

In [92]:
mtcars.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear',
       'carb'],
      dtype='str')

In [93]:
mtcars[['wt','mpg']].tail()

                   wt   mpg
Lotus Europa    1.513  30.4
Ford Pantera L  3.170  15.8
Ferrari Dino    2.770  19.7
Maserati Bora   3.570  15.0
Volvo 142E      2.780  21.4

In [94]:
mtcars

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In Pandas, loc and iloc are the primary methods for selecting data from a DataFrame. The fundamental difference is 
that loc is label-based while iloc is integer-position-based.

In [96]:
mtcars.iloc[0] #1st row

mpg      21.00
cyl       6.00
disp    160.00
hp      110.00
drat      3.90
wt        2.62
qsec     16.46
vs        0.00
am        1.00
gear      4.00
carb      4.00
Name: Mazda RX4, dtype: float64

In [97]:
mtcars.iloc[3:5]  #3rd to 5th row, all columns

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [99]:
mtcars.iloc[[0,4]]  #index position

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.62,16.46,0,1,4,4
Hornet Sportabout,18.7,8,360.0,175,3.15,3.44,17.02,0,0,3,2

In [101]:
mtcars.iloc[0,4] # 0th row and 4th column intersection value

np.float64(3.9)

In [102]:
mtcars.iloc[0:4]  # range of index position,   x:y  : from x to y-1

                 mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4       21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710      22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1

In [103]:
mtcars.head(5)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [104]:
mtcars.loc['Datsun 710']  #row by rowname

mpg      22.80
cyl       4.00
disp    108.00
hp       93.00
drat      3.85
wt        2.32
qsec     18.61
vs        1.00
am        1.00
gear      4.00
carb      1.00
Name: Datsun 710, dtype: float64

In [105]:
carlist = ['Mazda RX4','Datsun 710']
#mtcars.loc[['Mazda RX4','Datsun 710']] #row by rowname
mtcars.loc[carlist]

             mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
Mazda RX4   21.0    6  160.0  110  3.90  2.62  16.46   0   1     4     4
Datsun 710  22.8    4  108.0   93  3.85  2.32  18.61   1   1     4     1

In [106]:
mtcars.iloc[[0,2]]

             mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
Mazda RX4   21.0    6  160.0  110  3.90  2.62  16.46   0   1     4     4
Datsun 710  22.8    4  108.0   93  3.85  2.32  18.61   1   1     4     1

In [107]:
print(mtcars.iloc[0,2])
mtcars

160.0

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [108]:
mtcars.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear',
       'carb'],
      dtype='str')

In [109]:
mtcars.loc[:, 'mpg':'wt'].head()  # from mpg to wt columns by name

                    mpg  cyl   disp   hp  drat     wt
Mazda RX4          21.0    6  160.0  110  3.90  2.620
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875
Datsun 710         22.8    4  108.0   93  3.85  2.320
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440

In [110]:
mandalCarList = ['Mazda RX4','Datsun 710', 'Hornet 4 Drive']  #list of cars
print(mandalCarList)
mtcars.loc[mandalCarList, 'mpg':'wt'].head()  # row by names, col by names

['Mazda RX4', 'Datsun 710', 'Hornet 4 Drive']

                 mpg  cyl   disp   hp  drat     wt
Mazda RX4       21.0    6  160.0  110  3.90  2.620
Datsun 710      22.8    4  108.0   93  3.85  2.320
Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215

In [141]:
mtcars.loc[['Mazda RX4','Datsun 710', 'Hornet 4 Drive'], 'mpg':'wt'].head()

                 mpg  cyl   disp   hp  drat     wt
Mazda RX4       21.0    6  160.0  110  3.90  2.620
Datsun 710      22.8    4  108.0   93  3.85  2.320
Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215

In [111]:
mtcars.index

Index(['Mazda RX4', 'Mazda RX4 Wag', 'Datsun 710', 'Hornet 4 Drive',
       'Hornet Sportabout', 'Valiant', 'Duster 360', 'Merc 240D', 'Merc 230',
       'Merc 280', 'Merc 280C', 'Merc 450SE', 'Merc 450SL', 'Merc 450SLC',
       'Cadillac Fleetwood', 'Lincoln Continental', 'Chrysler Imperial',
       'Fiat 128', 'Honda Civic', 'Toyota Corolla', 'Toyota Corona',
       'Dodge Challenger', 'AMC Javelin', 'Camaro Z28', 'Pontiac Firebird',
       'Fiat X1-9', 'Porsche 914-2', 'Lotus Europa', 'Ford Pantera L',
       'Ferrari Dino', 'Maserati Bora', 'Volvo 142E'],
      dtype='str')

In [113]:
mtcars.iloc[:,3:8].head()

                    hp  drat     wt   qsec  vs
Mazda RX4          110  3.90  2.620  16.46   0
Mazda RX4 Wag      110  3.90  2.875  17.02   0
Datsun 710          93  3.85  2.320  18.61   1
Hornet 4 Drive     110  3.08  3.215  19.44   1
Hornet Sportabout  175  3.15  3.440  17.02   0

In [144]:
mtcars.iloc[1:10, [3,6,9,10]] #.head()  #4th, 7th, 10th, 11th col

                    hp   qsec  gear  carb
Mazda RX4 Wag      110  17.02     4     4
Datsun 710          93  18.61     4     1
Hornet 4 Drive     110  19.44     3     1
Hornet Sportabout  175  17.02     3     2
Valiant            105  20.22     3     1
Duster 360         245  15.84     3     4
Merc 240D           62  20.00     4     2
Merc 230            95  22.90     4     2
Merc 280           123  18.30     4     4

In [145]:
mtcars.iloc[0:3, [3,6,9,10]]

                hp   qsec  gear  carb
Mazda RX4      110  16.46     4     4
Mazda RX4 Wag  110  17.02     4     4
Datsun 710      93  18.61     4     1

In [147]:
mtcars.iloc[[0,4,31], [3,6,9,10]].head()  #4th, 7th, 10th, 11th col with 1st, 5th, 32th row

                    hp   qsec  gear  carb
Mazda RX4          110  16.46     4     4
Hornet Sportabout  175  17.02     3     2
Volvo 142E         109  18.60     4     2

In [148]:
mtcars.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear',
       'carb'],
      dtype='str')

## Summmary
- iloc - locating an item by index
- missing value - isnull, notnull
- duplicate - locating, remove
- Read/ Write to CSV, Excel  : df.to_csv, pd.read_csv  . excel
- filter specific columns or rows
- items in columns - concate - rows
- shape, head, tail, columns, str, help, ?
- import data from pydataset
- range

## END HERE
- Go To Advanced
- Mandal & Suroor - help students with GitHub, Anaconda, *
- Asssignment, Task