In [6]:
import pandas as pd
from pydataset import data

In [7]:
mtcars = data('mtcars')
mtcars.head(3)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

In [3]:
import pandas as pd

# Load mtcars dataset directly from URL
url = "https://vincentarelbundock.github.io/Rdatasets/csv/datasets/mtcars.csv"
mtcars_python= pd.read_csv(url, index_col=0) # index_col=0 handles car names correctly

In [4]:
mtcars_python.head(3)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
rownames
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

In [5]:
print(mtcars.equals(mtcars_python))

True

In [6]:
type(mtcars)

pandas.DataFrame

In [7]:
mtcars.shape

(32, 11)

In [8]:
mtcars.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear',
       'carb'],
      dtype='str')

In [9]:
mtcars.dtypes

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [10]:
mtcars.info()

<class 'pandas.DataFrame'>
Index: 32 entries, Mazda RX4 to Volvo 142E
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   mpg     32 non-null     float64
 1   cyl     32 non-null     int64
 2   disp    32 non-null     float64
 3   hp      32 non-null     int64
 4   drat    32 non-null     float64
 5   wt      32 non-null     float64
 6   qsec    32 non-null     float64
 7   vs      32 non-null     int64
 8   am      32 non-null     int64
 9   gear    32 non-null     int64
 10  carb    32 non-null     int64
dtypes: float64(5), int64(6)
memory usage: 3.4 KB

In [11]:
mtcars.sample(2)

                 mpg  cyl   disp  hp  drat     wt  qsec  vs  am  gear  carb
Porsche 914-2   26.0    4  120.3  91  4.43  2.140  16.7   0   1     5     2
Toyota Corolla  33.9    4   71.1  65  4.22  1.835  19.9   1   1     4     1

In [12]:
mtcars.head(4)

                 mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4       21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710      22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1

In [13]:
mtcars.tail(5)

                 mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  carb
Lotus Europa    30.4    4   95.1  113  3.77  1.513  16.9   1   1     5     2
Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5     4
Ferrari Dino    19.7    6  145.0  175  3.62  2.770  15.5   0   1     5     6
Maserati Bora   15.0    8  301.0  335  3.54  3.570  14.6   0   1     5     8
Volvo 142E      21.4    4  121.0  109  4.11  2.780  18.6   1   1     4     2

In [14]:
mtcars.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [15]:
mtcars.describe(include='all')

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [16]:
mtcars.nunique() # returns the count of unique items

mpg     25
cyl      3
disp    27
hp      22
drat    22
wt      29
qsec    30
vs       2
am       2
gear     3
carb     6
dtype: int64

In [17]:
mtcars['cyl'].value_counts()

cyl
8    14
4    11
6     7
Name: count, dtype: int64

In [18]:
mtcars['gear'].value_counts()

gear
3    15
4    12
5     5
Name: count, dtype: int64

In [19]:
mtcars.to_csv('mtcarsdata.csv', index =False)

In [20]:
mtcars2 = pd.read_csv('mtcarsdata.csv')
mtcars2.head()

    mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [8]:
mtcars2 = mtcars.copy().reset_index().rename(columns={'index':'car'})  #duplicate, reset_index (rownames to column by index), rename by index to car
mtcars2.head()

,car,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [9]:
mtcars2['car'] == 'Mazda RX4'

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
Name: car, dtype: bool

In [10]:
mtcars2[mtcars2['car'] == 'Mazda RX4']  #all cars with name of Mazda RX4

         car   mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
0  Mazda RX4  21.0    6  160.0  110   3.9  2.62  16.46   0   1     4     4

In [12]:
mazda2 = mtcars2[mtcars2['car'] == 'Mazda RX4']
datson2 = mtcars2[mtcars2['car'] == 'Datsun 710']
datson2

          car   mpg  cyl   disp  hp  drat    wt   qsec  vs  am  gear  carb
2  Datsun 710  22.8    4  108.0  93  3.85  2.32  18.61   1   1     4     1

In [13]:
mazda2

         car   mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
0  Mazda RX4  21.0    6  160.0  110   3.9  2.62  16.46   0   1     4     4

In [16]:
mtcars_dup = pd.concat([mtcars2, mazda2, datson2, mazda2], ignore_index=True) # 2 more cars Mazda, 1 more car for Datson

In [18]:
mtcars_dup.sort_values('car')
mtcars_dup

,car,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
32,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
33,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
34,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4

In [19]:
mtcars_dup.duplicated().sum()  #duplicate rows - 3

np.int64(3)

In [20]:
mtcars_dup.duplicated(subset = ['gear']).sum()

np.int64(32)

In [25]:
mtcars_dup['gear'].value_counts()

gear
4    15
3    15
5     5
Name: count, dtype: int64

In [26]:
mtcars_dup.duplicated(keep=False)  #mark all duplicates

0      True
1     False
2      True
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32     True
33     True
34     True
dtype: bool

In [31]:
import pandas as pd
# Assuming mtcars is already loaded as a pandas DataFrame
subset = mtcars.iloc[:, [0, 2, 5]]                
print(subset.head())

                    mpg   disp     wt
Mazda RX4          21.0  160.0  2.620
Mazda RX4 Wag      21.0  160.0  2.875
Datsun 710         22.8  108.0  2.320
Hornet 4 Drive     21.4  258.0  3.215
Hornet Sportabout  18.7  360.0  3.440

In [32]:
import pandas as pd
# Assuming mtcars is already loaded
mtcars.reset_index(inplace=True)

# View result
print(mtcars.head())

               index   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3

   carb
0     4
1     4
2     1
3     1
4     2

In [36]:
mtcars.iloc[:,:3]

                  index   mpg  cyl
0             Mazda RX4  21.0    6
1         Mazda RX4 Wag  21.0    6
2            Datsun 710  22.8    4
3        Hornet 4 Drive  21.4    6
4     Hornet Sportabout  18.7    8
5               Valiant  18.1    6
6            Duster 360  14.3    8
7             Merc 240D  24.4    4
8              Merc 230  22.8    4
9              Merc 280  19.2    6
10            Merc 280C  17.8    6
11           Merc 450SE  16.4    8
12           Merc 450SL  17.3    8
13          Merc 450SLC  15.2    8
14   Cadillac Fleetwood  10.4    8
15  Lincoln Continental  10.4    8
16    Chrysler Imperial  14.7    8
17             Fiat 128  32.4    4
18          Honda Civic  30.4    4
19       Toyota Corolla  33.9    4
20        Toyota Corona  21.5    4
21     Dodge Challenger  15.5    8
22          AMC Javelin  15.2    8
23           Camaro Z28  13.3    8
24     Pontiac Firebird  19.2    8
25            Fiat X1-9  27.3    4
26        Porsche 914-2  26.0    4
27         Lotus Europa  30.4    4
28       Ford Pantera L  15.8    8
29         Ferrari Dino  19.7    6
30        Maserati Bora  15.0    8
31           Volvo 142E  21.4    4