# Assignment - PY/02
- Lambda Functions

In [1]:
import pandas as pd
from pydataset import data

# Load mtcars dataset
df = data('mtcars')

In [2]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

### 4.1 Add Two Columns
- Create a new column mpg_hp_sum = mpg + hp using a lambda function.

In [3]:
df["mpg_hp_sum"] = df.apply(lambda x: x["mpg"] + x["hp"], axis=1)
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_hp_sum
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,131.0
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,131.0
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,115.8
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,131.4
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,193.7

### 4.2 Conditional Label
- Create a new column mpg_label:
	•	"High" if mpg > 20
	•	"Low" otherwise
- Use apply() with a lambda.

In [4]:
df["mpg_label"] = df.apply(lambda x: "High" if x["mpg"] > 20 else "Low", axis=1)
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_hp_sum,mpg_label
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,131.0,High
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,131.0,High
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,115.8,High
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,131.4,High
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,193.7,Low

### 4.3 Multiply Column Values
- Double all hp values using map() with a lambda.

In [5]:
df["hp_double"] = df.apply(lambda x: x["mpg"] * 2, axis=1)
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_hp_sum,mpg_label,hp_double
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,131.0,High,42.0
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,131.0,High,42.0
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,115.8,High,45.6
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,131.4,High,42.8
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,193.7,Low,37.4

### 4.4 Filter Rows
- Get a list of all mpg values greater than 25 using filter() with a lambda.

In [6]:
mpg_over_25 = list(filter(lambda x: x > 25, df["mpg"]))
mpg_over_25

[32.4, 30.4, 33.9, 27.3, 26.0, 30.4]

### 4.5 Reduce to Total
- Use reduce() with a lambda to sum all cyl values in the dataset.

In [7]:
from functools import reduce
cyl_sum = reduce(lambda x, y: x + y, df["cyl"])
cyl_sum

198

### 4.6 Sort by Custom Rule
- Sort the dataset by the reverse of the car names’ length using sorted() with a lambda on the index.

In [8]:
# Sort the index labels by length in reverse order
sorted_index = sorted(df.index, key=lambda x: len(str(x)), reverse=True)
print(list(sorted_index))

# Reorder the DataFrame using the sorted index list
df_sorted = df.reindex(sorted_index)
df_sorted.head()

['Lincoln Continental', 'Cadillac Fleetwood', 'Hornet Sportabout', 'Chrysler Imperial', 'Dodge Challenger', 'Pontiac Firebird', 'Hornet 4 Drive', 'Toyota Corolla', 'Ford Pantera L', 'Mazda RX4 Wag', 'Toyota Corona', 'Porsche 914-2', 'Maserati Bora', 'Lotus Europa', 'Ferrari Dino', 'Merc 450SLC', 'Honda Civic', 'AMC Javelin', 'Datsun 710', 'Duster 360', 'Merc 450SE', 'Merc 450SL', 'Camaro Z28', 'Volvo 142E', 'Mazda RX4', 'Merc 240D', 'Merc 280C', 'Fiat X1-9', 'Merc 230', 'Merc 280', 'Fiat 128', 'Valiant']

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_hp_sum,mpg_label,hp_double
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,225.4,Low,20.8
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,215.4,Low,20.8
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,193.7,Low,37.4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,244.7,Low,29.4
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,165.5,Low,31.0

### 4.7 Multi-Column Condition
- Create a column efficient_power = "Yes" if mpg > 20 and hp > 100, else "No".|

In [9]:
df["efficient_power"] = df.apply(
    lambda x: "Yes" if x["mpg"] > 20 and x["hp"] > 100 else "No", axis=1)
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_hp_sum,mpg_label,hp_double,efficient_power
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,131.0,High,42.0,Yes
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,131.0,High,42.0,Yes
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,115.8,High,45.6,No
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,131.4,High,42.8,Yes
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,193.7,Low,37.4,No

### 4.8 Normalize a Column
- Normalize mpg between 0 and 1 using a lambda inside apply():
- {normalized} = (x - min)/(max - min)

In [10]:
mpg_min = df["mpg"].min()
mpg_max = df["mpg"].max()

df["mpg_normalized"] = df["mpg"].apply(
    lambda x: (x - mpg_min) / (mpg_max - mpg_min))
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_hp_sum,mpg_label,hp_double,efficient_power,mpg_normalized
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,131.0,High,42.0,Yes,0.451064
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,131.0,High,42.0,Yes,0.451064
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,115.8,High,45.6,No,0.527660
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,131.4,High,42.8,Yes,0.468085
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,193.7,Low,37.4,No,0.353191

### 4.9 Extract First Word
- Extract the first word from each car name (index) into a new column car_make using map() with a lambda.

In [11]:
# Extract the first word from the car name index
df['car_make'] = df.index.map(lambda x: str(x).split()[0])

# View the result
print(df[['car_make']].head())

                  car_make
Mazda RX4            Mazda
Mazda RX4 Wag        Mazda
Datsun 710          Datsun
Hornet 4 Drive      Hornet
Hornet Sportabout   Hornet

### 4.10 Square and Add
- Create a column hp_mpg_calc = (hp² + mpg²) using apply() with a lambda.

In [12]:
df['hp_mpg_calc'] = df.apply(lambda row: row['hp']**2 + row['mpg']**2, axis=1)
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_hp_sum,mpg_label,hp_double,efficient_power,mpg_normalized,car_make,hp_mpg_calc
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,131.0,High,42.0,Yes,0.451064,Mazda,12541.00
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,131.0,High,42.0,Yes,0.451064,Mazda,12541.00
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,115.8,High,45.6,No,0.527660,Datsun,9168.84
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,131.4,High,42.8,Yes,0.468085,Hornet,12557.96
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,193.7,Low,37.4,No,0.353191,Hornet,30974.69

### 4.11 Filter by Col values
- Filter cars with mpg > 25.

In [13]:
# The lambda 'x' represents the entire DataFrame being filtered
high_mpg_cars = df.loc[lambda x: x['mpg'] > 25]
high_mpg_cars

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_hp_sum,mpg_label,hp_double,efficient_power,mpg_normalized,car_make,hp_mpg_calc
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,98.4,High,64.8,No,0.936170,Fiat,5405.76
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,82.4,High,60.8,No,0.851064,Honda,3628.16
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,98.9,High,67.8,No,1.000000,Toyota,5374.21
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,93.3,High,54.6,No,0.719149,Fiat,5101.29
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,117.0,High,52.0,No,0.663830,Porsche,8957.00
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,143.4,High,60.8,Yes,0.851064,Lotus,13693.16

### 4.12 Filter and soted carnames by horsepower
- From above return a list of car names sorted by horsepower.

In [14]:
# Extract car names (index) into a list, sorted by horsepower using a lambda key
sorted_cars = sorted(high_mpg_cars.index, key=lambda x: high_mpg_cars.loc[x, 'hp'])
sorted_cars

['Honda Civic',
 'Toyota Corolla',
 'Fiat 128',
 'Fiat X1-9',
 'Porsche 914-2',
 'Lotus Europa']

# End Here
- docs - 1nWPAH4oD_DNP9lfJXtrlrgufld4YwYoJHVoNUtWZGS4