### Write the queries for the following
1. List the names of analysts and salesmen.
2. List details of employees who have joined before 30 Sep 81.
3. List names of employees who are not managers.
4. List the names of employees whose employee numbers are 7369, 7521, 7839, 7934, 7788.
5. List employees not belonging to department 30, 40, or 10.
6. List employee names for those who have joined between 30 June and 31 Dec. ‘81.
7. List the different designations in the company.
8. List the names of employees who are not eligible for commission.
9. List the name and designation of the employee who does not report to anybody.
10. List the employees not assigned to any department.
11. List the employees who are eligible for commission.
12. List employees whose names either start or end with “S”.
13. List names of employees whose names have “i” as the second character.
14. List the number of employees working with the company.
15. List the number of designations available in the EMP table.
16. List the total salaries paid to the employees.
17. List the maximum, minimum and average salary in the company.
18. List the maximum salary paid to a salesman.

In [1]:
# SQL - PYTHON Connect

In [2]:
from sqlalchemy import create_engine, text
import pymysql
import pandas as pd
import os

In [3]:
# URL-encode special chars in password if any (e.g., # -> %23, @ -> %40)  #Pass@123 - Pass%40123
engine1 = create_engine("mysql+pymysql://root:piit2026@localhost:3306/piit")
# URL-encode special chars in password if any (e.g., # -> %23, @ -> %40)  #Pass@123 - Pass%40123
#engine1 = create_engine("mysql+pymysql://root:piit2026@localhost:3306/piit")
print(engine1)
#setting up connection mysql with user name - piuser, pwd - piit2026 and to database piit at port no  3306

Engine(mysql+pymysql://root:***@localhost:3306/piit)

In [4]:
# function to run the query with parameters or query
def q(sql, **params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

In [5]:
emp = q("SELECT * FROM emp")
emp

    empno   ename        job     mgr    hiredate     sal    comm  deptno
0    1234  DHIRAJ    ANALYST  7839.0  1988-12-17  5000.0   100.0      10
1    7369   SMITH      CLERK  7902.0  1980-12-17   800.0     NaN      20
2    7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0      30
3    7521    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0      30
4    7566   JONES    MANAGER  7839.0  1981-04-02  2975.0     NaN      20
5    7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0      30
6    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     NaN      30
7    7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0     NaN      10
8    7788   SCOTT    ANALYST  7566.0  1987-04-19  3000.0     NaN      20
9    7839    KING  PRESIDENT     NaN  1981-11-17  5000.0     NaN      10
10   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0      30
11   7876   ADAMS      CLERK  7788.0  1987-05-23  1100.0     NaN      20
12   7900   JAMES      CLERK  7698.0  1981-12-03   950.0     NaN      30
13   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0     NaN      20
14   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0     NaN      10

In [10]:
dept = q("SELECT * FROM dept")
dept

   deptno       dname       loc
0      10  ACCOUNTING  NEW YORK
1      20    RESEARCH    DALLAS
2      30       SALES   CHICAGO
3      40  OPERATIONS    BOSTON

#### `1. List the names of analysts and salesmen.`

In [9]:
# MYSQL Query
q("SELECT ename, job FROM emp WHERE job in('ANALYST','SALESMAN')")

    ename       job
0  DHIRAJ   ANALYST
1   ALLEN  SALESMAN
2    WARD  SALESMAN
3  MARTIN  SALESMAN
4   SCOTT   ANALYST
5  TURNER  SALESMAN
6    FORD   ANALYST

In [7]:
# Equivalent pandas code
result = emp[emp['job'].isin(['ANALYST', 'SALESMAN'])][['ename', 'job']]
result

     ename       job
0   DHIRAJ   ANALYST
1     SHAN   ANALYST
3    ALLEN  SALESMAN
4     WARD  SALESMAN
6   MARTIN  SALESMAN
9    SCOTT   ANALYST
11  TURNER  SALESMAN
14    FORD   ANALYST

#### `2. List details of employees who have joined before 30 Sep 81.`

In [11]:
# MYSQL Query
q("SELECT * FROM emp where hiredate < '1981-09-30'")

   empno   ename       job   mgr    hiredate     sal    comm  deptno
0   7369   SMITH     CLERK  7902  1980-12-17   800.0     NaN      20
1   7499   ALLEN  SALESMAN  7698  1981-02-20  1600.0   300.0      30
2   7521    WARD  SALESMAN  7698  1981-02-22  1250.0   500.0      30
3   7566   JONES   MANAGER  7839  1981-04-02  2975.0     NaN      20
4   7654  MARTIN  SALESMAN  7698  1981-09-28  1250.0  1400.0      30
5   7698   BLAKE   MANAGER  7839  1981-05-01  2850.0     NaN      30
6   7782   CLARK   MANAGER  7839  1981-06-09  2450.0     NaN      10
7   7844  TURNER  SALESMAN  7698  1981-09-08  1500.0     0.0      30

In [12]:
## Equivalent pandas code
emp['hiredate'] = pd.to_datetime(emp['hiredate']) # Convert to datetime first
result = emp.loc[emp['hiredate'] < '1981-09-30']
result

    empno   ename       job     mgr   hiredate     sal    comm  deptno
1    7369   SMITH     CLERK  7902.0 1980-12-17   800.0     NaN      20
2    7499   ALLEN  SALESMAN  7698.0 1981-02-20  1600.0   300.0      30
3    7521    WARD  SALESMAN  7698.0 1981-02-22  1250.0   500.0      30
4    7566   JONES   MANAGER  7839.0 1981-04-02  2975.0     NaN      20
5    7654  MARTIN  SALESMAN  7698.0 1981-09-28  1250.0  1400.0      30
6    7698   BLAKE   MANAGER  7839.0 1981-05-01  2850.0     NaN      30
7    7782   CLARK   MANAGER  7839.0 1981-06-09  2450.0     NaN      10
10   7844  TURNER  SALESMAN  7698.0 1981-09-08  1500.0     0.0      30

#### `3. List names of employees who are not managers.`

In [13]:
# MYSQL Query
q("SELECT ename, job FROM emp WHERE job <> 'MANAGER'")

     ename        job
0   DHIRAJ    ANALYST
1    SMITH      CLERK
2    ALLEN   SALESMAN
3     WARD   SALESMAN
4   MARTIN   SALESMAN
5    SCOTT    ANALYST
6     KING  PRESIDENT
7   TURNER   SALESMAN
8    ADAMS      CLERK
9    JAMES      CLERK
10    FORD    ANALYST
11  MILLER      CLERK

In [14]:
## Equivalent pandas code
emp[emp['job'] != 'MANAGER'][['ename','job']]

     ename        job
0   DHIRAJ    ANALYST
1    SMITH      CLERK
2    ALLEN   SALESMAN
3     WARD   SALESMAN
5   MARTIN   SALESMAN
8    SCOTT    ANALYST
9     KING  PRESIDENT
10  TURNER   SALESMAN
11   ADAMS      CLERK
12   JAMES      CLERK
13    FORD    ANALYST
14  MILLER      CLERK

#### `4. List the names of employees whose employee numbers are 7369, 7521, 7839, 7934, 7788.`

In [15]:
# MYSQL Query
q("SELECT ename FROM emp WHERE empno in('7369', '7521', '7934', '7788')")

    ename
0   SMITH
1    WARD
2   SCOTT
3  MILLER

In [16]:
## Equivalent pandas code
emp[emp['empno'].isin([7369, 7521, 7934, 7788])] [['ename']]

     ename
1    SMITH
3     WARD
8    SCOTT
14  MILLER

#### `5. List employees not belonging to department 30, 40, or 10.`

In [17]:
# MYSQL Query
q("SELECT ename FROM emp WHERE deptno NOT IN (30,40,10)")

   ename
0  SMITH
1  JONES
2  SCOTT
3  ADAMS
4   FORD

In [18]:
# Equivalent pandas code
emp[~emp['deptno'].isin([30,40,10])][['ename']]

    ename
1   SMITH
4   JONES
8   SCOTT
11  ADAMS
13   FORD

#### 6.  `List employee names for those who have joined between 30 June and 31 Dec.'81`

In [19]:
# MYSQL Query
q("SELECT ename FROM emp WHERE hiredate between '1981-06-30' and '1981-12-31'")

    ename
0  MARTIN
1    KING
2  TURNER
3   JAMES
4    FORD

In [20]:
# Equivalent pandas code
start_date = '1981-06-30'
end_date = '1981-12-31'
emp[emp['hiredate'].between(start_date, end_date)][['ename']]

     ename
5   MARTIN
9     KING
10  TURNER
12   JAMES
13    FORD

#### 7.  `List the different designations in the company.`

In [21]:
# MYSQL Query
q("SELECT DISTINCT(job) AS designation FROM emp")

  designation
0     ANALYST
1       CLERK
2    SALESMAN
3     MANAGER
4   PRESIDENT

In [22]:
# Equivalent pandas code
emp[['job']].drop_duplicates().rename(columns={'job': 'designation'})

  designation
0     ANALYST
1       CLERK
2    SALESMAN
4     MANAGER
9   PRESIDENT

#### 8.  `List the names of employees who are not eligible for commission.`

In [23]:
# MYSQL Query
q("SELECT ename FROM emp WHERE comm IS NULL OR comm = 0")

     ename
0    SMITH
1    JONES
2    BLAKE
3    CLARK
4    SCOTT
5     KING
6   TURNER
7    ADAMS
8    JAMES
9     FORD
10  MILLER

In [24]:
# Equivalent pandas code
emp[(emp['comm'].isna ()) | ( emp['comm'] == 0) ][['ename']]

     ename
1    SMITH
4    JONES
6    BLAKE
7    CLARK
8    SCOTT
9     KING
10  TURNER
11   ADAMS
12   JAMES
13    FORD
14  MILLER

#### 9.  `List the name and designation of the employee who does not report to anybody.`

In [25]:
# MYSQL Query
q("SELECT ename AS name, job AS designation FROM emp where mgr IS NULL")

   name designation
0  KING   PRESIDENT

In [26]:
# Equivalent pandas code
emp[emp['mgr'].isna()][['ename','job']].rename(columns ={'ename':'name', 'job':'designation'})

   name designation
9  KING   PRESIDENT

#### '10. `List the employees not assigned to any department.`

In [27]:
# MYSQL Query
q("SELECT ename FROM emp where deptno IS NULL")

Empty DataFrame
Columns: [ename]
Index: []

In [28]:
# Equivalent pandas code
emp[emp['deptno'].isna()][['ename']]

Empty DataFrame
Columns: [ename]
Index: []

#### 11.  `List the employees who are eligible for commission.`

In [29]:
# MYSQL Query
q("SELECT ename FROM emp WHERE comm IS NOT NULL AND comm != 0")

    ename
0  DHIRAJ
1   ALLEN
2    WARD
3  MARTIN

In [30]:
# Equivalent pandas code
emp[emp['comm'].notna() & ( emp['comm'] != 0)][['ename']]

    ename
0  DHIRAJ
2   ALLEN
3    WARD
5  MARTIN

#### 12.  `List employees whose names either start or end with “S”.`

In [31]:
# MYSQL Query
q("SELECT ename FROM emp WHERE ename LIKE 'S%' OR ename LIKE '%S'")

   ename
0  SMITH
1  JONES
2  SCOTT
3  ADAMS
4  JAMES

In [32]:
# Equivalent pandas code
emp[emp['ename'].str.contains(r'^S|S$', case=False, na=False)][['ename']]

    ename
1   SMITH
4   JONES
8   SCOTT
11  ADAMS
12  JAMES

#### 13.  `List names of employees whose names have “i” as the second character.`

In [33]:
# MYSQL Query
q("SELECT ename FROM emp WHERE ename LIKE'_i%'")

    ename
0    KING
1  MILLER

In [34]:
# Equivalent pandas code
emp[emp['ename'].str.contains(r'^.i', case=False, na=False)][['ename']]

     ename
9     KING
14  MILLER

#### 14.  `List the number of employees working with the company.`

In [35]:
# MYSQL Query
q("SELECT COUNT(empno) AS Number_of_Employees FROM emp")

   Number_of_Employees
0                   15

In [36]:
# Equivalent pandas code
#emp[['empno']].count().rename({'empno': 'Nunber_of_Employees'}) # same output as below
emp['empno'].agg(Nunber_of_Employees='count')

Nunber_of_Employees    15
Name: empno, dtype: int64

#### 15.  `List the number of designations available in the EMP table.`

In [37]:
# MYSQL Query
q("SELECT count(job) AS Number_of_Designation FROM emp")

   Number_of_Designation
0                     15

In [38]:
# Equivalent pandas code
#emp[['job']].count().rename({'job': 'Nunber_of_designations'})
emp['job'].agg(Nunber_of_designations='count')

Nunber_of_designations    15
Name: job, dtype: int64

#### 16.  `List the total salaries paid to the employees.`

In [39]:
# MYSQL Query
q("SELECT SUM(sal) AS Total_Salaries FROM emp")

   Total_Salaries
0         34025.0

In [40]:
# Equivalent pandas code
#Total_Salaries = emp['sal'].sum()
#print(f'Total_Salaries: {Total_Salaries:.2f}')
emp['sal'].agg(Total_Salaries='sum')

Total_Salaries    34025.0
Name: sal, dtype: float64

#### 17.  `List the maximum, minimum and average salary in the company.`

In [41]:
# MYSQL Query
q("SELECT MAX(sal) AS Maximum_Salary, MIN(sal) AS Minimum_Salary, AVG(Sal) AS Average_salary FROM emp")

   Maximum_Salary  Minimum_Salary  Average_salary
0          5000.0           800.0     2268.333333

In [42]:
# Equivalent pandas code
emp["sal"].agg(
    Maximum_Salary="max", Minimum_Salary="min", Average_salary="mean"
)

Maximum_Salary    5000.000000
Minimum_Salary     800.000000
Average_salary    2268.333333
Name: sal, dtype: float64

#### 18.  `List the maximum salary paid to a salesman`

In [43]:
# MYSQL Query
q("SELECT MAX(sal) FROM emp where job = 'salesman'")

   MAX(sal)
0    1600.0

In [44]:
# Equivalent pandas code
emp[emp['job'] == 'SALESMAN']['sal'].agg(Maximum_Salary='max')

Maximum_Salary    1600.0
Name: sal, dtype: float64